### ISSUE TITLE
cross/circular references causes errors in <ion-select>

### ISSUE THREAD

**Issue by rolandjitsu** [ionic-team/ionic#11497]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Using an `<ion-select>` with object that has circular references fails:
```html
<ion-list>
    <ion-item>
        <ion-label>Controller</ion-label>
        <ion-select [(ngModel)]="controller" [disabled]="isWorking">
            <ion-option *ngFor="let controller of unit.controllers" [value]="controller">
                {{controller.name}}
            </ion-option>
        </ion-select>
    </ion-item>
</ion-list>
```

The error:
```text
ERROR Error: Uncaught (in promise): TypeError: Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at deepEqual (http://localhost:8100/build/main.js:14880:39)
    at Select._inputShouldChange (http://localhost:8100/build/main.js:79546:102)
    at Select.BaseInput._writeValue (http://localhost:8100/build/main.js:39776:145)
    at Select.BaseInput.writeValue (http://localhost:8100/build/main.js:39749:18)
    at http://localhost:8100/build/main.js:26075:27
    at http://localhost:8100/build/main.js:27264:65
    at Array.forEach (native)
    at FormControl.setValue (http://localhost:8100/build/main.js:27264:28)
    at http://localhost:8100/build/main.js:28670:60
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11562)
    at Object.onInvoke (http://localhost:8100/build/main.js:4404:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11502)
    at n.run (http://localhost:8100/build/polyfills.js:3:6468)
    at http://localhost:8100/build/polyfills.js:3:3767
    at JSON.stringify (<anonymous>)
    at deepEqual (http://localhost:8100/build/main.js:14880:39)
    at Select._inputShouldChange (http://localhost:8100/build/main.js:79546:102)
    at Select.BaseInput._writeValue (http://localhost:8100/build/main.js:39776:145)
    at Select.BaseInput.writeValue (http://localhost:8100/build/main.js:39749:18)
    at http://localhost:8100/build/main.js:26075:27
    at http://localhost:8100/build/main.js:27264:65
    at Array.forEach (native)
    at FormControl.setValue (http://localhost:8100/build/main.js:27264:28)
    at http://localhost:8100/build/main.js:28670:60
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11562)
    at Object.onInvoke (http://localhost:8100/build/main.js:4404:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:11502)
    at n.run (http://localhost:8100/build/polyfills.js:3:6468)
    at http://localhost:8100/build/polyfills.js:3:3767
    at d (http://localhost:8100/build/polyfills.js:3:3991)
    at l (http://localhost:8100/build/polyfills.js:3:3244)
    at http://localhost:8100/build/polyfills.js:3:3798
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12256)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4395:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:12177)
    at n.runTask (http://localhost:8100/build/polyfills.js:3:7153)
    at a (http://localhost:8100/build/polyfills.js:3:2312)
    at HTMLButtonElement.invoke (http://localhost:8100/build/polyfills.js:3:13253)
defaultErrorLogger @ core.es5.js:1084
ErrorHandler.handleError @ core.es5.js:1144
next @ core.es5.js:4754
schedulerFn @ core.es5.js:3828
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ core.es5.js:3814
NgZone.triggerError @ core.es5.js:4185
onHandleError @ core.es5.js:4146
t.handleError @ polyfills.js:3
n.runGuarded @ polyfills.js:3
(anonymous) @ polyfills.js:3
a @ polyfills.js:3
invoke @ polyfills.js:3
```

The function that causes this seems to be (which makes sense):
```js
function deepEqual(a, b) {
    if (a === b) {
        return true;
    }
    return JSON.stringify(a) === JSON.stringify(b);
}
```

**Expected behavior:**

It should work with objects that have circular references.

**Steps to reproduce:**

Just run a sample app and use objects that reference themselves, such as:
```ts
class Foo {
    bar: Bar;
}

class Bar {
    foo: Foo;
}
```

**Related code:**

```
insert any relevant code here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Cordova CLI: 6.5.0 
Ionic Framework Version: 3.1.1
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.6
ios-deploy version: Not installed
ios-sim version: Not installed
OS: macOS Sierra
Node Version: v7.4.0
Xcode version: Xcode 8.3.2 Build version 8E2002
```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.
