### ISSUE TITLE
e2e tests fail to run

### ISSUE THREAD

**Issue by imgx64** [ionic-team/ionic#11551]
**Ionic version:**  (check one with "x")
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report

**Current behavior:**
Running `gulp e2e.watch --f=button/basic` fails with;

```
> gulp e2e.watch --f=button/basic
[11:05:29] Using gulpfile ~\ionic\gulpfile.js
[11:05:29] Starting 'e2e.prepare'...
[11:05:29] Starting 'e2e.clean'...
[11:05:29] Finished 'e2e.clean' after 126 ms
[11:05:29] Starting 'e2e.polyfill'...
[11:05:58] Finished 'e2e.polyfill' after 29 s
[11:05:58] Starting 'e2e.prepareSass'...
[11:05:58] Finished 'e2e.prepareSass' after 2.42 ms
[11:05:58] Finished 'e2e.prepare' after 29 s
[11:05:58] Starting 'e2e.watch'...
Running ionic-app-scripts serve with button/basic
node ./node_modules/.bin/ionic-app-scripts serve --appEntryPoint C:\Users\redacted\ionic\src\components\button\test\basic\app\main.ts --appNgModulePath C:\Users\redacted\ionic\src\components\button\test\basic\app\app.module.ts --deepLinksDir C:\Users\redacted\ionic\src\components\button\test\basic --srcDir C:\Users\redacted\ionic\src --wwwDir C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\www --tsconfig C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\tsconfig.json --readConfigJson false --ionicAngularDir C:\Users\redacted\ionic\src --sass scripts\e2e\sass.config.js --copy scripts\e2e\copy.config.js --enableLint false --bonjour
C:\Users\redacted\ionic\node_modules\.bin\ionic-app-scripts:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
[11:05:58] 'e2e.watch' errored after 195 ms
[11:05:58] Error: App-scripts failed with non-zero status code
    at ChildProcess.<anonymous> (C:\Users\redacted\ionic\scripts\gulp\util.ts:229:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I tried to fix it by changing `scripts/gulp/util.ts` from: (why is trying to run a shell script using node?)
``` 
    const args = ['./node_modules/.bin/ionic-app-scripts'].concat(scriptArgs);
```
to
```
    const args = ['./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js'].concat(scriptArgs);
```

But then I got other errors:
```
[11:12:07]  ionic-app-scripts 1.3.7
[11:12:07]  watch started ...
[11:12:07]  build dev started ...
[11:12:08]  clean started ...
[11:12:08]  clean finished in 3 ms
[11:12:08]  copy started ...
[11:12:08]  transpile started ...
[11:13:49]  typescript: .../ionic/src/components/action-sheet/test/basic/e2e.ts, line: 3
            Cannot find name 'it'.

       L3:  it('should open action sheet', function() {
       L4:    element(by.css('.e2eOpenActionSheet')).click();

[11:13:49]  typescript: .../ionic/src/components/action-sheet/test/basic/e2e.ts, line: 7
            Cannot find name 'it'.

       L7:  it('should close with backdrop click', function() {
       L8:    element(by.css('ion-backdrop')).click();

[11:13:49]  typescript: .../ionic/src/components/alert/test/basic/e2e.ts, line: 3
            Cannot find name 'it'.

       L3:  it('should open basic alert', function() {
       L4:    element(by.css('.e2eOpenAlert')).click();

[11:13:49]  typescript: .../ionic/src/components/alert/test/basic/e2e.ts, line: 7
            Cannot find name 'it'.
```
And hundreds more similar errors.

**Expected behavior:**
e2e tests should run.

**Steps to reproduce:**
Clone ionic repository, then run `gulp e2e.watch --f=button/basic`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
> ionic info

Your system information:

 ordova CLI: 7.0.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.3
Xcode version: Not installed```

**Comment by jgw96** [comment]
Thanks for opening an issue with us, we will look into this.

**Comment by brandyscarney** [comment]
Can you try running it on this branch and see if you get a different error?

https://github.com/driftyco/ionic/tree/e2e-serve

**Comment by imgx64** [comment]
Now I'm getting this error:

```
> git status
On branch e2e-serve
nothing to commit, working tree clean

> gulp e2e.watch --f=button/basic
[07:24:21] Using gulpfile ~\ionic\gulpfile.js
[07:24:21] Starting 'e2e.prepare'...
[07:24:21] Starting 'e2e.clean'...
[07:24:21] Finished 'e2e.clean' after 163 ms
[07:24:21] Starting 'e2e.polyfill'...
[07:24:28] Finished 'e2e.polyfill' after 7.02 s
[07:24:28] Starting 'e2e.prepareSass'...
[07:24:28] Finished 'e2e.prepareSass' after 1.03 ms
[07:24:28] Finished 'e2e.prepare' after 7.2 s
[07:24:28] Starting 'e2e.watch'...
Running ionic-app-scripts serve with button\basic
C:\Users\redacted\ionic\node_modules\.bin\ionic-app-scripts.cmd serve --appEntryPoint C:\Users\redacted\ionic\src\components\button\test\basic\app\main.ts --appNgModulePath C:\Users\redacted\ionic\src\components\button\test\basic\app\app.module.ts --deepLinksDir C:\Users\redacted\ionic\src\components\button\test\basic --srcDir C:\Users\redacted\ionic\src --wwwDir C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\www --tsconfig C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\tsconfig.json --readConfigJson false --ionicAngularDir C:\Users\redacted\ionic\src --sass scripts\e2e\sass.config.js --copy scripts\e2e\copy.config.js --enableLint false
[07:24:30]  ionic-app-scripts 1.3.4
[07:24:30]  watch started ...
[07:24:30]  build dev started ...
[07:24:30]  clean started ...
[07:24:30]  clean finished in 2 ms
[07:24:30]  copy started ...
[07:24:30]  transpile started ...
[07:25:21]  typescript: .../ionic/src/components/action-sheet/test/basic/e2e.ts, line: 3
            Cannot find name 'it'.

       L3:  it('should open action sheet', function() {
       L4:    element(by.css('.e2eOpenActionSheet')).click();

[07:25:21]  typescript: .../ionic/src/components/action-sheet/test/basic/e2e.ts, line: 7
            Cannot find name 'it'.

       L7:  it('should close with backdrop click', function() {
       L8:    element(by.css('ion-backdrop')).click();

[07:25:21]  typescript: .../ionic/src/components/alert/test/basic/e2e.ts, line: 3
            Cannot find name 'it'.

[ ... Removed hundreds of lines ... ]

       L3:  it('should open basic alert', function() {
       L4:    element(by.css('.e2eOpenAlert')).click();
[07:25:26]  typescript: .../ionic/src/util/test/util.spec.ts, line: 345
            Cannot find name 'it'.

     L345:      it('should return a value lazily', () => {
     L346:        expect(util.requestIonicCallback(() => { return 1; })).toEqual(1);

[07:25:26]  typescript: .../ionic/src/util/test/util.spec.ts, line: 346
            Cannot find name 'expect'.

     L345:  it('should return a value lazily', () => {
     L346:    expect(util.requestIonicCallback(() => { return 1; })).toEqual(1);
     L347:  });

[07:25:26]  typescript error
            Cannot find type definition file for 'jasmine'.

[07:25:26]  typescript error
            Cannot find type definition file for 'systemjs'.

[07:25:26]  dev server running: http://localhost:8100/

[07:25:26]  copy finished in 58.94 s
(node:9692) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: A watch configured to watch the following paths failed to start. It likely that a file referenced does not exist: C:\Users\redacted\ionic\src\components\button\test\basic\assets\**\*, C:\Users\redacted\ionic\scripts\e2e\index.html, C:\Users\redacted\ionic\node_modules\ionicons\dist\fonts\**\*, C:\Users\redacted\ionic\src\fonts\**\*, C:\Users\redacted\ionic\dist\e2e\polyfills\polyfills.ng.js, C:\Users\redacted\ionic\node_modules\sw-toolbox\sw-toolbox.js, C:\Users\redacted\ionic\scripts\e2e\e2e.shared.css
^C
```

And a blank page opens at http://localhost:8100/

**Comment by jgw96** [comment]
Hello @imgx64 , are you still getting this issue?

**Comment by imgx64** [comment]
@jgw96 Yes. On latest master:

```
> git log -1
commit 892e14f3344b9ea666793eb24b9c83b6c4d5c919
[...]
> npm install
[...]
> gulp e2e.watch --f=button/basic
[07:29:29] Using gulpfile ~\ionic\gulpfile.js
[07:29:29] Starting 'e2e.prepare'...
[07:29:29] Starting 'e2e.clean'...
[07:29:29] Finished 'e2e.clean' after 35 ms
[07:29:29] Starting 'e2e.polyfill'...
[07:29:39] Finished 'e2e.polyfill' after 9.72 s
[07:29:39] Starting 'e2e.prepareSass'...
[07:29:39] Finished 'e2e.prepareSass' after 913 μs
[07:29:39] Finished 'e2e.prepare' after 9.77 s
[07:29:39] Starting 'e2e.watch'...
Running ionic-app-scripts serve with button/basic
node ./node_modules/.bin/ionic-app-scripts serve --appEntryPoint C:\Users\redacted\ionic\src\components\button\test\basic\app\main.ts --appNgModulePath C:\Users\redacted\ionic\src\components\button\test\basic\app\app.module.ts --deepLinksDir C:\Users\redacted\ionic\src\components\button\test\basic --srcDir C:\Users\redacted\ionic\src --wwwDir C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\www --tsconfig C:\Users\redacted\ionic\dist\e2e\components\button\test\basic\tsconfig.json --readConfigJson false --ionicAngularDir C:\Users\redacted\ionic\src --sass scripts\e2e\sass.config.js --copy scripts\e2e\copy.config.js --enableLint false --bonjour
C:\Users\redacted\ionic\node_modules\.bin\ionic-app-scripts:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
[07:29:39] 'e2e.watch' errored after 102 ms
[07:29:39] Error: App-scripts failed with non-zero status code
    at ChildProcess.<anonymous> (C:\Users\redacted\ionic\scripts\gulp\util.ts:229:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by brandyscarney** [comment]
To update this issue, this branch has some fixes for the windows errors: https://github.com/ionic-team/ionic/tree/e2e-serve

I haven't had a chance to fix the remaining errors that pop up. I think it's definitely a path issue somewhere with Windows, either in the protractor config or the tsconfig.

**Comment by brandyscarney** [comment]
I've merged some changes in that should have fixed this. I've verified the e2e tests are now building on Windows. Please let me know if you're still seeing errors. Thanks!
