### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by unipheas** [ionic-team/ionic#11872]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I created a new app, installed my platforms, linked the app, ran resources, then tried to do 'ionic upload'. It's giving me an error of '_stream_readable.js:545 switch (state.pipesCount) { TypeError: Cannot read property 'pipesCount' of undefined ....

**Expected behavior:**
Successfully upload to Ionic Services

**Steps to reproduce:**

**Related code:**

```
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/usr/local/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/usr/local/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/usr/local/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/usr/local/lib/node_modules/ionic/node_modules/zip-stream/index.js:138:49)
    at Zip.append (/usr/local/lib/node_modules/ionic/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/usr/local/lib/node_modules/ionic/node_modules/archiver/lib/core.js:172:16)
    at Archiver._onQueueTask (/usr/local/lib/node_modules/ionic/node_modules/archiver/lib/core.js:370:8)
    at /usr/local/lib/node_modules/ionic/node_modules/async/dist/async.js:4045:9
    at process (/usr/local/lib/node_modules/ionic/node_modules/async/dist/async.js:2316:17)
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v8.0.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.2 Build version 8E2002 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
```

**Comment by unipheas** [comment]
**update: I ran 'ionic package build android' and got some new information

```
(node:18146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
(node:18146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lathonez** [comment]
I am getting the same error running `ionic upload`:

https://travis-ci.org/lathonez/clicker/builds/237887503?utm_source=email&utm_medium=notification

* [travis.yml](https://github.com/lathonez/clicker/blob/master/.travis.yml)
* [deploy.sh](https://github.com/lathonez/clicker/blob/b42dafec34fc65628e9f254cef538b1f072f5f1c/.travis/deploy.sh)`

The entire build runs fine, just fails to upload.

```
dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!
dpl.2
Preparing deploy
dpl.3
Deploying application
--email=[secure] --password=[secure]
[11:27:23]  build dev started ... 
[11:27:23]  clean started ... 
[11:27:23]  clean finished in 3 ms 
[11:27:23]  copy started ... 
[11:27:23]  transpile started ... 
[11:27:26]  transpile finished in 3.43 s 
[11:27:26]  preprocess started ... 
[11:27:26]  deeplinks started ... 
[11:27:26]  deeplinks finished in 31 ms 
[11:27:26]  preprocess finished in 33 ms 
[11:27:26]  webpack started ... 
[11:27:26]  copy finished in 3.65 s 
[11:27:35]  webpack finished in 9.13 s 
[11:27:35]  sass started ... 
[11:27:37]  sass finished in 1.35 s 
[11:27:37]  postprocess started ... 
[11:27:37]  postprocess finished in 5 ms 
[11:27:37]  lint started ... 
[11:27:37]  build dev finished in 14.03 s 
_stream_readable.js:545
  switch (state.pipesCount) {
               ^
TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:184:11)
    at module.exports.ZipArchiveOutputStream._appendStream (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:96:20)
    at module.exports.ArchiveOutputStream.entry (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/compress-commons/lib/archivers/archive-output-stream.js:88:10)
    at module.exports.ZipStream.entry (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/zip-stream/index.js:138:49)
    at Zip.append (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/archiver/lib/plugins/zip.js:53:15)
    at Archiver._moduleAppend (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/archiver/lib/core.js:172:16)
    at Archiver._onQueueTask (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/archiver/lib/core.js:370:8)
    at /home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/async/dist/async.js:4045:9
    at Object.process (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/ionic/node_modules/async/dist/async.js:2316:17)
Script failed with status 1
failed to deploy
```

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2375
