### ISSUE TITLE
Error installing plugins, [ImagePicker] for example

### ISSUE THREAD

**Issue by MrFirases** [ionic-team/ionic#11936]
**Ionic version:
[ ] **1.x**
[ ] **2.x**
[ x] **3.x**

**I'm submitting a
[x ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

Error installing **plugins** with **Github link**, for example: "**ionic cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker**". 
The error was because the file package.json was missing from the ImagePicker pluging after the last update of cordova, but two days later Telerik-Verified-Plugins fixed this problem and added the package.json file after many users reports. That's does not fix the problem and we still getting errors while installing plugins.

**Steps to reproduce:**
```
ionic cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker
```

**Results:**

```
 cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add https://github.com/Telerik-Verified-Plugins/ImagePicker --sav... (exit code 1):

        Error: Failed to fetch plugin https://github.com/Telerik-Verified-Plugins/ImagePicker via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\moham\AppData\Roaming\npm-cache\_logs\2017-06-06T07_22_17_209Z-debug.log
```

This is the content of the 2017-06-06T07_22_17_209Z-debug.log file:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\moham\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/Telerik-Verified-Plugins/ImagePicker',
1 verbose cli   '--save' ]
2 info using npm@5.0.0
3 info using node@v6.9.4
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 silly fetchPackageMetaData error for git+https://github.com/Telerik-Verified-Plugins/ImagePicker.git exited with error code: 128
7 verbose stack Error: exited with error code: 128
7 verbose stack     at ChildProcess.onexit (C:\Users\moham\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
7 verbose stack     at emitTwo (events.js:106:13)
7 verbose stack     at ChildProcess.emit (events.js:191:7)
7 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
8 verbose cwd C:\Users\moham\Desktop\asb\node_modules
9 verbose Windows_NT 10.0.15063
10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\moham\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Telerik-Verified-Plugins/ImagePicker" "--save"
11 verbose node v6.9.4
12 verbose npm  v5.0.0
13 error exited with error code: 128
14 verbose exit [ 1, true ]
```

**Comment by jgw96** [comment]
Hello, thanks for using Ionic! Since this seems to be an issue with the Telerik imagePicker plugin I would recommend opening an issue with them.
