### ISSUE TITLE
bug: `ionic serve` crashes in tiny-lr

### ISSUE THREAD

**Issue by Polyergic** [ionic-team/ionic#12191]
**Type**: <span ionic-type>bug</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>desktop</span>  <span ionic-webview>browser</span>

<span ionic-description>`ionic serve` occasionally crashes in tiny-lr with output as below.

I've submitted a pull request to tiny-lr that should fix the immediate error:  https://github.com/mklabs/tiny-lr/pull/125

```
/Users/ssterling3/path/to/project/node_modules/tiny-lr/src/server.js:266
      console.error('... Uhoh. Got error %s ...', e.message);
                                                   ^

TypeError: Cannot read property 'message' of undefined
    at Server.error (/Users/ssterling3/path/to/project/node_modules/tiny-lr/src/server.js:266:52)
    at Socket.<anonymous> (/Users/ssterling3/path/to/project/node_modules/tiny-lr/src/server.js:217:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:481:13)
    at Socket._destroy (net.js:522:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:816:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mobile-dashboard@ ionic:serve: `ionic-app-scripts serve "--v2" "--address" "0.0.0.0" "--port" "8100" "--livereload-port" "35729"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mobile-dashboard@ ionic:serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ssterling3/.npm/_logs/2017-06-28T14_04_11_658Z-debug.log
```</span>

<span is-issue-template></span>

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2479
