### ISSUE TITLE
Unable to Install Ionic Native Screen Orientation

### ISSUE THREAD

**Issue by iamchairs** [ionic-team/ionic#12279]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

```
PS C:\dev\theatreApp> ionic cordova plugin add cordova-plugin-screen-orientation
> cordova plugin add cordova-plugin-screen-orientation --save
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.

[ERROR] An error occurred while running cordova plugin add cordova-plugin-screen-orientation --save (exit code 1):

        Installing "cordova-plugin-screen-orientation" for android
        Failed to install 'cordova-plugin-screen-orientation': Error
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:205:33
        at _rejected
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:864:24)
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:890:30
        at Promise.when
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:1142:31)
        at Promise.promise.promiseDispatch
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:808:41)
        at C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:624:44
        at runSingle
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:137:13)
        at flush
        (C:\Users\Micah\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-fetch\node_modules\q\q.js:125:13)
        at _combinedTickCallback (internal/process/next_tick.js:95:7)
        at process._tickCallback (internal/process/next_tick.js:161:9)
        Error: Failed to fetch plugin https://github.com/vstirbu/PromisesPlugin.git via registry.
        Probably this is either a connection problem, or plugin spec is incorrect.
        Check your connection and plugin name/version/URL.
        Error: cmd: Command failed with exit code 1 Error output:
        npm ERR! Error while executing:
        npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
        npm ERR!
        npm ERR! fatal: Unable to find remote helper for 'https'
        npm ERR!
        npm ERR! exited with error code: 128

        npm ERR! A complete log of this run can be found in:
        npm ERR!     C:\Users\Micah\AppData\Roaming\npm-cache\_logs\2017-07-06T21_26_15_824Z-debug.log
```

C:\Users\Micah\AppData\Roaming\npm-cache\_logs\2017-07-06T21_26_15_824Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Micah\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'https://github.com/vstirbu/PromisesPlugin.git',
1 verbose cli   '--save' ]
2 info using npm@5.1.0
3 info using node@v8.1.0
4 verbose npm-session 2417404b05243cca
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/vstirbu/PromisesPlugin.git Error while executing:
7 silly fetchPackageMetaData C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData fatal: Unable to find remote helper for 'https'
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData exited with error code: 128
8 verbose stack Error: exited with error code: 128
8 verbose stack     at ChildProcess.onexit (C:\Users\Micah\AppData\Roaming\npm\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
8 verbose stack     at emitTwo (events.js:125:13)
8 verbose stack     at ChildProcess.emit (events.js:213:7)
8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
9 verbose cwd C:\dev\theatreApp\node_modules
10 verbose Windows_NT 10.0.15063
11 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Micah\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/vstirbu/PromisesPlugin.git" "--save"
12 verbose node v8.1.0
13 verbose npm  v5.1.0
14 error Error while executing:
14 error C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/vstirbu/PromisesPlugin.git
14 error
14 error fatal: Unable to find remote helper for 'https'
14 error
14 error exited with error code: 128
15 verbose exit [ 1, true ]
```

**Steps to reproduce:**

Follow installation instructions at https://ionicframework.com/docs/native/screen-orientation/

Run `ionic cordova plugin add cordova-plugin-screen-orientation`

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.8
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.1.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0
```

**Comment by russcarver** [comment]
I've been dealing with this for a week as well.  Any update?

**Comment by AmitMY** [comment]
Try removing your platforms & plugins folders, and `ionic cordova prepare`, and try again.

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-native#1778
