### ISSUE TITLE
__webpack_require__.e is undefined in webpackAsyncContext

### ISSUE THREAD

**Issue by iamchairs** [ionic-team/ionic#12446]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ x] **3.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I don't strictly know how to reproduce this but it's not behaving in a reproduceable way. I have an app that I just started implementing `IonicPage`. I have 3 page components that are now using the `IonicPage` decorator. I went to add a 4th page, and after including the new module in my `app.module.ts`, I started getting this error after navigating to any page after the app loads (i can be an unrelated page).

> core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: undefined is not a function
> TypeError: undefined is not a function
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:94664:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:82492:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:82457:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:61796:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26002:39)
>     at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:25985:25)
>     at getComponent (http://localhost:8100/build/main.js:35246:23)
>     at convertToView (http://localhost:8100/build/main.js:35264:16)
>     at convertToViews (http://localhost:8100/build/main.js:35283:32)
>     at Array.map (native)
>     at webpackAsyncContext (http://localhost:8100/build/main.js:94664:34)
>     at loadAndCompile (http://localhost:8100/build/main.js:82492:36)
>     at NgModuleLoader.load (http://localhost:8100/build/main.js:82457:83)
>     at ModuleLoader.load (http://localhost:8100/build/main.js:61796:44)
>     at DeepLinker.getNavLinkComponent (http://localhost:8100/build/main.js:26002:39)
>     at DeepLinker.getComponentFromName (http://localhost:8100/build/main.js:25985:25)
>     at getComponent (http://localhost:8100/build/main.js:35246:23)
>     at convertToView (http://localhost:8100/build/main.js:35264:16)
>     at convertToViews (http://localhost:8100/build/main.js:35283:32)
>     at c (http://localhost:8100/build/polyfills.js:3:13535)
>     at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
>     at NavControllerBase._fireError (http://localhost:8100/build/main.js:49542:16)
>     at NavControllerBase._failed (http://localhost:8100/build/main.js:49530:14)
>     at http://localhost:8100/build/main.js:49585:59
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
>     at Object.onInvoke (http://localhost:8100/build/main.js:4166:33)
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
>     at r.run (http://localhost:8100/build/polyfills.js:3:4452)
>     at http://localhost:8100/build/polyfills.js:3:14076

I removed the import and the problem went away. I took a look at what `__webpack_require__.e` was and when it works it is `ensureRequire` and appears to be a part of the chunking process, and when it is not working, it is not defined.

I tore everything out of the module and the page until I was at the point where I only had a single ts file that exported-

```
export class X { }

import {X} from './pages/x/x.page.ts'
console.log(X);
```

And it was still broken. I removed the new directory entirely and now I'm getting the error with or without the new page/module.

I can't see any pattern here. If this sounds confusing and maybe not enough to go on- I know!

Why would `ensureRequire` not be set in `main.js`?
If the polyfills need to be updated, how do I do that?

**Expected behavior:**

**Steps to reproduce:**

I don't know!

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v8.1.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0
```

**Comment by iamchairs** [comment]
No idea why that was happening but upgraded to `@ionic/app-scripts` 2.0.2 (warning, read about the breaking change) and it went away.
