### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by bishanshan** [ionic-team/ionic#12493]
[DEBUG] CLI flags: { interactive: true, confirm: false }
[DEBUG] { cwd: 'C:\\Users\\bss\\Documents\\work\\TestApp', local: true, binPath:
        'C:\\Users\\bss\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath:
        'C:\\Users\\bss\\Documents\\work\\TestApp\\node_modules\\ionic\\dist\\index.js' }
[DEBUG] Loading local plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] Daemon found (pid: 10984)
[DEBUG] Getting plugin info for ionic
[DEBUG] Checking for latest plugin version of ionic@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-proxy
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-proxy@latest.
[DEBUG] Getting plugin info for @ionic/cli-plugin-ionic-angular
[DEBUG] Checking for latest plugin version of @ionic/cli-plugin-ionic-angular@latest.
Running app-scripts build: --log-level debug

[17:13:11]  build dev started ...
[17:13:11]  clean started ...
[17:13:11]  clean finished in less than 1 ms
[17:13:11]  copy started ...
[17:13:11]  transpile started ...
[17:13:13]  transpile finished in 1.94 s
[17:13:13]  preprocess started ...
[17:13:13]  deeplinks started ...
[17:13:13]  deeplinks finished in 15 ms
[17:13:13]  preprocess finished in 31 ms
[17:13:13]  webpack started ...
[17:13:13]  copy finished in 2.09 s
[17:13:19]  webpack finished in 6.45 s
[17:13:19]  sass started ...
[17:13:20]  sass finished in 890 ms
[17:13:20]  postprocess started ...
[17:13:20]  postprocess finished in 16 ms
[17:13:20]  lint started ...
[17:13:20]  build dev finished in 9.34 s
√ Requesting snapshot upload - done!
\ Uploading snapshot [17:13:22]  lint finished in 2.00 s
× Uploading snapshot - failed!
Error: connect ECONNREFUSED 127.0.0.1:443
[DEBUG] Error: connect ECONNREFUSED 127.0.0.1:443
        at Object.exports._errnoException (util.js:1018:11)
        at exports._exceptionWithHostPort (util.js:1041:20)
        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

**Comment by jgw96** [comment]
This issue was moved to ionic-team/ionic-cli#2582
