### ISSUE TITLE
IONIC SERVE gets ERR_CONNECTION_RESET 

### ISSUE THREAD

**Issue by nicolasmgago** [ionic-team/ionic#12669]
**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

Hello. Thanks in advance for future help and sorry for my english, it is not my first language.

When running ionic serve in my application I get ERR_CONNECTION_RESET on Chrome.

This was working long time ago. And it is still working on other branch from the same application which has much less code of course. 

I'm not being able to detect the problem. My command console gets 

"TypeError: Cannot read property 'toString' of undefined
    at injectLiveReloadScript ... AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic1\serve.js:115:29)
    at ReadFileContext.fs.readFile [as callback] (...\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\ionic1\serve.js:158:33)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)"

**Comment by nicolasmgago** [comment]
Nevermind, somehow index.html was being deleted...
