### ISSUE TITLE
Build fails when trying to import a file in a custom folder.

### ISSUE THREAD

**Issue by jayserdny** [ionic-team/ionic#13164]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**Current behavior:**
Build fails when trying to import something outside Ionic source folder. The project is a normal Ionic project with Meteor api. Project runs fine using `ionic cordova run android --prod --release --aot --livereload`. However, it fails when `livereload` flag is not given. With ionic serve, project runs without any problem. The only way to run the project right now is by using `cordova run android` command. I asked about this in the @Urigo repo for his tutorial [Whatsapp clone using Ionic cli](https://angular-meteor.com/tutorials/whatsapp2/ionic/setup) and they confirmed that this issue is not related to their implementation.

**Expected behavior:**
The expected behavior should be to run the app without this compilation error.

**Steps to reproduce:**
Make sure to have installed the meteor-client builder before running this app.

1. git clone https://github.com/jayserdny/Ionic2CLI-Meteor-WhatsApp
2. cd Ionic2CLI-Meteor-WhatsApp
3. npm install
4. npm run meteor-client:bundle
5. ionic cordova run android --release --aot

**Output error:**

```
Error: ./api/server/collections/index.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/Jayser/Documents/aplicaciones/firestore/api/server/collections/index.js'
 @ ./src/pages/search/search.ts 10:20-46
 @ ./src/pages/search/search.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts
    at new BuildError (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
    at callback (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/@ionic/app-scripts/dist/webpack.js:123:28)
    at emitRecords.err (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/Jayser/Documents/aplicaciones/firestore/node_modules/webpack/lib/Compiler.js:365:9)
```

**Other information:**
I believe this problem is related to the generate maps from the typescript transpilation beucase I can see the generated maps for each file inside /src folder but not in the api folder. 

**Ionic info:**:

```
     cli packages: (/Users/Jayser/Documents/aplicaciones/firestore/node_modules)

         @ionic/cli-plugin-proxy : 1.4.13
         @ionic/cli-utils        : 1.13.1
         ionic (Ionic CLI)       : 3.13.1

     global packages:

         cordova (Cordova CLI) : 7.1.0 

     local packages:

         @ionic/app-scripts : 3.0.0
         Cordova Platforms  : android 6.3.0 ios 4.5.2
         Ionic Framework    : ionic-angular 3.7.1

    System:

         Android SDK Tools : 26.1.1
         ios-deploy        : 1.9.1 
         Node              : v8.7.0
         npm               : 5.4.2 
         OS                : macOS High Sierra
         Xcode             : Xcode 9.0 Build version 9A235 

     Misc:

         backend : legacy
```
**Webpack config:**

```
var path = require('path');
var webpack = require('webpack');
var ionicWebpackFactory = require(process.env.IONIC_WEBPACK_FACTORY);

var ModuleConcatPlugin = require('webpack/lib/optimize/ModuleConcatenationPlugin');
var PurifyPlugin = require('@angular-devkit/build-optimizer').PurifyPlugin;

var optimizedProdLoaders = [
  {
    test: /\.json$/,
    loader: 'json-loader'
  },
  {
    test: /\.js$/,
    loader: [
      {
        loader: process.env.IONIC_CACHE_LOADER
      },

      {
        loader: '@angular-devkit/build-optimizer/webpack-loader',
        options: {
          sourceMap: true
        }
      },
    ]
  },
  {
    test: /\.ts$/,
    loader: [
      {
        loader: process.env.IONIC_CACHE_LOADER
      },

      {
        loader: '@angular-devkit/build-optimizer/webpack-loader',
        options: {
          sourceMap: true
        }
      },

      {
        loader: process.env.IONIC_WEBPACK_LOADER
      }
    ]
  }
];

function getProdLoaders() {
  if (process.env.IONIC_OPTIMIZE_JS === 'true') {
    return optimizedProdLoaders;
  }
  return devConfig.module.loaders;
}

var devConfig = {
  entry: process.env.IONIC_APP_ENTRY_POINT,
  output: {
    path: '{{BUILD}}',
    publicPath: 'build/',
    filename: '[name].js',
    devtoolModuleFilenameTemplate: ionicWebpackFactory.getSourceMapperFunction(),
  },
  devtool: process.env.IONIC_SOURCE_MAP_TYPE,

  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [path.resolve('node_modules')],
    alias: {
      'api': path.resolve(__dirname, 'api/server')
    }
  },

  externals: [
    {
      sharp: '{}'
    },
    resolveExternals
  ],

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.ts$/,
        loader: process.env.IONIC_WEBPACK_LOADER
      }
    ]
  },

  plugins: [
    ionicWebpackFactory.getIonicEnvironmentPlugin(),
    ionicWebpackFactory.getCommonChunksPlugin(),
    new webpack.ProvidePlugin({
      __extends: 'typescript-extends'
    })
  ],

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    __dirname: true
  }
};

var prodConfig = {
  entry: process.env.IONIC_APP_ENTRY_POINT,
  output: {
    path: '{{BUILD}}',
    publicPath: 'build/',
    filename: '[name].js',
    devtoolModuleFilenameTemplate: ionicWebpackFactory.getSourceMapperFunction(),
  },
  devtool: process.env.IONIC_SOURCE_MAP_TYPE,

  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [path.resolve('node_modules')],
    alias: {
      'api': path.resolve(__dirname, 'api/server')
    }
  },

  externals: [
    resolveExternals
  ],

  module: {
    loaders: getProdLoaders()
  },

  plugins: [
    ionicWebpackFactory.getIonicEnvironmentPlugin(),
    ionicWebpackFactory.getCommonChunksPlugin(),
    new ModuleConcatPlugin(),
    new PurifyPlugin(),
    new webpack.ProvidePlugin({
      __extends: 'typescript-extends'
    })
  ],

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    __dirname: true
  }
};

function resolveExternals(context, request, callback) {
  return resolveMeteor(request, callback) ||
    callback();
}

function resolveMeteor(request, callback) {
  var match = request.match(/^meteor\/(.+)$/);
  var pack = match && match[1];

  if (pack) {
    callback(null, 'Package["' + pack + '"]');
    return true;
  }
}

module.exports = {
  dev: devConfig,
  prod: prodConfig
}
```
**Tsconfig:**
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "baseUrl": ".",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "downlevelIteration": true,
    "lib": [
      "dom",
      "es2015",
      "es2016"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "paths": {
      "api/*": ["./api/server/*"]
    },
    "sourceMap": true,
    "target": "es5",
    "skipLibCheck": true,
    "stripInternal": true,
    "noImplicitAny": false,
    "types": [
      "@types/meteor",
      "@types/underscore",
      "@types/meteor-collection-hooks"
    ]
  },
  "include": [
    "src/**/*.ts",
    "api/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "api/node_modules",
    "api"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

This does not appear to be an issue with the Ionic Framework, but with the Ionic App Scripts (the scripts used to build an Ionic application). I will move this issue to that repo for investigation.

Thank you for using Ionic

**Comment by kensodemann** [comment]
This issue was moved to ionic-team/ionic-app-scripts#1284
