### ISSUE TITLE
VirtualStats error today when building my app

### ISSUE THREAD

**Issue by wowkucko** [ionic-team/ionic#13182]
I am about to completely go crazy. My dear project is no longer working, today when i try to run on my android device, i get the following:

```
[21:01:05]  transpile started ...
[21:01:11]  typescript: .../feederhorgasz/node_modules/@ionic/app-scripts/dist/util/virtual-file-utils.d.ts, line: 3
            Class 'VirtualStats' incorrectly implements interface 'Stats'. Property 'atimeMs' is missing in type
            'VirtualStats'.

       L2:  export declare class VirtualStats implements Stats {
       L3:      protected _path: string;
       L4:      protected _ctime: Date;

Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
    at transpileWorker (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
    at Object.transpile (C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
    at C:\Users\Thomas\mobiledevelopment\feederhorgasz\node_modules\@ionic\app-scripts\dist\buil

```

ionic info:
cli packages: (C:\Users\Thomas\AppData\Roaming\npm\node_modules)

@ionic/cli-utils  : 1.12.0
ionic (Ionic CLI) : 3.12.0
global packages:

cordova (Cordova CLI) : 7.0.1
local packages:

@ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.7.1
System:

Node : v6.11.3
npm  : 3.10.10
OS   : Windows 10
Misc:

backend : pro

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
