### ISSUE TITLE
Naming a tabs component different than "tabs" leads to issue in case of lazy-loaded roots

### ISSUE THREAD

**Issue by DavidStrausz** [ionic-team/ionic#13193]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
When switching between two `ion-tabs` instances and the root pages are lazy loaded the root page of the tab at the selected index does not get set, the page from the previous tabs component stays on the nav-stack.
While putting the repo together I noticed that the underlying problem is the naming of the ts-class (and module) of the tabs component. Naming it `tabs.ts` works just fine but re-naming it to e.g. `TabsContainer.ts` creates the problem. I guess this is because the name is used for generating the DeepLink config/the URL.

With `tabs.ts` after switching the tabs for the first time the the URL is:
`http://localhost:8100/#/tabs/contact/contact`
which is correct.

With `TabsContainer.ts` after switching the tabs for the first time the URL is:
`http://localhost:8100/#/TabsContainer/contact/about`
which is incorrect.

**Expected behavior:**
Naming a tabs component differnt than "tabs" should not cause problems with lazy loading/deep link config.

**Steps to reproduce:**
- Clone the example repo
- Run `npm install`
- Run `ionic serve`
- Watch tabs/pages/url (tabs are switched ever 7.5 seconds)

**Related code:**
Example github repo [here](https://github.com/DavidStrausz/lazy-tab-roots).

**Other information:**
- As suggested by @kensodemann [here](https://github.com/ionic-team/ionic/issues/12625#issuecomment-338008704) this can be worked around by explicitly naming the segment of the tabs component `tabs` in the `@IonicPage` decorator.
- It works with eagerly loaded tab roots
- The issue occurs since Ionic 3.6.0 (nav url refactoring)

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages:
    @ionic/cli-utils  : 1.13.1
    ionic (Ionic CLI) : 3.13.2

global packages:
    cordova (Cordova CLI) : 7.1.0

local packages:
    @ionic/app-scripts : 3.0.0-201710161925
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1-201710181432

System:
    Node : v6.11.0
    npm  : 5.1.0
    OS   : Windows 10

Misc:
    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening this. I'll consult with @danbucholtz on whether this should be fixed in v3 or if we should just make sure it works correctly in v4 given that we a.) have a workaround in v3 and b.) v4 is going to have a fair amount of navigation-related changes. I'll mark it as v4 for now.

**Comment by iget-master** [comment]
@kensodemann This workaround doens't works. Since I can not set two tabs with the same segment:

> There are multiple entries in the deeplink config with the segment of tabs
>     at new BuildError (/home/.../node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
>     at /home/.../node_modules/@ionic/app-scripts/dist/deep-linking.js:57:21
>     at <anonymous>

I really think that this kind of bugs are critical, and people can not wait until someday you guys release the v4 (that will with sure will have many, many breaking changes).

Again I think that Ionic team don't care anymore about v3, since there are many and many critical issues open without solutions, only work arounds.

**Comment by fishgrind** [comment]
@iget-master found another workaround by mistake today,

for your first one do:

`@IonicPage(
  {
    priority: 'high',
    segment: 'tabs'
}`

and for your second one:

`@IonicPage(
  {
    priority: 'high',
    segment: 'tabs/'
}`

adding the slash somehow passes the check but is still seen as if it's without a slash and works for me!

Crappy workaround but at least it works for now...
