### ISSUE TITLE
Error on build a fresh blank sample

### ISSUE THREAD

**Issue by raugaral** [ionic-team/ionic#13342]
**Ionic version:**  (check one with "x")
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x ] bug report
[ ] feature request

**Current behavior:**
I have got a new ubuntu machine. Than I have installed all packages and dependences, node, java, android studio... 
I had create a new project using `ionic start blank blank` and ran `ionic serve`, up here all right ...
The Error comes when i try to build the project. `ionic build` don't have any error but the cordova yes. The error is produced by one gradle script.

`ionic cordova build android` show an error and not compile

**Expected behavior:**
`ionic cordova build android` compile the project

**Other information:**
Tracktrace:
```
> cordova build android
ANDROID_HOME=/home/raul/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
Subproject Path: CordovaLib
[13:41:45]  lint finished in 3.04 s 

FAILURE: 
Build failed with an exception.


* What went wrong:

A problem occurred configuring root project 'android'.

> 
Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve net.sf.proguard:proguard-gradle:5.2.1.
     Required by:
         project : > com.android.tools.build:gradle:2.2.3 > com.android.tools.build:gradle-core:2.2.3
      > Could not resolve net.sf.proguard:proguard-gradle:5.2.1.
         > Could not get resource 'https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

node -v: v6.11.5
npm -v: 3.10.10
gradle --version: Gradle 4.1
JVM: 1.8.0_144

ionic info
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v6.11.5
    npm               : 3.10.10 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/raul/Android/Sdk

Misc:

    backend : pro

**Comment by raugaral** [comment]
if I ran the build command as sudo I have another error:
```
Exception in thread "main" 
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)

	at org.gradle.wrapper.Download.download(Download.java:51)
	at org.gradle.wrapper.Install$1.call(Install.java:62)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by raugaral** [comment]
Was a Java + ubuntu problem...
apt purge apenjdk*
apt autoclean 
apt autoremove
restart 
apt install openjdk-8-*

... and works!

**Comment by martispaul** [comment]
Hello, 
I had the same issue, I solved by updating the Java JDK to a newer version.

**Comment by siddrc** [comment]
@martispaul what jdk version are you using now?

**Comment by martispaul** [comment]
@siddrc jdk 1.8.0_171
