### ISSUE TITLE
ionic command is not working

### ISSUE THREAD

**Issue by RakeshKW** [ionic-team/ionic#13352]
i just install node on mac pc and then i installed ionic.
when i type command on terminal node -v it shows v8.9.1 .It means node is installed. But when i type command ionic it shows following error:
 Nirajs-MacBook-2:~ nirajviveksheel$ ionic
module.js:538
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

Please tell me solution ......

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
