### ISSUE TITLE
Ionic 3.9.2 Build Fails using --prod with browser

### ISSUE THREAD

**Issue by morrisonbrett** [ionic-team/ionic#13368]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
Build fails

**Expected behavior:**
Build should pass

**Steps to reproduce:**
In package.json scripts:

```
    "build-dev": "ionic-app-scripts build -- --dev",
    "build-prod": "ionic-app-scripts build -- --prod",
    "build-dev-browser": "npm run build-dev && cordova build browser --debug",
    "build-prod-browser": "npm run build-prod && cordova build browser --release",
```

Works:
```
$ npm run build-dev-browser
```

Fails:
```
$ npm run build-prod-browser
```

Output from fail:

```
[14:21:00]  copy finished in 11.82 s
[14:21:07]  ionic-app-script task: "build"
[14:21:07]  Error: ./src/app/main.ts Module not found: Error: Can't resolve './app.module.ngfactory' in
            'D:\dev\mckissock\Colibri.Dashboard\src\app' resolve './app.module.ngfactory' in
            'D:\dev\mckissock\Colibri.Dashboard\src\app' using description file:
            D:\dev\mckissock\Colibri.Dashboard\package.json (relative path: ./src/app) Field 'browser' doesn't contain a
            valid alias configuration after using description file: D:\dev\mckissock\Colibri.Dashboard\package.json
            (relative path: ./src/app) using description file: D:\dev\mckissock\Colibri.Dashboard\package.json (relative
            path: ./src/app/app.module.ngfactory) no extension Field 'browser' doesn't contain a valid alias
            configuration D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory doesn't exist .ts Field
            'browser' doesn't contain a valid alias configuration
            D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.ts doesn't exist .js Field 'browser' doesn't
            contain a valid alias configuration D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.js
            doesn't exist .json Field 'browser' doesn't contain a valid alias configuration
            D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.json doesn't exist as directory
            D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory doesn't exist
            [D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory]
            [D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.ts]
            [D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.js]
            [D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.json]
            [D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory] @ ./src/app/main.ts 2:0-60
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'D:\dev\mckissock\Colibri.Dashboard\src\app'
resolve './app.module.ngfactory' in 'D:\dev\mckissock\Colibri.Dashboard\src\app'
  using description file: D:\dev\mckissock\Colibri.Dashboard\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\dev\mckissock\Colibri.Dashboard\package.json (relative path: ./src/app)
    using description file: D:\dev\mckissock\Colibri.Dashboard\package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.json doesn't exist
      as directory
        D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory doesn't exist
[D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory]
[D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.ts]
[D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.js]
[D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory.json]
[D:\dev\mckissock\Colibri.Dashboard\src\app\app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at new BuildError (D:\dev\mckissock\Colibri.Dashboard\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (D:\dev\mckissock\Colibri.Dashboard\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\Compiler.js:368:12)
    at next (D:\dev\mckissock\Colibri.Dashboard\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\dev\mckissock\Colibri.Dashboard\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\dev\mckissock\Colibri.Dashboard\node_modules\webpack\lib\Compiler.js:365:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! colibridashboard@2.0.0 build-prod: `gulp default && ionic-app-scripts build -- --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the colibridashboard@2.0.0 build-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\b\AppData\Roaming\npm-cache\_logs\2017-11-08T22_21_07_587Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! colibridashboard@2.0.0 build-prod-browser: `gulp default && npm run build-prod && cordova build browser --release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the colibridashboard@2.0.0 build-prod-browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\b\AppData\Roaming\npm-cache\_logs\2017-11-08T22_21_07_612Z-debug.log

b@pg0 MINGW64 /d/dev/mckissock/Colibri.Dashboard (test) $
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
$ ionic info

cli packages: (C:\Users\b\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.17.0
    ionic (Ionic CLI) : 3.17.0

global packages:

    cordova (Cordova CLI) : 7.1.0
    Gulp CLI              : CLI version 1.4.0 Local version 3.9.1

local packages:

    @ionic/app-scripts : 3.1.0
    Cordova Platforms  : browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.0
    npm               : 5.5.1
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : F:\Android\Sdk

Misc:

    backend : legacy

b@pg0 MINGW64 /d/dev/mckissock/Colibri.Dashboard (test) $
```

**Comment by bogomips** [comment]
same here

**Comment by vksgautam1** [comment]
same issue here
https://github.com/ionic-team/ionic/issues/13356

**Comment by qcnguyen** [comment]
same here

**Comment by CoreyCole** [comment]
Same here, but I'm getting 
```
ionic-app-scripts build --prod
```
```
/Users/clutch/.config/yarn/global/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
    at module.exports (/Users/clutch/.config/yarn/global/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/clutch/.config/yarn/global/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/clutch/.config/yarn/global/node_modules/@ionic/app-scripts/dist/core/bundle-components.js:6:16)
```

**Comment by CoreyCole** [comment]
Same, but I got
```
ionic-app-scripts build --prod
```
```
[06:43:49]  ionic-app-scripts 3.1.0
[06:43:49]  build prod started ...
[06:43:49]  clean started ...
[06:43:49]  clean finished in 5 ms
[06:43:49]  copy started ...
[06:43:49]  deeplinks started ...
[06:43:49]  deeplinks finished in 137 ms
[06:43:49]  ngc started ...
[06:43:50]  ionic-app-script task: "build"
[06:43:50]  Error: Cannot find module '@angular/compiler-cli/ngtools2'
Error: Cannot find module '@angular/compiler-cli/ngtools2'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /Users/clutch/.config/yarn/global/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:206:90
    at <anonymous>
```

I'm on versions
```
    angular stuff @5.0.0, 
    "@ionic-native/core": "4.3.1",
    "@ionic-native/splash-screen": "4.3.1",
    "@ionic-native/status-bar": "4.3.1",
    "@ionic/storage": "2.1.3",
    "rxjs": "5.5.2",
    "ionic-angular": "3.9.2",
    "@ionic/app-scripts": "3.1.0",
```

**Comment by mhartington** [comment]
The original stacktrace looks like it would be from app-scripts side. If you have a package-lock file, it could be caching the version. If you could, try to delete node_modules and the lock file then reinstall

**Comment by bogomips** [comment]
I posted a possible solution (it worked from me) here:
#13356

**Comment by mhartington** [comment]
Closing and moving over to #13356

**Comment by morrisonbrett** [comment]
I deleted my node_modules and package-lock.json and the original stack trace is still happening. Looking in #13356, I don't see a solution there as of now.

**Comment by morrisonbrett** [comment]
Related: #13372
