### ISSUE TITLE
ionic cordova build android --release --prod,this command to build app have a lots bug

### ISSUE THREAD

**Issue by zengyufang** [ionic-team/ionic#13372]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```
![image](https://user-images.githubusercontent.com/23447639/32590562-ff8e8330-c555-11e7-9599-6a9ccc6fe7a5.png)

**Other information:**

I can't get the device information with the app I packaged with the release command，but debugger command is geted the device information,I don't know Why is that???and other bug of slides on android app used release command

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):
```
insert the output from ionic info here
```
![image](https://user-images.githubusercontent.com/23447639/32590449-665dcb12-c555-11e7-8e6e-0ccbaa40a214.png)

**Comment by Sampath-Lokuge** [comment]
Do you need to release this app to store or just for debugging purpose?

**Comment by zengyufang** [comment]
yes,it's need to release to store

**Comment by Sampath-Lokuge** [comment]
You can run `ionic doctor check` and see the latest updates which you need to do and errors on your project.

**Comment by zengyufang** [comment]
hi， I don't know this relson,but I used command (ionic cordova build android --release) to build android app is ok. cound you tell me is why?

**Comment by zengyufang** [comment]
The command I used before was ionic cordova build android --release --prod

**Comment by Sampath-Lokuge** [comment]
If you use `ionic doctor check` then it'll show any errors in your app. Run it and see that. This `CLI` is not for releasing the app. Jut for checking errors and etc.

**Comment by zengyufang** [comment]
I'm sorry ,I didn't express myself clearly before.I used "ionic doctor check" to check errors.but before I'm used "ionic cordova build android --release --prod" build app can't get the device info, used"ionic cordova build android --release" build app can get the device info

**Comment by Sampath-Lokuge** [comment]
Why can't you test this in debug mode first on your device?

`ionic cordova run android --prod --device`

**Comment by gregor-srdic** [comment]
I am also having a problem building with --prod flag after updating to 3.9.2
here is the log:
> ionic-app-scripts build --prod

[17:30:34]  ionic-app-scripts 3.1.0
[17:30:34]  build prod started ...
[17:30:34]  clean started ...
[17:30:34]  clean finished in 8 ms
[17:30:34]  copy started ...
[17:30:34]  deeplinks started ...
[17:30:34]  deeplinks finished in 159 ms
[17:30:34]  ngc started ...
[17:30:45]  ngc finished in 10.81 s
[17:30:45]  preprocess started ...
[17:30:45]  preprocess finished in 2 ms
[17:30:45]  webpack started ...
[17:30:45]  copy finished in 11.56 s
[17:31:55]  ionic-app-script task: "build"
[17:31:55]  Error: ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js Module build failed: TypeError: Cannot
            read property 'type' of undefined at Object.getEffectiveTypeAnnotationNode
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:9341:17) at
            assignContextualParameterTypes
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41652:25) at
            checkFunctionExpressionOrObjectLiteralMethod
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41948:29) at
            checkExpressionWorker (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42959:28)
            at checkExpression (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42898:42) at
            checkExpressionCached (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42779:38)
            at checkReturnStatement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:45418:54)
            at checkSourceElement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:46763:28)
            at Object.forEach (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:1506:30) at
            checkBlock (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:44563:16) @
            ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76 @
            ./node_modules/rxjs/add/observable/bindNodeCallback.js @ ./node_modules/rxjs/Rx.js @
            ./src/providers/data-manager.ts @ ./src/app/app.module.ngfactory.js @
            ./src/app/main.ts,./node_modules/rxjs/observable/BoundCallbackObservable.js Module build failed: TypeError:
            Cannot read property 'type' of undefined at Object.getEffectiveTypeAnnotationNode
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:9341:17) at
            assignContextualParameterTypes
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41652:25) at
            checkFunctionExpressionOrObjectLiteralMethod
            (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41948:29) at
            checkExpressionWorker (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42959:28)
            at checkExpression (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42898:42) at
            checkExpressionCached (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42779:38)
            at checkReturnStatement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:45418:54)
            at checkSourceElement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:46763:28)
            at Object.forEach (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:1506:30) at
            checkBlock (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:44563:16) @
            ./node_modules/rxjs/observable/bindCallback.js 2:32-68 @ ./node_modules/rxjs/add/observable/bindCallback.js
            @ ./node_modules/rxjs/Rx.js @ ./src/providers/data-manager.ts @ ./src/app/app.module.ngfactory.js @
            ./src/app/main.ts
Error: ./node_modules/rxjs/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindNodeCallback.js 2:36-76
 @ ./node_modules/rxjs/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./src/providers/data-manager.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts,./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (C:\Nomnio\Gregor\360popusti\app\node_modules\typescript\lib\typescript.js:44563:16)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./src/providers/data-manager.ts
 @ ./src/app/app.module.ngfactory.js
 @ ./src/app/main.ts
    at BuildError.Error (native)
    at new BuildError (C:\Nomnio\Gregor\360popusti\app\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\Nomnio\Gregor\360popusti\app\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (C:\Nomnio\Gregor\360popusti\app\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\Nomnio\Gregor\360popusti\app\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\Nomnio\Gregor\360popusti\app\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\Nomnio\Gregor\360popusti\app\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\Nomnio\Gregor\360popusti\app\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\Nomnio\Gregor\360popusti\app\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Nomnio\Gregor\360popusti\app\node_modules\tapable\lib\Tapable.js:222:13)

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

Does anyone have a sample app demonstrating this issue that they can share via GitHub?

I am experiencing none of these issues, including on an app I just upgraded an app to Angular 5.0.1, Ionic Framework 3.9.2.

Also, I am going to move this to the Ionic CLI repo, but a sample application would still be very very helpful.

Thank you for using Ionic
