### ISSUE TITLE
Module not found: Error: Can't resolve './app.module.ngfactory' due to (ngModelChange)

### ISSUE THREAD

**Issue by matoos32** [ionic-team/ionic#13453]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**Current behavior:**

When using an `<ion-input>` with `(ngModelChange)` and Angular 5.0.x, `ionic build --prod` and `ionic build --aot` are failing with:

```
Error: ./src/app/main.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\issue-ionic-3-angular-5-ng-model-change\src\app'
resolve './app.module.ngfactory' in 'C:\issue-ionic-3-angular-5-ng-model-change\src\app'
  using description file: C:\issue-ionic-3-angular-5-ng-model-change\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\issue-ionic-3-angular-5-ng-model-change\package.json (relative path: ./src/app)
    using description file: C:\issue-ionic-3-angular-5-ng-model-change\package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.json doesn't exist
      as directory
        C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory doesn't exist
[C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory]
[C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.ts]
[C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.js]
[C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory.json]
[C:\issue-ionic-3-angular-5-ng-model-change\src\app\app.module.ngfactory]
 @ ./src/app/main.ts 2:0-60
    at BuildError.Error (native)
    at new BuildError (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\webpack\lib\Compiler.js:368:12)
    at next (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\issue-ionic-3-angular-5-ng-model-change\node_modules\tapable\lib\Tapable.js:222:13)
```

**Expected behavior:**
Successful compilation

**Steps to reproduce:**
1. `ionic start test blank`
2. Edit `home.html` to add an `<ion-input>` containing an `(ngModelChange)`
3. Save and close.
4. `ionic build --prod` (*Module not found error*)
5. Remove `(ngModelChange)` from `home.html` then save.
6. `ionic build --prod` (*Error is gone*)

**Related code:**

I created a sample repo to demonstrate: https://github.com/matoos32/issue-ionic-3-angular-5-ng-model-change

**Other information:**

This is a follow-on to https://github.com/ionic-team/ionic/issues/13356

***ionic info***:

```
cli packages: (<somewhere>\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

local packages:

    @ionic/app-scripts : 3.1.2
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v6.11.2
    npm  : 3.10.10
    OS   : Windows 10

Misc:

    backend : legacy
```

**Comment by matoos32** [comment]
False alarm. There is no bug and I will close the issue. I inadvertently escaped the `$` character in `(ngModelChange)="foo = event2Num(\$event)"` while working around issue #13388 (see sample repo). This caused the problem I observed. Everything compiles properly when the character is not escaped.
