### ISSUE TITLE
[ionic 3.9.2] the correct typescript code breaks the ngc compiler

### ISSUE THREAD

**Issue by anatoly-spb** [ionic-team/ionic#13480]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

when I create android release with `ionic cordova build android --prod --release` the ngc compiler breaks with:

```
[10:26:31]  build prod started ... 
[10:26:31]  clean started ... 
[10:26:31]  clean finished in 2 ms 
[10:26:31]  copy started ... 
[10:26:31]  deeplinks started ... 
[10:26:32]  deeplinks finished in 547 ms 
[10:26:32]  ngc started ... 
[GTypeError: Cannot read property 'kind' of undefined
    at nodeCanBeDecorated (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:7805:35)
    at nodeIsDecorated (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:7825:16)
    at Object.nodeOrChildIsDecorated (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:7829:16)
    at isDecoratedClassElement (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51668:23)
    at isInstanceDecoratedClassElement (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51659:20)
    at Object.filter (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:1652:25)
    at getDecoratedClassElements (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51641:23)
    at generateClassElementDecorationExpressions (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51815:27)
    at addClassElementDecorationStatements (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51804:44)
    at visitClassDeclaration (H:\src\trunk\src\ionic\rms\node_modules\typescript\lib\typescript.js:51131:13)
```

**Expected behavior:**

success build

**Steps to reproduce:**

`ionic cordova build android --prod --release`

**Related code:**

The following code uses https://github.com/pleerock/class-transformer library breaks the ngc compiler:
```
export class Notification {
@Expose({ name: "notId" }) 
id: number;
@Expose({ name: "title" })
title: string;
@Expose({ name: "message" })
message: string;
foreground: boolean;
coldstart: boolean;
@Type(() => NotificationInfo)
info: NotificationInfo;
readed: boolean = false;
@Type(() => Date)
created: Date = new Date();
}
```

**Other information:**

https://forum.ionicframework.com/t/ionic-3-9-2-the-correct-typescript-code-breaks-the-ngc-compiler/112980

https://github.com/angular/angular/issues/20216

https://github.com/Microsoft/TypeScript/issues/17384

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (h:\npm\node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v6.9.2
    npm               : 3.10.10
    OS                : Windows 7

Environment Variables:

    ANDROID_HOME : h:\mobile\android\sdk

Misc:

    backend : pro
```

**project.json:**

```
{
...
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "5.0.1",
    "@angular/compiler": "5.0.1",
    "@angular/compiler-cli": "5.0.1",
    "@angular/core": "5.0.1",
    "@angular/forms": "5.0.1",
    "@angular/http": "5.0.1",
    "@angular/platform-browser": "5.0.1",
    "@angular/platform-browser-dynamic": "5.0.1",
    "@ionic-native/core": "4.4.0",
    "@ionic-native/deeplinks": "4.4.0",
    "@ionic-native/file-transfer": "4.4.0",
    "@ionic-native/http": "4.4.0",
    "@ionic-native/push": "4.4.0",
    "@ionic-native/splash-screen": "4.4.0",
    "@ionic-native/status-bar": "4.4.0",
    "@ionic/storage": "2.1.3",
    "class-transformer": "^0.1.8",
    "cordova": "^7.1.0",
    "cordova-plugin-advanced-http": "^1.8.1",
    "cordova-plugin-device": "^1.1.7",
    "cordova-plugin-file": "^4.3.3",
    "cordova-plugin-file-transfer": "^1.7.0",
    "cordova-plugin-ionic-webview": "^1.1.16",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.1.2",
    "ionic-angular": "3.9.2",
    "ionic-plugin-deeplinks": "^1.0.15",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "^3.0.0",
    "phonegap-plugin-push": "^2.1.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18",
    "cordova-android": "~6.3.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.2",
    "typescript": "2.4.2"
  },
...
    },
    "platforms": [
      "android"
    ]
  }
}
```

`tsconfig.json`:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "src/**/*.spec.ts",
    "src/**/__tests__/*.ts"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

**Comment by anatoly-spb** [comment]
Actually this is a bug of typescript: https://github.com/Microsoft/TypeScript/issues/17384 It seems to me this bug has been fixed in typescript 2.6.1: https://github.com/shlomiassaf/TypeScript/commit/7017fa2a0a8137279230f04b59a6ec89f6928331

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

I am going to close this as it is not an issue with the Ionic Framework, but as you point out an issue with TypeScript.

Thank you for using Ionic

**Comment by niveo** [comment]
https://github.com/typestack/class-transformer/issues/108

@rmrevin

```
export function serializeType<T>(object: T) {
  return function () { return object; }
}

export class CatalogItem {

  id: string;

  @Type(serializeType(CatalogCategory))
  category?: CatalogCategory = null;

  @Type(serializeType(PackingVariant))
  packing: PackingVariant;

  price: string = null;

}
```

**Comment by niveo** [comment]
https://github.com/angular/angular-cli/issues/8434

@gmavritsakis

I had the same issue with:
Angular CLI 1.6.1
Typescript 2.4.2
Angular 5.0.2

Found a solution by changing typescript.js for now.
Replace all the function
function nodeCanBeDecorated(node)
with the following code

```
function nodeCanBeDecorated(node) {
       switch (node.kind) {
           case 229 /* ClassDeclaration */:
               // classes are valid targets
               return true;
           case 149 /* PropertyDeclaration */:
               // property declarations are valid if their parent is a class declaration.
   			// return node.parent.kind === 229 /* ClassDeclaration */;
   			return (node.parent && node.parent.kind === 229) || (node.original && node.original.parent && node.original.parent.kind === 229);
           case 153 /* GetAccessor */:
           case 154 /* SetAccessor */:
           case 151 /* MethodDeclaration */:
               // if this method has a body and its parent is a class declaration, this is a valid target.
               return node.body !== undefined &&
   				// && node.parent.kind === 229 /* ClassDeclaration */;
   				(node.parent && node.parent.kind === 229) || (node.original && node.original.parent && node.original.parent.kind === 229);
           case 146 /* Parameter */:
               // if the parameter's parent has a body and its grandparent is a class declaration, this is a valid target;
               // return node.parent.body !== undefined
               //     && (node.parent.kind === 152 /* Constructor */
               //         || node.parent.kind === 151 /* MethodDeclaration */
               //         || node.parent.kind === 154 /* SetAccessor */)
   			//     && node.parent.parent.kind === 229 /* ClassDeclaration */;
   			
   			var parent = node.parent || (node.original && node.original.parent);
   			return parent && parent.body !== undefined &&
                     (parent.kind === 152
                        || parent.kind === 151
                        || parent.kind === 154) && parent.parent.kind === 229;
       }
       return false;
   }
```
Which comes from here, if you compile typescript:
shlomiassaf/TypeScript@7017fa2

**Comment by anatoly-spb** [comment]
@niveo yes, I am using the patched typescript also.

**Comment by daixtrose** [comment]
@kensodemann I cannot believe this issue gets closed, since **everybody** (!) who follows the ionic docs to the letter will run into this problem. Since ionic is built on top of other libraries, I would at least expect a configuration management that picks working versions of these libraries, expecially when it is Angular, Typescript, Cordova, etc.

Why do you think that Ionic is not responsible? A simple 
```
ionic start showbug blank
ionic generate component gaga
```
together with adding `GagaComponent` to the declarations of `app.modules.ts` already reveals this issue, but **only if** building a **release** for Android:

- `ionic serve` works
- `ionic cordova build android` works as expected
- `ionic cordova build android --release --prod` yields
   ```
   typescript error
		Type GagaComponent in PATH_TO_APP/showbug/src/components/gaga/gaga.ts is part
		of the declarations of 2 modules: AppModule in
		PATH_TO_APP/showbug/src/app/app.module.ts and ComponentsModule in
		PATH_TO_APP/showbug/src/components/components.module.ts! Please consider moving
		GagaComponent in PATH_TO_APP/showbug/src/components/gaga/gaga.ts to a higher
		module that imports AppModule in PATH_TO_APP/showbug/src/app/app.module.ts and
		ComponentsModule in PATH_TO_APP/showbug/src/components/components.module.ts.
		You can also create a new NgModule that exports and includes GagaComponent in
		PATH_TO_APP/showbug/src/components/gaga/gaga.ts then import that NgModule in
		AppModule in PATH_TO_APP/showbug/src/app/app.module.ts and ComponentsModule in
		PATH_TO_APP/showbug/src/components/components.module.ts.
   ```

Is it so hard to avoid weird hacks like [this one](https://github.com/angular/angular/issues/20216)? If the ionic team cannot provide clear advice on how to get even a basic app work properly with greatest and latest version of node/angular/cordova what do you expect your customers to do? Use React.js? 

So why don't you provide a clear statement **on your main page** on how to avoid this issue or even better: adopt your own setup scripts to fix this such that no one runs into it?

**Comment by codenthusiast** [comment]
@niveo this solves it for me. Thanks
