### ISSUE TITLE
undefined when calling a method of my Storage provider

### ISSUE THREAD

**Issue by Cypaubr** [ionic-team/ionic#13519]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I have a page called 'Settings' where the user can disconnect by clicking a button. When he clicks on the button I call the clearStorage() method of my Storage provider but an error is thrown:

```javascript
TypeError: Cannot read property 'clearStorage' of undefined
    at Object.webpackJsonp.210.SettingsPage.logout [as handler] (http://localhost:8100/build/main.js:353:29)
    at AlertCmp.btnClick (http://localhost:8100/build/vendor.js:49147:24)
    at Object.eval [as handleEvent] (ng:///IonicModule/AlertCmp.ngfactory.js:201:23)
    at handleEvent (http://localhost:8100/build/vendor.js:12380:138)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:13850:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:13438:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:8972:21)
    at http://localhost:8100/build/vendor.js:9583:20
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:39816:53)
    at HTMLButtonElement.wrapped (http://localhost:8100/build/vendor.js:125198:21)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15040)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4238:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14961)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10214)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16174)
    at p (http://localhost:8100/build/polyfills.js:2:26993)
    at HTMLButtonElement.v (http://localhost:8100/build/polyfills.js:2:27238)
```

**Expected behavior:**

When the users clicks on the disconnect button, the storage is cleared and the user is redirected on the connect page.

**Related code:**

Here is my page code:
```typescript
import { Component } from '@angular/core';
import {AlertController, IonicPage, NavController, NavParams} from 'ionic-angular';
import {CityfidStorageProvider} from "../../providers/cityfid-storage/cityfid-storage";
import {ConnectPage} from "../connect/connect";

@IonicPage()
@Component({
  selector: 'page-settings',
  templateUrl: 'settings.html',
})
export class SettingsPage {

  constructor(public navCtrl: NavController, public navParams: NavParams,
              private alertCtrl: AlertController,
              private cityfidStorage: CityfidStorageProvider) {
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad SettingsPage');
  }

  logoutAlert(){
    let logoutAlert = this.alertCtrl.create({
      title: 'Deconnexion',
      message: 'Êtes-vous sûr de vouloir vous deconnecter ?',
      buttons: [
        {
          text: 'Oui',
          handler: this.logout
        },{
          text: 'Non'
        }
      ]
    });
    logoutAlert.present();
  }

  logout(){
    this.cityfidStorage.clearStorage().then(res => {
      this.navCtrl.push(ConnectPage);
    })
  }
}

```
And here is my provider code:
```typescript
import { Injectable } from '@angular/core';
import { Storage } from "@ionic/storage";
import 'rxjs/add/operator/map';

@Injectable()
export class CityfidStorageProvider{

  constructor(private storage:Storage) {
    console.log('Hello CityfidStorageProvider Provider');
  }

  /**
   * This method sets if the user is connected
   * @param value Boolean
   * @return Boolean
   */
  setConnected(value){
    if (typeof(value) === 'boolean' ){
      this.storage.set('connected',value);
      console.log('Set connected: ' + value);
      return true;
    } else {
      throw new Error('Value for setConnected() must be type of Boolean');
    }
  }

  /**
   * Returns if the user is connected
   */
  getConnected(){
    return new Promise(val => {
      this.storage.get('connected').then(res => {
        val(res);
      });
    });
  }

  /**
   * This method saves the user object
   * @param value
   */
  setUser(value){
    return new Promise(val => {
      this.storage.set('user',value).then(res => {
        val(res);
      });
      console.log('Set user: ' + value);
    });
  }

  /**
   * This method returns the user object
   * @return {Promise<any>}
   */
  getUser(){
    return new Promise(val => {
      this.storage.get('user').then(res => {
        val(res);
      });
    });
  }

  /**
   * This method clears the user info.
   * @return {Promise<any>}
   */
  clearStorage(){
    return new Promise(val => {
      this.storage.clear();
      console.log('Storage cleared');
    })
  }
}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\cypou\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    Node              : v8.6.0
    npm               : 5.5.1 
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\cypou\AppData\Local\Android\Sdk

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Perhaps you don't have something set up properly as a provider? Somehow, your service is not being injected, but that is not handled by the Ionic Framework. Your app should be using Angular for that.

It may also be helpful to post a link to your apps repo (or a link to a sample application exhibiting the same behavior if you cannot allow others to access your app's repo).

Thanks for using Ionic!
