### ISSUE TITLE
[Ionic + Cordova + Gradle + Android + Jenkins on Windows] Build failed with the pipe is being closed

### ISSUE THREAD

**Issue by anatoly-spb** [ionic-team/ionic#13594]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[ x] bug report
[ ] feature request

Please do not submit support requests or "How to" questions here. Instead, please use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**

I try to build ionic project under Jenkings on Windows and from time to time my build failed with:
```
* What went wrong:
Execution failed for task ':mergeArmv7ReleaseResources'.
> Error: java.util.concurrent.ExecutionException: java.io.IOException: The pipe is being closed

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

```

**Expected behavior:**

success build

**Steps to reproduce:**

 I created the jenkins item with free configuration and run the following windows batch and run several times:

```
set ANDROID_HOME=C:\android\sdk
set NODEJS_HOME=C:\nodejs
set NPM_HOME=%NODEJS_HOME%\npmroot
set CI=true
set PATH=%SystemRoot%\system32;%SystemRoot%
set PATH=%JAVA_HOME%\bin;%PATH%
set PATH=%NODEJS_HOME%;%PATH%
set PATH=%NPM_HOME%;%PATH%
set PATH=%ANDROID_HOME%\platform-tools;%ANDROID_HOME%\tools;%ANDROID_HOME%\tools\bin;%PATH%
set BUILD_DIR=%WORKSPACE%\..\builds\%BUILD_ID%\build
mkdir %BUILD_DIR%
cd %BUILD_DIR%
call ionic start latest sidemenu
cd latest
call npm install
call ionic cordova plugin add cordova-plugin-file-transfer
call ionic cordova plugin add cordova-sqlite-storage
call ionic cordova plugin add cordova-plugin-advanced-http
call ionic cordova plugin add ionic-plugin-deeplinks --variable URL_SCHEME=myapp --variable DEEPLINK_SCHEME=https --variable DEEPLINK_HOST=example.com --variable ANDROID_PATH_PREFIX=/
call ionic cordova plugin add cordova-plugin-pin-dialog
call ionic cordova plugin add cordova-plugin-crosswalk-webview
call ionic cordova platform add android
rem also I tried to set android.aaptOptions.useNewCruncher=true in build-extras.gradle but it does not help
rem echo android.aaptOptions.useNewCruncher=true >platforms\android\build-extras.gradle
rem also I tried to set cdvBuildToolsVersion with different build-tools, it does not help
rem echo cdvBuildToolsVersion=25 >platforms\android\gradle.properties 
call ionic cordova build android --prod --release -- --gradleArg=--info
```

**Related code:**

**Other information:**

https://issues.apache.org/jira/browse/CB-13638

**Stack trace:**
```
* What went wrong:
Execution failed for task ':mergeArmv7ReleaseResources'.
> Error: java.util.concurrent.ExecutionException: java.io.IOException: The pipe is being closed

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 4.296 secs
Stopped 0 worker daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':mergeArmv7ReleaseResources'.] from daemon DaemonInfo{pid=8240, address=[cef53d36-8cae-4993-8efb-7f9a4d217241 port:52098, addresses:[/127.0.0.1, /0:0:0:0:0:0:0:1]], state=Idle, lastBusy=1512517318653, context=DefaultDaemonContext[uid=2d744783-e87e-4dae-b50a-728ff0821338,javaHome=C:\Program Files\Java\jdk1.8.0_151,daemonRegistryDir=C:\Windows\System32\config\systemprofile\.gradle\daemon,pid=8240,idleTimeout=10800000,daemonOpts=-Xmx2048m,-Dfile.encoding=windows-1251,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
Error: cmd: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Thread(png-cruncher_6): The pipe is being closed
java.io.IOException: The pipe is being closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
	at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
	at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_17): The pipe is being closed
java.io.IOException: The pipe is being closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
	at com.android.builder.png.AaptProcess.shutdown(AaptProcess.java:143)
	at com.android.builder.png.QueuedCruncher$1.destruction(QueuedCruncher.java:151)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:245)
	at java.lang.Thread.run(Thread.java:748)
Thread(png-cruncher_2): The pipe is being closed
```

**Environment:**
```
PATH=C:\android\sdk\platform-tools;C:\android\sdk\tools;C:\android\sdk\tools\bin;C:\nodejs\npmroot;C:\nodejs;C:\Program Files\Java\jdk1.8.0_151\bin;C:\Windows\system32;C:\Windows
windows 8.1 
jenkins: 2.73.3
java version "1.8.0_151"
node v8.9.1
npm 5.5.1
cordova 7.1.0
```
**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\nodejs\npmroot\node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0
 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.1
    npm               : 5.5.1 
    OS                : Windows 8.1

Environment Variables:

    ANDROID_HOME : C:\android\sdk
```

**Comment by mhartington** [comment]
Hi there! I'm going to close this issue because this is not an issue with the framework, but rather a build issue with android/gradle. Please use the cordova issue instead. Thanks!

**Comment by anatoly-spb** [comment]
The problem was with Jenkins/Gradle Daemon. The following command disable Gradle Daemon:
```
ionic cordova build android --prod --release -- -- --gradleArg=--no-daemon
```
