### ISSUE TITLE
Cannot find module "ionic-native"

### ISSUE THREAD

**Issue by AlGantori** [ionic-team/ionic#13648]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[X] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

More about the Runtime Error
```
Error: Cannot find module "ionic-native"
    at Object.306 (http://localhost:8100/build/main.js:3578:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.253 (http://localhost:8100/build/main.js:3286:73)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.229 (http://localhost:8100/build/main.js:3266:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1
Ionic Framework: ^3.9.2
Ionic App Scripts: 3.1.5
Angular Core: 5.0.0
Angular Compiler CLI: 5.0.0
Node: 7.2.0
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
```

5 months later I have now upgraded from 3.4.0 to latest 3.19.0 but facing this Runtime Error
"Cannot find module "ionic-native""

Among other push ups to get the project running as it was I have done thing like the following...

1. 1231 ionic info
2. 1232 npm install -g ionic@latest
3. 1234 ionic serve --nobrowser
4. 1235 npm install ionic-angular@latest --save
5. 1236 npm install @ionic/app-scripts@latest --save-dev
6. 1237 ionic info
7. 1238 npm install --save-dev @ionic/cli-plugin-cordova@latest
8. 1239 npm install --save-dev @ionic/cli-plugin-ionic-angular@latest
9. 1240 npm install -g ionic@latest
10. 1241 npm outdated
11. 1242 npm install
12. 1244 ionic info
13. 1245 ionic serve --nobrowser
14. 1246 npm uninstall -D @ionic/cli-plugin-cordova
15. 1247 npm uninstall -D @ionic/cli-plugin-ionic-angular
16. 1248 ionic serve --no-open
17. 1249 npm install
18. 1250 ionic serve --no-open
19. 1251 npm update
20. 1252 ionic serve --no-open
21. 1253 npm install
22. 1256 ionic serve --no-open
23. 1264 ionic info
24. added vendor.js to index.html

the build folder seems to contain the files needed?
![index 44](https://user-images.githubusercontent.com/11699920/33959338-0770fb6c-dffc-11e7-94ae-b1749fc8eb92.jpg)

I believe all my imports are using the new spelling for "@ionic-native...."
![index 41](https://user-images.githubusercontent.com/11699920/33956700-3a2dc240-dff4-11e7-9f28-b9f4358739f7.jpg)

ionic info...
![index 42](https://user-images.githubusercontent.com/11699920/33956833-a2cc75c6-dff4-11e7-9fdc-904ea1c98461.jpg)

Here are my updates to packages.json
![index 43](https://user-images.githubusercontent.com/11699920/33956942-0a30309a-dff5-11e7-9830-f94744ecc622.jpg)

All 5 related ionic-native node_modules seems to have been already re-installed  (during npm install)
do I have to issue explicit installs for each one of them?

![index 40](https://user-images.githubusercontent.com/11699920/33957068-67d482dc-dff5-11e7-9c74-e3e20b907c45.jpg)

I believe I rechecked all that applies from this closed issue 
https://github.com/ionic-team/ionic/issues/11091

Don't know what to do at the moment.

**Comment by AlGantori** [comment]
Moved to here according to suggestions
https://github.com/ionic-team/ionic-native/issues/2197
