### ISSUE TITLE
Typescript Error Class 'BaseInput<T>' incorrectly implements interface 'CommonInput<T>'.

### ISSUE THREAD

**Issue by luffySAMA** [ionic-team/ionic#13644]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
My ionic app build success on windows while failed on mac.

**Steps to reproduce:**
If I run `ionic serve`, the application work correctly.
However if I run `ionic cordova build ios --prod`, it failed into this error

```
Running app-scripts build: --prod --platform ios --target cordova
[19:47:02]  build prod started ...
[19:47:02]  clean started ...
[19:47:02]  clean finished in 2 ms
[19:47:02]  copy started ...
[19:47:02]  copy finished in 109 ms
[19:47:02]  deeplinks started ...
[19:47:02]  deeplinks finished in 13 ms
[19:47:02]  ngc started ...
[19:47:18]  typescript: node_modules/ionic-angular/util/base-input.d.ts, line: 23
            Class 'BaseInput<T>' incorrectly implements interface 'CommonInput<T>'. Types of property 'ionFocus' are
            incompatible. Type 'EventEmitter<BaseInput<T>>' is not assignable to type 'EventEmitter<CommonInput<T>>'.
            Types of property 'observers' are incompatible. Type 'Observer<BaseInput<T>>[]' is not assignable to type
            'Observer<CommonInput<T>>[]'. Type 'Observer<BaseInput<T>>' is not assignable to type
            'Observer<CommonInput<T>>'. Type 'CommonInput<T>' is not assignable to type 'BaseInput<T>'.

      L23:  export declare class BaseInput<T> extends Ion implements CommonInput<T> {
      L24:      private _defaultValue;

Error: The Angular AoT build failed. See the issues above
    at /Users/caihuapeng/work/ionicApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:232:55
    at step (/Users/caihuapeng/work/ionicApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:32:23)
    at Object.next (/Users/caihuapeng/work/ionicApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:13:53)
    at fulfilled (/Users/caihuapeng/work/ionicApp/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:4:58)
    at <anonymous>
```

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (/Users/caihuapeng/work/ionicApp/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.2.3 ios 4.3.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    Node       : v8.9.3
    npm        : 5.5.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

What version of TypeScript are you using? I suggest `2.4.2`, which is what our starters currently use.

Thank you for using Ionic

**Comment by luffySAMA** [comment]
@kensodemann thank you very much!
previously my typescript version is `2.6.1`,now I have changed it to version `2.4.2`, and it works.

perfect 🎉

I will close this issue

**Comment by mahnuh** [comment]
I am getting the same error although I am using typescript 2.4.2. Any Ideas?

**Comment by shinriyo** [comment]
I added below `tsconfig.json`. it happened.

```
+    "removeComments": true,
+    "strict": true,
+    "noUnusedLocals": true,
+    "noUnusedParameters": true,
+    "noImplicitReturns": true,
+    "noFallthroughCasesInSwitch": true,
+    "experimentalDecorators": true,
```

so, I guess you remove one of them, you'll remove error.

**Comment by shinriyo** [comment]
Ionic4 may fix it...

https://github.com/ionic-team/ionic/issues/10646
