### ISSUE TITLE
[IONIC3] - COMPILE ANDROID - ionic cordova build android, fail

### ISSUE THREAD

**Issue by oTTa** [ionic-team/ionic#13749]
I execute this command in W10 but I can't compile.

**ionic cordova build android**
Running app-scripts build: --platform android --target cordova
[23:17:32]  build dev started ...
[23:17:32]  clean started ...
[23:17:32]  clean finished in 16 ms
[23:17:32]  copy started ...
[23:17:32]  deeplinks started ...
[23:17:32]  deeplinks finished in 203 ms
[23:17:32]  transpile started ...
[23:17:38]  transpile finished in 5.79 s
[23:17:38]  preprocess started ...
[23:17:38]  preprocess finished in less than 1 ms
[23:17:38]  webpack started ...
[23:17:38]  copy finished in 6.26 s
[23:17:50]  webpack finished in 12.42 s
[23:17:50]  sass started ...
Witout `from` option PostCSS could generate wrong source map or do not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning
[23:17:54]  sass finished in 3.60 s
[23:17:54]  postprocess started ...
[23:17:54]  postprocess finished in 16 ms
[23:17:54]  lint started ...
[23:17:54]  build dev finished in 22.42 s
> cordova build android
Preparing Firebase on Android
cordova-android-play-services-gradle-release  PLAY_SERVICES_VERSION:  11.+
cordova-android-support-gradle-release  ANDROID_SUPPORT_VERSION:  26.+
cordova-android-play-services-gradle-release : WROTE  C:\Users\pololo\mobile\myapp\platforms\android\build.gradle  >  11.+
cordova-android-support-gradle-release : WROTE  C:\Users\pololo\mobile\myapp\platforms\android\build.gradle  >  26.+
ANDROID_HOME=C:\Users\pololo\android-tools
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_152
Subproject Path: CordovaLib
Exception in thread "main"
java.lang.NullPointerException
        at org.gradle.wrapper.PathAssembler.getDistName(PathAssembler.java:84)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:40)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Error: cmd: Command failed with exit code 1 Error output:
Exception in thread "main" java.lang.NullPointerException
        at org.gradle.wrapper.PathAssembler.getDistName(PathAssembler.java:84)
        at org.gradle.wrapper.PathAssembler.getDistribution(PathAssembler.java:40)
        at org.gradle.wrapper.Install.createDist(Install.java:44)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

---------------------------------------------------------------------------------------------------------
**cordova platform ls**

Installed platforms:
  android 6.3.0
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~5.0.0
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

**Comment by Nitingadhiya** [comment]
Please fix your play service library version.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
