### ISSUE TITLE
Ionic app doesn't run or build

### ISSUE THREAD

**Issue by otrepdila** [ionic-team/ionic#13893]
I'm trying to test my ionic application as a native app on android.
I've tried running the command below as per the ionic documentation
ionic cordova run android

I've also connected up my phone and enabled USB debugging. I get a bunch of output but the app doesn't get installed onto my device.

I've also tried building the application for android but same error!!

```
cordova run android
ANDROID_HOME=/Users/macbookpro/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home
(node:58469) UnhandledPromiseRejectionWarning: Error: spawn EACCES
at _errnoException (util.js:1003:13)
at ChildProcess.spawn (internal/child_process.js:340:11)
at Object.exports.spawn (child_process.js:499:9)
at Object.exports.spawn (/Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:134:31)
at GradleBuilder.runGradleWrapper (/Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/lib/builders/GradleBuilder.js:78:27)
at /Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/lib/builders/GradleBuilder.js:177:21
at _fulfilled (/Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/node_modules/q/q.js:854:54)
at self.promiseDispatch.done (/Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/node_modules/q/q.js:816:13)
at /Users/macbookpro/desktop/mobile/ionic/2018/vv/platforms/android/cordova/node_modules/q/q.js:570:49
(node:58469) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58469) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[OK] Your app has been deployed.
     Did you know you can live-reload changes from your app with --livereload?
```

I have remeved node, ionic and cordova and install them from the beginning and still did'nt work.

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
