### ISSUE TITLE
StaticInjectorError[OneSignal]

### ISSUE THREAD

**Issue by noor07** [ionic-team/ionic#13975]
hey team,
i got an error, 

Error: StaticInjectorError[OneSignal]: 
  StaticInjectorError[OneSignal]: 
    NullInjectorError: No provider for OneSignal!
    at _NullInjector.get (http://localhost:8100/build/vendor.js:1276:19)
    at resolveToken (http://localhost:8100/build/vendor.js:1564:24)
    at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16)
    at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20)
    at resolveToken (http://localhost:8100/build/vendor.js:1564:24)
    at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16)
    at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20)
    at resolveNgModuleDep (http://localhost:8100/build/vendor.js:10938:25)
    at NgModuleRef_.get (http://localhost:8100/build/vendor.js:12159:16)
    at resolveDep (http://localhost:8100/build/vendor.js:12655:45)

my ionic version

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. As this seems like more of a support question I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!

**Comment by noor07** [comment]
hey team,
i got an error,

Error: StaticInjectorError[OneSignal]:
StaticInjectorError[OneSignal]:
NullInjectorError: No provider for OneSignal!
at NullInjector.get (http://localhost:8100/build/vendor.js:1276:19)
at resolveToken (http://localhost:8100/build/vendor.js:1564:24)
at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16)
at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20)
at resolveToken (http://localhost:8100/build/vendor.js:1564:24)
at tryResolveToken (http://localhost:8100/build/vendor.js:1506:16)
at StaticInjector.get (http://localhost:8100/build/vendor.js:1377:20)
at resolveNgModuleDep (http://localhost:8100/build/vendor.js:10938:25)
at NgModuleRef.get (http://localhost:8100/build/vendor.js:12159:16)
at resolveDep (http://localhost:8100/build/vendor.js:12655:45)

my ionic version

Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.6
Angular Core: 5.0.3
Angular Compiler CLI: 5.0.3
Node: 8.9.4
OS Platform: Windows 10
Navigator Platform: Win32
