### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by vikceo** [ionic-team/ionic#13979]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
ionic 3.3.0

**I'm submitting a ...**  (check one with "x")
[ ] bug report

**Current behavior:**
run ionic serve and it shows
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at __extends (http://localhost:8100/build/vendor.js:55707:9)
    at http://localhost:8100/build/vendor.js:55804:5
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:55809:2)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.338 (http://localhost:8100/build/main.js:2025:79)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.333 (http://localhost:8100/build/main.js:2007:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
**Expected behavior:**
should run

**Steps to reproduce:**
ionic serve 

**Related code:**

not applicable

**Comment by kensodemann** [comment]
Hello! Thank you for opening an issue with us!

The Ionic Framework issues list is designated for the reporting of bugs with the Ionic Framework or for requesting new features. Since this does not occur in a newly created app, it seems like it is likely something in your code base or some library you are including which make this more of a support question so I am going to close this issue.

I urge that you ask this question on our [forum](https://forum.ionicframework.com) or on our [slack channel](https://ionicworldwide.herokuapp.com/).

You say you are using Ionic 3.3.0. The latest is 3.9.2. If it is an issue with Ionic itself and not your code or a library you are including, you will want to try upgrading to 3.9.2 first.

If you believe you have this tracked down to an Ionic issue, please supply a sample application via GitHub that demonstrates the issue you are having.

Thanks for using Ionic!
