### ISSUE TITLE
Error: Cannot find module 'braces'

### ISSUE THREAD

**Issue by piyushmanurkar** [ionic-team/ionic#14045]
Create new sample project.
run
**_ionic serve_**

Error: Cannot find module 'braces'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (path_to_project_folder\node_modules\micromatch\lib\utils.js:14:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**$ionic info**

cli packages: (C:\Users\Piyush_pc\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.9.4
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : pro

**Comment by brandyscarney** [comment]
This issue was moved to ionic-team/ionic-cli#2998
