### ISSUE TITLE
when I run ionic cordova build android, node_modules/@ionic/app-scripts will Be automatically delete

### ISSUE THREAD

**Issue by 253936563** [ionic-team/ionic#14221]
when I run ionic cordova build android or ionic cordova ios , node_modules/@ionic/app-scripts will Be automatically delete.But I npm install all package before.@ionic/app-scripts is exist.

**Comment by 253936563** [comment]
this is error info:
Error: Cannot find module '/Users/wjh/Desktop/code/ex/app/ex/node_modules/@ionic/app-scripts'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wjh/.npm-packages/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:9:16)
    at next (native)
    at /Users/wjh/.npm-packages/lib/node_modules/ionic/node_modules/tslib/tslib.js:107:75
    at Object.__awaiter (/Users/wjh/.npm-packages/lib/node_modules/ionic/node_modules/tslib/tslib.js:103:16)
    at Object.importAppScripts (/Users/wjh/.npm-packages/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/app-scripts.js:7:20)
    at /Users/wjh/.npm-packages/lib/node_modules/ionic/node_modules/@ionic/cli-utils/lib/ionic-angular/build.js:10:48
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ex@0.0.1 build:md: `ionic cordova build android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ex@0.0.1 build:md script.

**Comment by 253936563** [comment]
this is my ionic info:
cli packages: (/Users/wjh/.npm-packages/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

System:

    Node : v6.11.3
    npm  : 5.0.1
    OS   : macOS High Sierra

Misc:

    backend : pro
cordova version is 8.0.0

**Comment by 253936563** [comment]
"@ionic/app-scripts": "^3.1.8",

**Comment by 253936563** [comment]
@ionic/app-scripts: "^3.1.8",

**Comment by 253936563** [comment]
ionic/app-scripts version is 3.1.8
