### ISSUE TITLE
Error: Could not find entry point (bootstrap file) in --prod build after updating to Ionic@3.19.0

### ISSUE THREAD

**Issue by lubra123** [ionic-team/ionic#14243]
**Ionic version:**  
[ ] **2.x**
[ x ] **3.x**
[ ] **4.x**

**I'm submitting a ...**  
[ x ] bug report
[ ] feature request

**Current behavior:**

After Upgdrading from Ionic3.5.0 to Ionic3.19.0 
ionic cordova build android --prod 
stops with the following Error Message:

```
Error: Could not find entry point (bootstrap file) \src\app\main.ts
    at replaceBootstrap (\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:125:39)
    at Object.<anonymous> (\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:92:48)
    at step (\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>
```

**Expected behavior:**

Prod should build with aot compiler 
**Steps to reproduce:**

**Related code:**

After some investigations on the Code (aot-compiler.js) I found out that "mainFile" is set to undefined, but I can't figure out why. "mailFilePath" is set to "C:\Users\User\WebstormProjects\App\src\app\main.js" My assumption is that "context.fileCache.get(mailFilePath)" can't find the File "main.js" which is also not in www/build folder. The --prod build was no problem before I upgraded Ionic to 3.19.0 and some of my plugin-versions (see package.json  and package_old.json below).

aot-compiler.js:
(line 88 to 97)
```
case 4:
                    errorCheckProgram(context, tsConfig, compilerHost, tsProgram);
                    mailFilePath = isNg5(context.angularVersion) ? helpers_1.changeExtension(options.entryPoint, '.js') : options.entryPoint;
                    mainFile = context.fileCache.get(mailFilePath);
                    modifiedBootstrapContent = replaceBootstrap(mainFile, options.appNgModulePath, options.appNgModuleClass, options);
                    mainFile.content = modifiedBootstrapContent;
                    if (isTranspileRequired(context.angularVersion)) {
                        transpileFiles(context, tsConfig, fileSystem);
                    }
                    return [2 /*return*/];
```

**Other information:**

package.json (the upgraded one):

````
{
    "name": "app",
    "version": "1.0.0",
    "description": "App ============================================================================",
    "main": "index.js",
    "dependencies": {
        "@angular/common": "5.2.1",
        "@angular/compiler": "5.2.1",
        "@angular/compiler-cli": "5.2.1",
        "@angular/core": "5.2.1",
        "@angular/forms": "5.2.1",
        "@angular/http": "5.2.1",
        "@angular/platform-browser": "5.2.1",
        "@angular/platform-browser-dynamic": "5.2.1",
        "@angular/tsc-wrapped": "4.4.6",
        "@ionic-native/camera": "4.5.2",
        "@ionic-native/core": "4.5.2",
        "@ionic-native/geolocation": "4.5.2",
        "@ionic-native/in-app-browser": "4.5.2",
        "@ionic-native/local-notifications": "4.5.2",
        "@ionic-native/native-page-transitions": "4.5.2",
        "@ionic-native/network": "4.5.2",
        "@ionic-native/push": "4.5.2",
        "@ionic-native/splash-screen": "4.5.2",
        "@ionic-native/status-bar": "4.5.2",
        "@ionic/storage": "2.1.3",
        "@ngx-translate/core": "9.0.2",
        "@ngx-translate/http-loader": "0.1.0",
        "@types/node": "8.5.5",
        "blob-util": "1.3.0",
        "change-case": "3.0.1",
        "com.telerik.plugins.nativepagetransitions": "^0.6.5",
        "cordova-android": "^6.4.0",
        "cordova-android-support-gradle-release": "^1.2.1",
        "cordova-browser": "^5.0.1",
        "cordova-plugin-app-event": "^1.2.1",
        "cordova-plugin-background-mode": "^0.7.2",
        "cordova-plugin-camera": "^4.0.1",
        "cordova-plugin-compat": "^1.2.0",
        "cordova-plugin-device": "^1.1.4",
        "cordova-plugin-geolocation": "^3.0.0",
        "cordova-plugin-inappbrowser": "^2.0.0",
        "cordova-plugin-network-information": "^2.0.0",
        "cordova-plugin-splashscreen": "^5.0.0",
        "cordova-plugin-statusbar": "^2.4.0",
        "cordova-plugin-whitelist": "^1.3.2",
        "cordova-sqlite-storage": "^2.0.4",
        "de.appplant.cordova.plugin.local-notification": "^0.8.5",
        "intl": "1.2.5",
        "ionic-angular": "3.9.2",
        "ionic-img-viewer": "^2.9.0",
        "ionic-plugin-keyboard": "^2.2.1",
        "leaflet": "1.1.0",
        "leaflet.markercluster": "1.3.0",
        "phonegap-plugin-push": "^1.10.3",
        "rxjs": "5.5.2",
        "suncalc": "1.8.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.18"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.8",
        "babel-minify": "^0.2.0",
        "del-cli": "1.1.0",
        "glob-run": "0.1.6",
        "icon-font-generator": "1.1.1",
        "js-beautify": "1.6.14",
        "minimatch": "^3.0.4",
        "npm-run-all": "4.0.2",
        "object-keys": "^1.0.11",
        "renamer": "0.6.1",
        "replace": "0.3.0",
        "svgo": "0.7.2",
        "tslint": "^5.9.1",
        "typedoc": "0.7.1",
        "typescript": "2.4.2",
        "typescript-formatter": "5.2.0"
    },
    "scripts": {
        "build": "ionic-app-scripts build",
        "lint": "tslint -c tslint.json -p tsconfig.json 'src/**/*.ts' --type-check",
        "fix-html": "glob-run \"html-beautify -r src/**/*.html\"",
        "fix-css": "glob-run \"css-beautify -r src/**/*.css\"",
        "fix-scss": "glob-run \"css-beautify -r src/**/*.scss\"",
        "fix-tsfmt": "tsfmt -r",
        "fix-style": "run-p -c \"fix-html\" \"fix-css\" \"fix-scss\" \"fix-tsfmt\"",
        "fix-tslint": "tslint -c tslint.json -p tsconfig.json 'src/**/*.ts' --type-check --fix",
        "fix-icons": "svgo -f resources/icons",
        "fix-svg": "glob-run \"svgo -i src/**/*.svg\"",
        "fix-ts": "run-s -c \"fix-tsfmt\" \"fix-tslint\"",
        "fix": "run-p -c \"fix-html\" \"fix-css\" \"fix-scss\" \"fix-ts\" \"fix-svg\" \"fix-icons\"",
        "doc": "typedoc --out docs/ --name App-Docs --target ES5 --excludePrivate --mode file",
        "update-icon-font": "icon-font-generator resources/icons/*.svg -o resources/icons/fonts -n 
icons --htmlpath resources/icons/preview.html -t i -j true -f ./fonts/ --normalize --types woff && del-cli resources/icons/fonts/icons.scss && renamer --find css --replace scss resources/icons/fonts/icons.css && replace \"^(@font-face {)\" \"/* This file is automatically generated. Do not edit it. */$-icons-font-path: $font-path !default;$1\" resources/icons/fonts/icons.scss -m && replace \"(url\\(.).*(\\/.*?\\.)\" \"$1#{$$-icons-font-path}$2\" resources/icons/fonts/icons.scss && css-beautify -r resources/icons/fonts/icons.scss",
        "font": "run-s \"fix-icons\" \"update-icon-font\""
    },
    "repository": {
        "type": "git",
        "url": ""
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "cordova": {
        "platforms": [
            "android",
            "browser"
        ],
        "plugins": {
            "com.telerik.plugins.nativepagetransitions": {},
            "cordova-plugin-background-mode": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-geolocation": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "cordova-sqlite-storage": {},
            "de.appplant.cordova.plugin.local-notification": {},
            "phonegap-plugin-push": {
                "SENDER_ID": "986342598031"
            },
            "cordova-plugin-device": {},
            "ionic-plugin-keyboard": {},
            "cordova-plugin-compat": {},
            "cordova-android-support-gradle-release": {
                "ANDROID_SUPPORT_VERSION": "24.+"
            }
        }
    },
    "config": {
        "ionic_copy": "./config/copy.config.js",
        "ionic_sass": "./config/sass.config.js"
    }
}
````

package_old.json (before the Upgrade):

````
{
    "name": "app",
    "version": "1.0.0",
    "description": "App ============================================================================",
    "main": "index.js",
    "dependencies": {
        "@angular/animations": "4.1.3",
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@angular/platform-server": "4.1.3",
        "@angular/router": "4.1.3",
        "@ionic-native/camera": "3.8.1",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/geolocation": "3.14.0",
        "@ionic-native/in-app-browser": "4.1.0",
        "@ionic-native/local-notifications": "4.0.1",
        "@ionic-native/native-page-transitions": "3.13.1",
        "@ionic-native/native-storage": "3.12.2",
        "@ionic-native/network": "3.12.2",
        "@ionic-native/push": "3.8.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "@ngx-translate/core": "7.1.0",
        "@ngx-translate/http-loader": "0.1.0",
        "@types/node": "8.0.15",
        "blob-util": "1.3.0",
        "change-case": "3.0.1",
        "com.telerik.plugins.nativepagetransitions": "0.6.5",
        "cordova-android": "6.2.3",
        "cordova-browser": "4.1.0",
        "cordova-custom-config": "4.0.2",
        "cordova-ios": "4.4.0",
        "cordova-plugin-app-event": "1.2.0",
        "cordova-plugin-background-mode": "0.7.2",
        "cordova-plugin-camera": "2.4.1",
        "cordova-plugin-compat": "1.1.0",
        "cordova-plugin-console": "1.0.7",
        "cordova-plugin-device": "1.1.6",
        "cordova-plugin-geolocation": "2.4.3",
        "cordova-plugin-inappbrowser": "1.7.1",
        "cordova-plugin-mqtt": "file:../mqtt-plugin",
        "cordova-plugin-nativestorage": "2.2.2",
        "cordova-plugin-network-information": "1.3.3",
        "cordova-plugin-splashscreen": "4.0.3",
        "cordova-plugin-statusbar": "2.2.3",
        "cordova-plugin-whitelist": "1.3.2",
        "cordova-sqlite-storage": "2.0.4",
        "de.appplant.cordova.plugin.local-notification": "0.8.5",
        "intl": "1.2.5",
        "ionic-angular": "3.4.2",
        "ionic-img-viewer": "2.4.0",
        "ionic-plugin-keyboard": "2.2.1",
        "leaflet": "1.1.0",
        "phonegap-plugin-push": "1.10.3",
        "rxjs": "5.4.0",
        "suncalc": "1.8.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "1.3.12",
        "@ionic/cli-plugin-cordova": "1.4.1",
        "@ionic/cli-plugin-ionic-angular": "1.3.2",
        "del-cli": "1.1.0",
        "glob-run": "0.1.6",
        "icon-font-generator": "1.1.1",
        "js-beautify": "1.6.14",
        "npm-run-all": "4.0.2",
        "renamer": "0.6.1",
        "replace": "0.3.0",
        "svgo": "0.7.2",
        "tslint": "5.2.0",
        "typedoc": "0.7.1",
        "typescript": "2.3.4",
        "typescript-formatter": "5.2.0"
    },
    "scripts": {
        "build": "ionic-app-scripts build",
        "lint": "tslint -c tslint.json -p tsconfig.json 'src/**/*.ts' --type-check",
        "fix-html": "glob-run \"html-beautify -r src/**/*.html\"",
        "fix-css": "glob-run \"css-beautify -r src/**/*.css\"",
        "fix-scss": "glob-run \"css-beautify -r src/**/*.scss\"",
        "fix-tsfmt": "tsfmt -r",
        "fix-style": "run-p -c \"fix-html\" \"fix-css\" \"fix-scss\" \"fix-tsfmt\"",
        "fix-tslint": "tslint -c tslint.json -p tsconfig.json 'src/**/*.ts' --type-check --fix",
        "fix-icons": "svgo -f resources/icons",
        "fix-svg": "glob-run \"svgo -i src/**/*.svg\"",
        "fix-ts": "run-s -c \"fix-tsfmt\" \"fix-tslint\"",
        "fix": "run-p -c \"fix-html\" \"fix-css\" \"fix-scss\" \"fix-ts\" \"fix-svg\" \"fix-icons\"",
        "doc": "typedoc --out docs/ --name App-Docs --target ES5 --excludePrivate --mode file",
        "update-icon-font": "icon-font-generator resources/icons/*.svg -o resources/icons/fonts -n icons --htmlpath resources/icons/preview.html -t i -j true -f ./fonts/ --normalize --types woff && del-cli resources/icons/fonts/icons.scss && renamer --find css --replace scss resources/icons/fonts/icons.css && replace \"^(@font-face {)\" \"/* This file is automatically generated. Do not edit it. */$-icons-font-path: $font-path !default;$1\" resources/icons/fonts/icons.scss -m && replace \"(url\\(.).*(\\/.*?\\.)\" \"$1#{$$-icons-font-path}$2\" resources/icons/fonts/icons.scss && css-beautify -r resources/icons/fonts/icons.scss",
        "font": "run-s \"fix-icons\" \"update-icon-font\""
    },
    "repository": {
        "type": "git",
        "url": ""
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "cordova": {
        "platforms": [
            "android",
            "browser"
        ],
        "plugins": {
            "com.telerik.plugins.nativepagetransitions": {},
            "cordova-custom-config": {},
            "cordova-plugin-background-mode": {},
            "cordova-plugin-camera": {},
            "cordova-plugin-compat": {},
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-geolocation": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-mqtt": {},
            "cordova-plugin-nativestorage": {},
            "cordova-plugin-network-information": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "cordova-sqlite-storage": {},
            "de.appplant.cordova.plugin.local-notification": {},
            "ionic-plugin-keyboard": {},
            "phonegap-plugin-push": {
                "SENDER_ID": "986342598031"
            }
        }
    },
    "config": {
        "ionic_copy": "./config/copy.config.js",
        "ionic_sass": "./config/sass.config.js"
    }
}
````
**Ionic info:** 

```
cli packages: (C:\Users\User\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0
global packages:
    cordova (Cordova CLI) : 7.0.0
local packages:
    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0 browser 5.0.1
    Ionic Framework    : ionic-angular 3.9.2
System:
    Android SDK Tools : 26.1.1
    Node              : v8.9.3
    npm               : 5.7.1
    OS                : Windows 7

Environment Variables:
    ANDROID_HOME : C:\Users\User\AppData\Local\Android\sdk
Misc:

    backend : pro
```

**Comment by mburger81** [comment]
You are confusing something.
Lastest ionic-angular is 3.9.2 and latest ionic cli is 3.20.0
If this is a cli issue this is not the right point to submit the issue

**Comment by lubra123** [comment]
Hey Scott,

I solved this by removing some settings in the tsconfig.json and updating the http-service to http-client. Could you post your tsconfig.json here maybe?
