### ISSUE TITLE
Macbook pro : Live reloading after saving changes in default helloworld application do not work

### ISSUE THREAD

**Issue by samir-kamble** [ionic-team/ionic#14431]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**

I am not able to see live Reloading of application pages. I have freshly installed nodeJS and NPM on my system and created HelloWorld application which is being provided by Ionic team. 

**Expected behavior:**

Application must be auto reloading with changes whenever I will save them on my editor. 

**Steps to reproduce:**

Following instructions on ionic framework to start hello world application.
1. npm install -g ionic cordova
2. ionic start helloWorld blank
3. cd helloWorld
4. ionic serve

Application starts on 8100 port but any changes to code is not getting detected on browser even manual refresh dosen't bring up changes. I doubt there is something wrong with builder.

```
insert short code snippets here
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
insert the output from ionic info here
Apples-MacBook-Air:helloWorld apple$ ionic info

cli packages: (/Users/Apple/npm-global/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0 
    OS   : OS X Yosemite

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by samir-kamble** [comment]
**Update** 
I have uninstalled my node version  8.11.1 and reinstalled latest version of it via Homebrew as per my readings and suggestions on ionic forums.

So my new **ionic info** is as follows

`apple@Apples-MacBook-Air:/Users/Apple/Documents/practice/helloWorld$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : none
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v10.0.0
    npm  : 5.6.0 
    OS   : OS X Yosemite

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro`

Please someone help. This is really getting me restless now.

Regards,
Samir

**Comment by samir-kamble** [comment]
Reinstalled ionic and getting following errors. Please do confirm if they are causing this problem of not reloading after save. I have set Write access open to the mentioned directory but its not getting installed.

```
> fsevents@1.2.3 install /usr/local/lib/node_modules/ionic/node_modules/fsevents
> node install

node-pre-gyp ERR! Pre-built binaries not installable for fsevents@1.2.3 and node@10.0.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error EACCES: permission denied, mkdir '/usr/local/lib/node_modules/ionic/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /usr/local/lib/node_modules/ionic/node_modules/fsevents
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/10.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ionic/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/lib/node_modules/ionic/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/ionic/node_modules/fsevents
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.9.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/10.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/ionic/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ionic@3.20.0
+ cordova@8.0.0
added 677 packages in 80.432s```

**Comment by samir-kamble** [comment]
Got it working by moving my project folder to "/usr/local/lib".

I think it is all about Folder write permissions. I cannot place my ionic installation other than mentioned directory If I do I get failed in LIVE RELOAD.

I hope this helps many people out here.
