### ISSUE TITLE
ionic with angular universal SSR error

### ISSUE THREAD

**Issue by Jimmysh** [ionic-team/ionic#14538]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/share/.config/yarn/global/node_modules)

   @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

System:

   NodeJS : v9.11.1
   npm    : 5.6.0
   OS     : macOS High Sierra
```

**Describe the Bug**

```
Node Express server listening on http://localhost:4000
ERROR TypeError: Cannot read property 'parentNode' of undefined
    at HTMLHeadElement._ensureInsertValid (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:84448:17)
    at HTMLHeadElement.insertBefore (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:84573:12)
    at M (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:132888:17035)
    at defineCustomElements (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:132763:77)
    at Array.<anonymous> (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:132728:85)
    at ApplicationInitStatus.runInitializers (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:7067:50)
    at /Users/jimmy/Desktop/universal-starter-master/dist/server.js:8641:28
    at _callAndReportToErrorHandler (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:8784:22)
    at /Users/jimmy/Desktop/universal-starter-master/dist/server.js:8639:20
    at ZoneDelegate.invoke (/Users/jimmy/Desktop/universal-starter-master/dist/server.js:558:26)
```

**Steps to Reproduce**
- clone https://github.com/Jimmysh/ionic-angular-ssr-test
- `npm run build:ssr`
- `npm run serve:ssr`

**Related Code**
 https://github.com/Jimmysh/ionic-angular-ssr-test

**Comment by paulstelzer** [comment]
Is this still an issue in beta.17?

**Comment by Jimmysh** [comment]
Duplicate of #15041
