### ISSUE TITLE
Navigation in ajax call success not working in ionic 3

### ISSUE THREAD

**Issue by Shadzzz** [ionic-team/ionic#14549]
get_info()
	{
	 	var a = this.username; //alert(a);
		var b = this.password; //alert(b);

	$.ajax({
       	type: 'post',
        dataType: 'json',
        url: 'http://xxxx/xxxx/xxxxx/login.php',
       	data: {
		username: a,
		password: b
       	},
       	success: function(data) { 
		alert('Login Successfull');
		**this.navCtrl.push(LatlongPage);**       // Error: Cannot read property 'push' of undefined

		}//success
		 });//ajax

	}

ERROR:

TypeError: Cannot read property 'push' of undefined
    at Object.success (http://localhost:8100/build/main.js:216:30)
    at fire (http://localhost:8100/build/vendor.js:127005:31)
    at Object.fireWith [as resolveWith] (http://localhost:8100/build/vendor.js:127135:7)
    at done (http://localhost:8100/build/vendor.js:133042:14)
    at XMLHttpRequest.<anonymous> (http://localhost:8100/build/vendor.js:133285:9)
    at XMLHttpRequest.H (http://localhost:8100/build/polyfills.js:3:23950)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5125:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)

**Comment by KillerCodeMonkey** [comment]
this is not an ionic 3 issue.. if you are using jquery.ajax you are running code outside of angulars ngZone.

aaannd

your error --> your ajax callbacks are executed in the jquery context (`this` is not your component instance!)
Use fat-arrow functions for that.

```
success: (data) => { 
  // this should be your component instance defined
}
```

**Comment by Shadzzz** [comment]
Thanks KillerCodeMonkey
