### ISSUE TITLE
ionic 4 server side rendering error

### ISSUE THREAD

**Issue by guzuomuse** [ionic-team/ionic#14559]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
 @ionic/cli-utils  : 2.0.0-rc.6
   ionic (Ionic CLI) : 4.0.0-rc.6

local packages:

   @angular-devkit/core       : 0.6.0
   @angular-devkit/schematics : 0.6.0
   @angular/cli               : 6.0.1
   @ionic/schematics-angular  : 1.0.0-rc.6
   Ionic Framework            : @ionic/angular 4.0.0-alpha.7
System:

   NodeJS : v8.9.4
   npm    : 5.6.0
   OS     : Windows 10

```

**Describe the Bug**
angular 6+ app using ionic. server side rendering error:

```
document.addEventListener('deviceready', function () {
    ^

ReferenceError: document is not defined
    at checkReady (D:\www\ionic\v4\test5\www\server.js:140566:5)
    at Object.<anonymous> (D:\www\ionic\v4\test5\www\server.js:140548:62)
    at __webpack_require__ (D:\www\ionic\v4\test5\www\server.js:29:30)
    at Object.<anonymous> (D:\www\ionic\v4\test5\www\server.js:140458:76)
    at __webpack_require__ (D:\www\ionic\v4\test5\www\server.js:29:30)
    at Object.@ionic-native/splash-screen/ngx (D:\www\ionic\v4\test5\www\server.js:128188:18)
    at __webpack_require__ (D:\www\ionic\v4\test5\www\server.js:127618:30)
    at Object../src/app/app.component.ts (D:\www\ionic\v4\test5\www\server.js:127749:13)
    at __webpack_require__ (D:\www\ionic\v4\test5\www\server.js:127618:30)
    at Object../src/app/app.server.module.ngfactory.js (D:\www\ionic\v4\test5\www\server.js:127809:10)

```

**Comment by dwieeb** [comment]
@guzuomuse We don't fully support SSR yet

Let's track it here: https://github.com/ionic-team/ionic/issues/14574
