### ISSUE TITLE
Fresh npm install, ionic build ios fails on OSX

### ISSUE THREAD

**Issue by Fmstrat** [ionic-team/ionic#14571]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
[fmstrat@MBPR13 myapp]$ ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 5.1.1 
    Gulp CLI              : CLI version 2.0.1 Local version 4.0.0

local packages:

    Cordova Platforms : none
    Ionic Framework   : ionic1 1.3.3

System:

    ios-deploy : 1.7.0 
    Node       : v10.3.0
    npm        : 6.1.0 
    OS         : macOS High Sierra

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Describe the Bug**
Building a blank project for ios throws a blank exception:
```
[fmstrat@MBPR13 myapp]$ ionic cordova build ios
> cordova platform add ios --save
Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at evalmachine.<anonymous>:46:26
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/tar/node_modules/fstream/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[ERROR] Exception: 
```

**Steps to Reproduce**
```
brew uninstall --force node; 
brew prune;
rm -f /usr/local/bin/npm /usr/local/lib/dtrace/node.d;
rm -rf ~/.npm;
brew install node;
npm rebuild
ionic cordova build ios
```

**Related Code**
n/a

**Expected Behavior**
Clean build.

**Additional Context**
n/a

**Comment by Fmstrat** [comment]
Some further investigation:

iOS install guide (https://cordova.apache.org/docs/en/8.x/guide/platforms/ios/) is missing:
```
npm install -g cordova
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```
Prior to:
```
npm install -g ios-deploy
```

I would consider linking https://cordova.apache.org/docs/en/8.x/guide/platforms/ios/ and https://ionicframework.com/docs/v1/guide/installation.html

Many of us don't use Xcode SDK, and there is no obvious drive from the Getting Started guide to the command line setup.

Thanks!

**Comment by mhartington** [comment]
Hi there! The cordova docs and setup are all documented on our getting started guide, here 

https://ionicframework.com/docs/intro/installation/

Please give them a read! 
Thanks!
