### ISSUE TITLE
TypeError: Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by vgpastor** [ionic-team/ionic#14613]
# Bug Report

**Ionic Info**
```
cli packages: (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules)
    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0
global packages:
    cordova (Cordova CLI) : 8.0.0
local packages:
    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.1.0 browser 5.0.3 ios 4.5.4 windows 6.0.0
    Ionic Framework    : ionic-angular 3.9.2
System:
    Node : v8.9.4
    npm  : 6.1.0
    OS   : Windows 10
Environment Variables:
    ANDROID_HOME : not set
Misc:
    backend : pro
```

**Describe the Bug**
Can't build or compile the project in prod mode

**Steps to Reproduce**
1. Remove node_modules , platforms, plugins and package-lock.json
2. npm i
3.  ionic build "--prod" "--aot" "--env" "prod"
4. Show the error below
```
PS` C:\Android\test01> ionic build "--prod" "--aot" "--env" "prod"
Running app-scripts build: --prod --aot --env prod
[01:20:10]  build prod started ...
[01:20:10]  clean started ...
[01:20:10]  clean finished in 10 ms
[01:20:10]  copy started ...
[01:20:11]  deeplinks started ...
[01:20:11]  deeplinks finished in 26 ms
[01:20:11]  ngc started ...
Warning: Can't resolve all parameters for AngularFirestore in C:/Android/test01/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AngularFirestore in C:/Android/test01/node_modules/angularfire2/firestore/index.d.ts: ([object Object], ?). This will become an error in Angular v6.x
TypeError: Cannot read property 'flags' of undefined
    at checkUnreachable (C:\Android\test01\node_modules\typescript\lib\typescript.js:24905:31)
    at bindChildrenWorker (C:\Android\test01\node_modules\typescript\lib\typescript.js:23111:17)
    at bindChildren (C:\Android\test01\node_modules\typescript\lib\typescript.js:23055:17)
    at bind (C:\Android\test01\node_modules\typescript\lib\typescript.js:24319:21)
    at bindSourceFile (C:\Android\test01\node_modules\typescript\lib\typescript.js:22689:17)
    at Object.bindSourceFile (C:\Android\test01\node_modules\typescript\lib\typescript.js:22640:9)
    at initializeTypeChecker (C:\Android\test01\node_modules\typescript\lib\typescript.js:47988:20)
    at Object.createTypeChecker (C:\Android\test01\node_modules\typescript\lib\typescript.js:27142:9)
    at getDiagnosticsProducingTypeChecker (C:\Android\test01\node_modules\typescript\lib\typescript.js:69678:93)
    at emitWorker (C:\Android\test01\node_modules\typescript\lib\typescript.js:69722:32)
[01:20:17]  copy finished in 6.69 s
```

**packaje.json**
```
{
  "name": "test01",
  "version": "0.2.13",
  "author": "Ingenieros Web",
  "homepage": "https://ingenierosweb.co/",
  "private": true,
  "scripts": {
    "clean": "ionic clean",
    "build": "ionic build --prod --env=prod --aot",
    "lint": "ionic lint",
    "ionic:build": "ionic build",
    "ionic:serve": "ionic serve -p 8111",
    "android:run": "ionic build & cordova run android --device",
    "android:debug": "ionic build & cordova build android",
    "android:release": "ionic build & cordova build android --prod --release",
    "reinstall": "rm -r node_modules & rm -r platforms & rm -r plugins & rm package-lock.json & npm i & ionic build"
  },
  "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11",
    "@fortawesome/fontawesome-svg-core": "^1.2.0-11",
    "@fortawesome/free-brands-svg-icons": "^5.1.0-11",
    "@fortawesome/free-solid-svg-icons": "^5.1.0-11",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "^4.7.0",
    "@ionic-native/fcm": "^4.7.0",
    "@ionic-native/file": "^4.7.0",
    "@ionic-native/firebase": "^4.7.0",
    "@ionic-native/firebase-analytics": "^4.7.0",
    "@ionic-native/geolocation": "^4.7.0",
    "@ionic-native/google-maps": "^4.8.2",
    "@ionic-native/image-picker": "^4.7.0",
    "@ionic-native/image-resizer": "^4.7.0",
    "@ionic-native/in-app-browser": "^4.7.0",
    "@ionic-native/native-geocoder": "^4.7.0",
    "@ionic-native/social-sharing": "^4.7.0",
    "@ionic-native/splash-screen": "^4.7.0",
    "@ionic-native/status-bar": "^4.7.0",
    "@ionic-native/toast": "^4.7.0",
    "@ionic/pro": "^1.0.20",
    "@ionic/storage": "2.1.3",
    "@ngx-share/core": "^5.3.1",
    "@tinymce/tinymce-angular": "^2.0.0",
    "angularfire2": "5.0.0-rc.4",
    "cordova-android": "7.1.0",
    "cordova-browser": "^5.0.3",
    "cordova-ios": "^4.5.4",
    "cordova-plugin-browsertab": "^0.2.0",
    "cordova-plugin-buildinfo": "^2.0.1",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-customurlscheme": "^4.3.0",
    "cordova-plugin-device": "^1.1.6",
    "cordova-plugin-firebase-analytics": "0.12.1",
    "cordova-plugin-inappbrowser": "^1.7.1",
    "cordova-plugin-ionic": "^3.1.3",
    "cordova-plugin-ionic-keyboard": "^2.0.2",
    "cordova-plugin-ionic-webview": "^1.1.15",
    "cordova-plugin-splashscreen": "^5.0.1",
    "cordova-plugin-statusbar": "^2.2.3",
    "cordova-plugin-whitelist": "^1.3.2",
    "cordova-plugin-x-socialsharing": "^5.4.0",
    "cordova-support-android-plugin": "^0.3.7",
    "cordova-support-google-services": "^1.2.0",
    "cordova-universal-links-plugin": "git+https://github.com/walteram/cordova-universal-links-plugin.git",
    "cordova-windows": "^6.0.0",
    "es6-promise-plugin": "~4.2.2",
    "firebase": "4.8.0",
    "ionic-angular": "3.9.2",
    "ionic-img-viewer": "^2.9.0",
    "ionic-tags-input": "^0.1.2",
    "ionicons": "3.0.0",
    "ngx-chips": "1.8.2",
    "ngx-moment": "^2.0.0",
    "rxjs": "5.5.2",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0-beta.4",
    "@angular/compiler-cli": "^5.2.11",
    "@angular/language-service": "^5.2.11",
    "@ionic/app-scripts": "^3.1.10",
    "typescript": "~2.4.1"
  },
  "config": {
    "ionic_aot_write_to_disk": true
  },
  "cordova": {
    "platforms": [
      "android",
      "ios",
      "windows",
      "browser"
    ],
    "plugins": {
      "cordova-plugin-device": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-x-socialsharing": {},
      "es6-promise-plugin": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-buildinfo": {},
      "cordova-plugin-browsertab": {},
      "cordova-plugin-customurlscheme": {
        "URL_SCHEME": "co.ingenierosweb.test01",
        "ANDROID_SCHEME": " ",
        "ANDROID_HOST": " ",
        "ANDROID_PATHPREFIX": "/"
      },
      "cordova-universal-links-plugin": {},
      "cordova-plugin-firebase-analytics": {
        "FIREBASE_CORE_VERSION": "16.0.+",
        "FIREBASE_VERSION": "11.6.2"
      },
      "cordova-plugin-ionic": {
        "APP_ID": "XXXXX",
        "CHANNEL_NAME": "Master",
        "UPDATE_METHOD": "background"
      }
    }
  }
}
```

**config.xml**
```
<?xml version='1.0' encoding='utf-8'?>
<widget defaultlocale="es-ES" id="co.ingenierosweb.test01" version="0.2.13" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Test01</name>
    <description>Share plans and meet new people</description>
    <author email="info@ingenierosweb.co" href="https://ingenierosweb.co/">Ingenieros Web</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="http://*/*" />
    <platform name="android">
        <resource-file src="google-services.json" target="/resources/google-services.json" />
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <icon src="resources/android/icon/drawable-xhdpi-icon.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
    </platform>
    <preference name="orientation" value="default" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="StatusBarStyle" value="default" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="ShowSplashScreenSpinner" value="false" />
    <preference name="AutoHideSplashScreen" value="false" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="xwalkMultipleApk" value="false" />
    <preference name="loadUrlTimeoutValue" value="60000" />
    <preference name="AndroidLaunchMode" value="singleTask" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^1.1.15" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.2" />
    <vs:toolsetVersion xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps">6.3.1</vs:toolsetVersion>
    <preference name="windows-target-version" value="10.0" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.0" />
    <plugin name="es6-promise-plugin" spec="~4.2.2" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <plugin name="cordova-plugin-camera" spec="^4.0.3" />
    <plugin name="cordova-plugin-buildinfo" spec="^2.0.1" />
    <plugin name="cordova-plugin-browsertab" spec="^0.2.0" />
    <plugin name="cordova-plugin-inappbrowser" spec="^1.7.1" />
    <universal-links>
        <host name="test01.app.goo.gl" scheme="https">
            <path url="*" />
            <path url="/" />
        </host>
        <host name="test01.firebaseapp.com" scheme="https">
            <path url="/__/auth/callback" />
        </host>
    </universal-links>
    <plugin name="cordova-plugin-customurlscheme" spec="^4.3.0">
        <variable name="URL_SCHEME" value="co.ingenierosweb.test01" />
        <variable name="ANDROID_SCHEME" value=" " />
        <variable name="ANDROID_HOST" value=" " />
        <variable name="ANDROID_PATHPREFIX" value="/" />
    </plugin>
    <plugin name="cordova-plugin-firebase-analytics" spec="0.12.1">
        <variable name="FIREBASE_CORE_VERSION" value="16.0.+" />
        <variable name="FIREBASE_VERSION" value="11.6.2" />
    </plugin>
    <plugin name="cordova-support-android-plugin" spec="~0.3.7" />
    <plugin name="cordova-support-google-services" spec="~1.2.0" />
    <plugin name="cordova-universal-links-plugin" spec="https://github.com/walteram/cordova-universal-links-plugin.git" />
    <engine name="android" spec="7.1.0" />
    <engine name="ios" spec="^4.5.4" />
    <engine name="windows" spec="^6.0.0" />
    <engine name="browser" spec="^5.0.3" />
</widget>

```

**Comment by mhartington** [comment]
Hi there! This is not an issue specific to the framework, but to ionic-app-scripts.
The real issues is that app scripts does not have an `--env` flag, so the build process does not know how to process it.
