### ISSUE TITLE
Unable to deploy ionic app for production

### ISSUE THREAD

**Issue by suryakant89** [ionic-team/ionic#14789]
Hi,
I am new to Ionic and have created an ionic app, I want to publish it but getting the below issue.

$ ionic cordova build android --prod --release
Running app-scripts build: --prod --platform android --target cordova
[15:08:00]  build prod started ...
[15:08:00]  clean started ...
[15:08:00]  clean finished in 53 ms
[15:08:00]  copy started ...
[15:08:01]  deeplinks started ...
[15:08:01]  deeplinks finished in 178 ms
[15:08:01]  ngc started ...
[15:08:12]  typescript error
            Type AccountPage in C:/mpay/src/pages/account/account.ts is part of the declarations of 2 modules: AppModule
            in C:/mpay/src/app/app.module.ts and AccountPageModule in C:/mpay/src/pages/account/account.module.ts!
            Please consider moving AccountPage in C:/mpay/src/pages/account/account.ts to a higher module that imports
            AppModule in C:/mpay/src/app/app.module.ts and AccountPageModule in
            C:/mpay/src/pages/account/account.module.ts. You can also create a new NgModule that exports and includes
            AccountPage in C:/mpay/src/pages/account/account.ts then import that NgModule in AppModule in
            C:/mpay/src/app/app.module.ts and AccountPageModule in C:/mpay/src/pages/account/account.module.ts.

Error: The Angular AoT build failed. See the issues above
    at C:\mpay\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (C:\mpay\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (C:\mpay\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (C:\mpay\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
[15:08:12]  copy finished in 11.90 s

**Comment by nathantaal** [comment]
You should fix your imports (Or better, implement lazy loading).
But this issue is solved a lot of times:
https://forum.ionicframework.com/t/ionic-build-prod-error-type-in-is-part-of-the-declarations-of-2-modules/87350/3
