### ISSUE TITLE
AlertController error: Cannot read property '_getPortal' of undefined

### ISSUE THREAD

**Issue by Robofolk** [ionic-team/ionic#14785]
**Ionic version:**  (check one with "x")
(For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[x] **3.x**
[ ] **4.x**

**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**Current behavior:**
I’m using Ionic v3.20.0. AlertController gives me the following error:

```
Runtime Error
Cannot read property '_getPortal' of undefined
Stack
TypeError: Cannot read property '_getPortal' of undefined
    at App.present (http://localhost:8100/build/vendor.js:22543:36)
    at Alert.present (http://localhost:8100/build/vendor.js:58761:26)
    at TermsAndConditionsPage.webpackJsonp.360.TermsAndConditionsPage.showBasicAlert (http://localhost:8100/build/1.js:333:20)
    at Object.eval [as handleEvent] (ng:///TermsAndConditionsPageModule/TermsAndConditionsPage.ngfactory.js:43:31)
    at handleEvent (http://localhost:8100/build/vendor.js:13963:155)
    at callWithDebugContext (http://localhost:8100/build/vendor.js:15472:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:8100/build/vendor.js:15059:12)
    at dispatchEvent (http://localhost:8100/build/vendor.js:10378:25)
    at http://localhost:8100/build/vendor.js:11003:38
    at HTMLButtonElement.<anonymous> (http://localhost:8100/build/vendor.js:39492:53)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.10
Angular Core: 5.2.11
Angular Compiler CLI: 5.2.11
Node: 8.11.1
OS Platform: Windows 7
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
```

**Expected behavior:**
No error is given and alert is shown up.

**Steps to reproduce:**
When button is clicked I get the above error.

**Related code:**

```
import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams, MenuController, AlertController } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-terms-and-conditions',
  templateUrl: 'terms-and-conditions.html',
})
export class TermsAndConditionsPage {

  constructor(public navCtrl: NavController,
              public navParams: NavParams,
              public menu: MenuController,
              private alertController: AlertController) {
  }

      showBasicAlert() {
        let basicAlert = this.alertController.create({
          title: 'Ionic alert',
          subTitle: 'ionic alert details',
          buttons: ['OK']
        });
        basicAlert.present();      
  }
}
```

```
<ion-header>
    <ion-navbar>
      <ion-title>Alert Controller</ion-title>
    </ion-navbar>
</ion-header>
  
  <ion-content padding>
    <ion-item-group>
      <ion-item-divider color="light">Basic Alerts</ion-item-divider>
         <button ion-button full (click)="showBasicAlert()">Basic</button>    
    </ion-item-group>
  </ion-content>
```

```
import { NgModule } from '@angular/core';
import { IonicPageModule, IonicModule } from 'ionic-angular';
import { TermsAndConditionsPage } from './terms-and-conditions';

@NgModule({
  declarations: [
    TermsAndConditionsPage,
  ],
  imports: [
    IonicPageModule.forChild(TermsAndConditionsPage),
    IonicModule
  ],
  exports: [
    TermsAndConditionsPage
  ]
})
export class TermsAndConditionsPageModule {}
```

**Other information:**

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
cli packages: (C:\Users\XXXXXXXX\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Windows 7

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

```

**Comment by Robofolk** [comment]
Phewww, I found the cause of this problem. In my project there was components.module.ts file somewhere, which had the following imports within NgModule:

```
import { NgModule } from '@angular/core';
import { IonicModule } from 'ionic-angular';
import { TermsAndConditionsComponent } from './terms-and-conditions/terms-and-conditions';

@NgModule({
	declarations: [
        TermsAndConditionsComponent,
    ],
	imports: [
        // IonicModule.forRoot(TermsAndConditionsComponent), <= THIS LINE CAUSED ALL THE ISSUES. THE FOLLOWING LINE SHOULD BE USED INSTEAD
        IonicModule
    ],
    exports: [
        TermsAndConditionsComponent
    ]
})

```
export class ComponentsModule {}
When I replaced the line IonicModule.forRoot(TermsAndConditionsComponent), with IonicModule instead then the AlertController started working just fine.

I’m not sure whether it’s purely my mistake or if it’s a bug though.
