### ISSUE TITLE
Downloading and extracting blank starter - failed!

### ISSUE THREAD

**Issue by YusykYura** [ionic-team/ionic#15068]
# Support Question
Dear community, please help resolve this problem! Perhaps someone had something similar.

TypeError: You must specify a "protocol" for the proxy type (http, https, socks, socks4, socks4a, socks5, socks5h, pac+data, pac+file, pac+http, pac+https)

at mapOptsToProxy (C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\proxy-agent\index.js:100:11)
at new ProxyAgent (C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\proxy-agent\index.js:150:17)
at ProxyAgent (C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\proxy-agent\index.js:145:45)
at Request.proxy (C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\superagent-proxy\index.js:71:15)
at C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\@ionic\cli-utils\lib\utils\http.js:32:21
at Generator.next (<anonymous>)
at fulfilled (C:\Users\User\AppData\Roaming\npm\node_modules\ionic\node_modules\tslib\tslib.js:104:62)
at <anonymous>

**Comment by YusykYura** [comment]
https://ionic.zendesk.com/hc/en-us/community/posts/360014564874-Downloading-and-extracting-blank-starter-failed-
