### ISSUE TITLE
Ionic 4.0.0-beta.3 Ion-select Unhandled Promise rejection when using async data offline

### ISSUE THREAD

**Issue by samrat-bhandari** [ionic-team/ionic#15314]
# Bug Report

**Ionic Info**

Ionic:
   ionic (Ionic CLI)          : 4.1.1 (/home/user/.nvm/versions/node/v8.11.3/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.3
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.7
   @ionic/schematics-angular  : 1.0.5
Cordova:
   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)
System:
   NodeJS : v8.11.3 (/home/user/.nvm/versions/node/v8.11.3/bin/node)
   npm    : 5.6.0
   OS     : Linux 4.15

**Describe the Bug**
Ion-select fails with an Unhandled Promise rejection anytime you use it with async data as such:

` <ion-select-option *ngFor="let project of ProjectsCollection |async" [value]="project.projectID">{{project.projectName}}</ion-select-option>`

This happen when the async data binded using 

> *ngFor="let project of ProjectsCollection |async"

is not available. In my case, when the data was supposed to be fetched via a server, everytime I take the app offline from chrome dev tools, and try to open ion-select, it gives the following error:

**Steps to Reproduce**
1. Insert the ion-select component in any page
2. In the ion-select-option, bind to an observable array using *ngFor as mention previously
3. Serve the app and immediately make the app offline before clicking on the ion-select such that the observable is not fetching the remote data yet
4. See error. I have copied the error bellow:

`Unhandled Promise rejection: Loading chunk 4 failed.
(error: http://localhost:8100/4.js) ; Zone: <root> ; Task: Promise.then ; Value: Error: Loading chunk 4 failed.
(error: http://localhost:8100/4.js)
    at HTMLScriptElement.onScriptComplete (bootstrap:134)
    at HTMLScriptElement.wrapFn (zone.js:1188)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1566) Error: Loading chunk 4 failed.
(error: http://localhost:8100/4.js)
    at HTMLScriptElement.onScriptComplete (http://localhost:8100/runtime.js:135:29)
    at HTMLScriptElement.wrapFn (http://localhost:8100/polyfills.js:3510:39)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:2743:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (http://localhost:8100/polyfills.js:2510:47)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (http://localhost:8100/polyfills.js:2818:34)
    at invokeTask (http://localhost:8100/polyfills.js:3862:14)
    at HTMLScriptElement.globalZoneAwareCallback (http://localhost:8100/polyfills.js:3888:17)
api.onUnhandledError @ zone.js:665
handleUnhandledRejection @ zone.js:692
_loop_1 @ zone.js:682
api.microtaskDrainDone @ zone.js:686
drainMicroTaskQueue @ zone.js:602
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:407
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
desc.set @ zone.js:1244
requireEnsure @ bootstrap:142
push../node_modules/@ionic/core/dist/esm/es5/ionic.components.js.ActionSheetController @ ionic.components.js:5
g @ ionic.core.js:6
(anonymous) @ ionic.core.js:6
e @ ionic.core.js:6
(anonymous) @ ionic.core.js:6
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
tick @ ionic.core.js:6
e @ ionic.core.js:6
M.e.connectedCallback @ ionic.core.js:6
J @ ionic.core.js:6
o @ ionic.core.js:6
(anonymous) @ ionic.core.js:6
(anonymous) @ lssq6lmr.js:5
(anonymous) @ lssq6lmr.js:5
(anonymous) @ lssq6lmr.js:5
(anonymous) @ lssq6lmr.js:5
ZoneAwarePromise @ zone.js:891
push../node_modules/@ionic/core/dist/esm/es5/lssq6lmr.js.__awaiter @ lssq6lmr.js:5
e.openActionSheet @ lssq6lmr.js:5
e.open @ lssq6lmr.js:5
zone.js:2969 GET https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel?database=projects%2Flikelyminds-63a7b%2Fdatabases%2F(default)&gsessionid=XxBi9DURtEVmpo9pdu9yOmP2pv_3TN2U&VER=8&RID=rpc&SID=Krd0Sz7qW5rQpo3xPcrasQ&CI=0&AID=17&TYPE=xmlhttp&zx=runhsc5u4a0u&t=1 0 ()`

**Related Code**
` <ion-select><ion-select-option *ngFor="let project of ProjectsCollection |async" [value]="project.projectID">{{project.projectName}}</ion-select-option></ion-select>`

Where ProjectsCollection is a firebase collection, as an observable using angularfire2 library.

**Expected Behavior**
If app is offline and the asynchronous remote data binded using *ngFor cannot be loaded, then the variable holding that data is empty, which would mean that ion-select should open but show zero ion-select-options, instead of the Unhandled Promise rejection error.

**Additional Context**
Chrome dev tools shows chunk 4 failed to load due to the unhandled promised rejection. The issue might be solved by handling the promise rejection properly. Here is what was in chunk 4:

`(window["webpackJsonp"] = window["webpackJsonp"] || []).push([[4],{

/***/ "./node_modules/@ionic/core/dist/esm/es5/jx66mgie.js":
/*!***********************************************************!*\
  !*** ./node_modules/@ionic/core/dist/esm/es5/jx66mgie.js ***!
  \***********************************************************/
/*! exports provided: IonActionSheetController */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "IonActionSheetController", function() { return ActionSheetController; });
/* harmony import */ var _chunk_13543983_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./chunk-13543983.js */ "./node_modules/@ionic/core/dist/esm/es5/chunk-13543983.js");
/*!
 * (C) Ionic http://ionicframework.com - MIT License
 * Built with http://stenciljs.com
 */
var ActionSheetController=function(){function e(){this.actionSheets=new Map}return e.prototype.actionSheetWillPresent=function(e){this.actionSheets.set(e.target.overlayId,e.target)},e.prototype.actionSheetWillDismiss=function(e){this.actionSheets.delete(e.target.overlayId)},e.prototype.escapeKeyUp=function(){Object(_chunk_13543983_js__WEBPACK_IMPORTED_MODULE_0__["d"])(this.actionSheets)},e.prototype.create=function(e){return Object(_chunk_13543983_js__WEBPACK_IMPORTED_MODULE_0__["a"])(this.doc.createElement("ion-action-sheet"),e)},e.prototype.dismiss=function(e,t,o){return void 0===o&&(o=-1),Object(_chunk_13543983_js__WEBPACK_IMPORTED_MODULE_0__["b"])(e,t,this.actionSheets,o)},e.prototype.getTop=function(){return Object(_chunk_13543983_js__WEBPACK_IMPORTED_MODULE_0__["c"])(this.actionSheets)},Object.defineProperty(e,"is",{get:function(){return"ion-action-sheet-controller"},enumerable:!0,configurable:!0}),Object.defineProperty(e,"properties",{get:function(){return{create:{method:!0},dismiss:{method:!0},doc:{context:"document"},getTop:{method:!0}}},enumerable:!0,configurable:!0}),Object.defineProperty(e,"listeners",{get:function(){return[{name:"body:ionActionSheetWillPresent",method:"actionSheetWillPresent"},{name:"body:ionActionSheetWillDismiss",method:"actionSheetWillDismiss"},{name:"body:ionActionSheetDidUnload",method:"actionSheetWillDismiss"},{name:"body:keyup.escape",method:"escapeKeyUp"}]},enumerable:!0,configurable:!0}),e}();

/***/ })

}]);
//# sourceMappingURL=4.js.map`

**Comment by lucasbasquerotto** [comment]
@samrat-bhandari In your comment you said:

> In the ion-select-option, bind to an observable array using *ngFor as mention previously

But the error is:

> Unhandled Promise rejection

Are you sure the error is in the `ion-select` with `async `(specifically)? It seems some **Promise** (not **Observable**) is created somewhere and is not handling possible errors.

**How is `ProjectsCollection` being populated?** Do you convert some observable to promise or vice-versa?

Try to create an empty observable to see what happens:

```typescript
// rxjs 6
import { empty } from "rxjs";

empty();
```

Assign the empty observable to your variable (for example, `public ProjectsCollection = empty();`), instead of calling your service to populate it to see if you get the same error.

**Comment by samrat-bhandari** [comment]
On further research I found that the issue was with the way webpack loads chucks, here is an example for your reference :

`https://github.com/webpack/webpack/issues/5264`

In our case this was happening anytime on network change, where webpack fails to load chunk because of the output path issue. 

It is mentioned in that issue and in many others that adding the following to webpack config file solves the chunk loading error :

add `publicPath: 'foo',` to output in webpack

Considering there is no webpack config file in ionic 4 project how can we resolve this issue?

**Comment by samrat-bhandari** [comment]
On further research I found that the issue was with the way webpack loads chucks, here is an example for your reference :

[Uncaught (in promise) Error: Loading chunk # failed. #7502](https://github.com/webpack/webpack/issues/7502
)
[And here as well](https://github.com/webpack/webpack/issues/5264)

In our case this was happening anytime on network change, where webpack fails to load chunk because of the output path issue. 

It is mentioned in that issue and in many others that adding the following to webpack config file solves the chunk loading error :

add `publicPath: 'foo',` to output in webpack

Considering there is no webpack config file in ionic 4 project how can we resolve this issue?

**Comment by lucasbasquerotto** [comment]
@samrat-bhandari I see that you edited the issue saying it is a webpack issue. If your app is a native ionic app (not a PWA) then the chunks should be loaded properly, even offline, otherwise it's a bug (either with webpack or with the way webpack is configured). Let's see if someone of the ionic team address this issue.

**Comment by samrat-bhandari** [comment]
@lucasbasquerott Yes the issue looks to be with how webpack is configured in ionic (not a webpack issue but issue with webpack config in ionic). And, yes the app is a PWA which is why this is a big issue because the app breaks completely on every network change because webpack cannot load the chunks after network change.

**Comment by lucasbasquerotto** [comment]
@samrat-bhandari If your app is a PWA than I assume that the chunks are loaded over the network, so the chunks that are not already loaded won't be loaded when it's offline. 

Unless they don't load even when the app comes back online, in such I case I assume this is a bug (or at least a not implemented feature).
