### ISSUE TITLE
Wrong reference to another version of the rxjs/Observable class through @ionic/ng-toolkit

### ISSUE THREAD

**Issue by tassiovale** [ionic-team/ionic#15478]
# Bug Report

**Ionic Info**

```
Ionic:

   ionic (Ionic CLI)          : 4.1.2 (/usr/local/lib/node_modules/ionic)
   Ionic Framework            : @ionic/angular 4.0.0-beta.7
   @angular-devkit/core       : 0.7.5
   @angular-devkit/schematics : 0.7.5
   @angular/cli               : 6.1.5
   @ionic/ng-toolkit          : 1.0.8
   @ionic/schematics-angular  : 1.0.6

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.1, (and 3 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/tassiovale/Library/Android/sdk)
   NodeJS            : v8.9.4 (/usr/local/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Describe the Bug**
Error when building for ios/android.
The framework makes reference to an old version of the rxjs/Observable class.

```
ng run app:ionic-cordova-build:production --platform=ios
sink._addParentTeardownLogic is not a function
TypeError: sink._addParentTeardownLogic is not a function
    at Observable.subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/rxjs/internal/Observable.js:27:18)
    at MergeMapOperator.call (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/mergeMap.js:35:23)
    at Observable.subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/rxjs/internal/Observable.js:24:22)
    at /Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/util/subscribeToObservable.js:10:20
    at Object.subscribeToResult (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/mergeMap.js:75:38)
    at MergeMapSubscriber._tryNext (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/mergeMap.js:72:14)
    at MergeMapSubscriber._next (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/Subscriber.js:64:18)
    at Observable._subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/observable/scalar.js:6:20)
    at Observable._trySubscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/Observable.js:43:25)
    at Observable.subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/Observable.js:29:22)
    at MergeMapOperator.call (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/mergeMap.js:35:23)
    at Observable.subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/Observable.js:24:22)
    at DoOperator.call (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/operators/tap.js:29:23)
    at Observable.subscribe (/Users/tassiovale/Documents/develop/15158-ui-residential-routers/Code/03.LPI/intelbras-lpi/node_modules/@ionic/ng-toolkit/node_modules/rxjs/internal/Observable.js:24:22)
[ERROR] An error occurred while running subprocess ng.
```

**Steps to Reproduce**
1. npm install
2. ionic cordova build ios --prod

**Related Code**

```js
import { Observable, throwError } from 'rxjs';
```

**Additional Context**
Dependencies:

```
"dependencies": {
    "@angular/common": "^6.1.4",
    "@angular/core": "^6.1.4",
    "@angular/forms": "^6.1.4",
    "@angular/http": "^6.1.4",
    "@angular/platform-browser": "^6.1.4",
    "@angular/platform-browser-dynamic": "^6.1.4",
    "@angular/router": "^6.1.4",
    "@ionic-native/core": "^5.0.0-beta.17",
    "@ionic-native/splash-screen": "5.0.0-beta.17",
    "@ionic-native/status-bar": "5.0.0-beta.17",
    "@ionic/angular": "^4.0.0-beta.5",
    "@ionic/ng-toolkit": "^1.0.8",
    "@ionic/schematics-angular": "^1.0.5",
    "cordova-ios": "4.5.5",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.1.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.7",
    "rxjs": "^6.3.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.7.5",
    "@angular-devkit/build-angular": "^0.7.5",
    "@angular-devkit/core": "^0.7.5",
    "@angular-devkit/schematics": "^0.7.5",
    "@angular/cli": "^6.1.5",
    "@angular/compiler": "^6.1.4",
    "@angular/compiler-cli": "^6.1.4",
    "@angular/language-service": "^6.1.4",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "^2.0.3",
    "@types/node": "^10.9.2",
    "codelyzer": "^4.4.4",
    "jasmine-core": "^3.2.1",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.2",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "^5.4.0",
    "puppeteer": "^1.7.0",
    "ts-node": "^7.0.1",
    "tslint": "^5.11.0",
    "typescript": "^2.9.2"
  },
```

**Comment by JorgeJoseAbad** [comment]
Same or similar error doing ng serve.. but with Angular 6 (updated from 5), in console:

(etc)../node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Observable.js:27
            sink._addParentTeardownLogic(this.source || (config_1.config.useDeprecatedSynchronousErrorHandling && !sink.syncErrorThrowable) ?
                 ^

TypeError: sink._addParentTeardownLogic is not a function

(resumed for clarity...)

at Observable.subscribe...
at MergeMapOperator.call..
at Object.subscribeToResult..

(and and more lines, all seem related to rxjs package, this rxjs was updated to 6.3.1, and the error arised, then downgraded to 6.2.2 but the error remain. 

node_modules deleted ad re-installed from package.json:
"dependencies": {
    "@angular/animations": "^6.1.6",
    "@angular/common": "^6.1.6",
    "@angular/compiler": "^6.1.6",
    "@angular/core": "^6.1.6",
    "@angular/forms": "^6.1.6",
    "@angular/http": "^6.1.6",
    "@angular/platform-browser": "^6.1.6",
    "@angular/platform-browser-dynamic": "^6.1.6",
    "@angular/router": "^6.1.6",
    "@ng-bootstrap/ng-bootstrap": "^3.2.0",
    "bootstrap": "^4.1.3",
    "chart.js": "^2.7.2",
    "core-js": "^2.4.1",
    "jquery": "^3.3.1",
    "ng2-charts": "^1.6.0",
    "popper.js": "^1.14.4",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.0.0-rc.0",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.7.0-rc.3",
    "@angular/cli": "6.1.5",
    "@angular/compiler-cli": "^6.1.6",
    "@angular/language-service": "^6.1.6",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.0",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.9.2"
  }

**Comment by Celtiore** [comment]
`"dependencies": {
    "@angular/common": "^6.1.7",
    "@angular/core": "^6.1.7",
    "@angular/forms": "^6.1.7",
    "@angular/http": "^6.1.7",
    "@angular/platform-browser": "^6.1.7",
    "@angular/platform-browser-dynamic": "^6.1.7",
    "@angular/router": "^6.1.7",
    "@ionic-native/core": "5.0.0-beta.15",
    "@ionic-native/splash-screen": "5.0.0-beta.15",
    "@ionic-native/status-bar": "5.0.0-beta.15",
    "@ionic/angular": "4.0.0-beta.7",
    "@ionic/pro": "2.0.3",
    "cordova-android": "7.1.1",
    "cordova-browser": "5.0.4",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-ionic": "^5.1.3",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.0.0",
    "cordova-plugin-splashscreen": "5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.3",
    "firebase": "^5.4.2",
    "moment": "^2.22.2",
    "rxjs": "6.2.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.8.0-rc.1",
    "@angular-devkit/build-angular": "^0.8.0-rc.1",
    "@angular-devkit/core": "^0.8.0-rc.1",
    "@angular-devkit/schematics": "^0.8.0-rc.1",
    "@angular/cli": "^6.1.5",
    "@angular/compiler": "^6.1.7",
    "@angular/compiler-cli": "^6.1.7",
    "@angular/language-service": "^6.1.7",
    "@ionic/ng-toolkit": "^1.0.8",
    "@ionic/schematics-angular": "^1.0.6",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.9.2",
    "codelyzer": "~4.4.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }`

`npm i --save @angular-devkit/architect@~0.8.0-rc.1 @angular-devkit/build-angular@~0.8.0-rc.1 @angular-devkit/core@~0.8.0-rc.1 @angular-devkit/schematics@~0.8.0-rc.1
`
i don't know if it's a good idea, but working with build android and build browser
