### ISSUE TITLE
(node:1056) UnhandledPromiseRejectionWarning: Unhandled promise rejection.

### ISSUE THREAD

**Issue by ericel** [ionic-team/ionic#15534]
**I get this error with ionic 4, cordova  platform android@7.1.0**

# Bug Report

> (node:1056) UnhandledPromiseRejectionWarning: Error: C:\Users\adjoi\AppData\Local\Android\sdk\platform-tools\adb.exe: Command failed with exit code 1 Error output:
> adb: failed to install E:\mobile apps\myapp\platforms\android\app\build\outputs\apk\debug\app-debug.apk:
>     at ChildProcess.whenDone (E:\mobile apps\myapp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)

**Ionic Info**

```
BUILD SUCCESSFUL in 18s
47 actionable tasks: 2 executed, 45 up-to-date
Built the following apk(s):
        E:\mobile apps\myapp\platforms\android\app\build\outputs\apk\debug\app-debug.apk
ANDROID_HOME=C:\Users\adjoi\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_181
none
Skipping build...
Built the following apk(s):
        E:\mobile apps\myapp\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Using apk: E:\mobile apps\myapp\platforms\android\app\build\outputs\apk\debug\app-debug.apk
Package name: com.myapp.money
(node:1056) UnhandledPromiseRejectionWarning: Error: C:\Users\adjoi\AppData\Local\Android\sdk\platform-tools\adb.exe: Command failed with exit code 1 Error output:
adb: failed to install E:\mobile apps\myapp\platforms\android\app\build\outputs\apk\debug\app-debug.apk:
    at ChildProcess.whenDone (E:\mobile apps\myapp\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
(node:1056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a
non-zero exit code.
```

**Describe the Bug**
I have no idea how to fix this. It happens when I do

**Steps to Reproduce**
`ionic cordova run android --device`

**Related Code**
 I am using windows 10 and the only plugins in the app are
```
cordova-android-support-gradle-release 1.4.4 "cordova-android-support-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-firebase 2.0.0 "Google Firebase Plugin"
cordova-plugin-googleplus 5.3.1 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by avo4** [comment]
Maybe this help you:
+Try to remove and then add the android platform:
  -ionic cordova platform remove/add android
+Another possible solution is changing the id "xx.name" on config.xml
+You can try also removing and adding some plugins you have already installed

**Comment by ericel** [comment]
I have tried all the above. it won't get me any where. So frustrating!

**Comment by paulstelzer** [comment]
THis is related to cordova / Android Studio, not Ionic. If you need help use the forum
