### ISSUE TITLE
[Core/beta.12] ion-router not working with Firefox in prod mode

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic#15829]
# Bug Report

```
"@ionic/core": "4.0.0-beta.12",
"@stencil/core": "0.13.2"
Firefox 62 - Ubuntu
Chrome 69 - Ubuntu
```

**Describe the Bug**
When compiled in `prod` mode, `<ion-router/>` does nothing in Firefox. Clicking on the _Profile Page_ button from the PWA starter does not trigger navigation

**Steps to Reproduce**

$ npx create-stencil ionic-pwa
...
$ npm run build

Open the app in Chome and Firefox :

- in Chrome, clicking on the _Profile Page_ button does open the new page, the router handles the call ;
- in Firefox, clicking on the button once does nothing, clicking a second time opens an 404 _*/profile/ionic_

**Additional Context**

There's a NGINX reverse proxy with configured:
```yaml
location / {
    alias /var/www/html/test/;
}
```

**Comment by manucorporat** [comment]
Looks like it's an issue in stencil, already fixed in master https://github.com/ionic-team/stencil/commit/8f17c32bc80060bb2f8baf90a60e0ad56ea9913c

Next version will have it fixed! Thanks

**Comment by kael** [comment]
Thanks for the quick reply.

Seems something's not working when testing on that commit version:

```json
  "dependencies": {
    "@ionic/core": "4.0.0-beta.12",
    "@stencil/core": "https://github.com/ionic-team/stencil#8f17c32"
  },
```
```json
    "@stencil/core": {
      "version": "git+https://github.com/ionic-team/stencil.git#8f17c32bc80060bb2f8baf90a60e0ad56ea9913c",
      "from": "git+https://github.com/ionic-team/stencil.git#8f17c32",
      "requires": {
        "chokidar": "2.0.3",
        "jsdom": "11.11.0",
        "typescript": "~2.9.1"
      }
    },
```


```bash
$ npm run build

> @ionic/pwa-toolkit@0.0.1 build /home/kael/dev/test-router
> stencil build

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../dist/cli/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/kael/dev/test-router/node_modules/@stencil/core/bin/stencil:4:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ionic/pwa-toolkit@0.0.1 build: `stencil build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ionic/pwa-toolkit@0.0.1 build script.
```

Node v10.11.0
NPM 6.4.1

(Tested twice, with `rm -rf  node_modules/`).

**Comment by kael** [comment]
Any update ? Are you able to reproduce that compilation bug ?
