### ISSUE TITLE
An error occurred while running subprocess cordova

### ISSUE THREAD

**Issue by baljeetkalsi** [ionic-team/ionic#15902]
**C:\IonicApp\LIMSApp>ionic cordova platform add andriod**
> cordova platform add andriod --save
Using cordova-fetch for andriod
Failed to fetch platform andriod
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not Found: andriod@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-10-09T13_46_01_190Z-debug.log
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add andriod --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**C:\IonicApp\LIMSApp>ionic cordova platform add android@latest**
> cordova platform add android@latest --save
Using cordova-fetch for cordova-android@latest
Platform android already added.
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add android@latest --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**C:\IonicApp\LIMSApp>ionic cordova platform add android@latest --verbose**

  ionic:cli-utils Terminal info: { tty: true, ci: false } +0ms
  ionic:cli-utils CLI global options: { _: [ 'cordova', 'platform', 'add', 'android@latest' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +0ms
  ionic:cli-utils:lib:project Project type from config: Ionic Angular 3 (ionic-angular) +0ms
  ionic:cli-utils Project name: undefined +227ms
  ionic:cli Context: { binPath: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ionic\\bin\\ionic', libPath: 'C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\ionic', execPath: 'C:\\IonicApp\\LIMSApp', version: '4.1.2' } +0ms
  ionic:cli-utils:lib:integrations:cordova:config Using config.xml: C:\IonicApp\LIMSApp\config.xml +0ms
> cordova platform add android@latest --verbose --save
No scripts found for hook "before_platform_add".
Using cordova-fetch for cordova-android@latest
saving exact
Running command: cmd "/s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-android@latest --production --save-exact""
Command finished with error code 0: cmd /s /c ""C:\Program Files\nodejs\npm.cmd" install cordova-android@latest --production --save-exact"
Removing "cordova-" prefix from cordova-android
Platform android already added.
CordovaError: Platform android already added.
    at C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\cordova-lib\src\cordova\platform\addHelper.js:145:35
    at _fulfilled (C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:854:54)
    at C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:816:13)
    at C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\IonicApp\LIMSApp\node_modules\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add android@latest --verbose --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
  ionic:cli-framework:utils:process onBeforeExit handler: process.exit received +0ms
  ionic:cli-framework:utils:process onBeforeExit handler: running 1 queued functions +16ms
  ionic:cli-framework:utils:process error while killing process tree for 9476: { Error: Command failed: taskkill /pid 9476 /T /F
  ionic:cli-framework:utils:process ERROR: The process "9476" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:276:12)
  ionic:cli-framework:utils:process     at emitTwo (events.js:126:13)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:214:7)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:915:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 9476 /T /F' } +133ms
  ionic:cli-framework:utils:process Error from function 0 in exit queue: { Error: Command failed: taskkill /pid 9476 /T /F
  ionic:cli-framework:utils:process ERROR: The process "9476" not found.
  ionic:cli-framework:utils:process
  ionic:cli-framework:utils:process     at ChildProcess.exithandler (child_process.js:276:12)
  ionic:cli-framework:utils:process     at emitTwo (events.js:126:13)
  ionic:cli-framework:utils:process     at ChildProcess.emit (events.js:214:7)
  ionic:cli-framework:utils:process     at maybeClose (internal/child_process.js:915:16)
  ionic:cli-framework:utils:process     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  ionic:cli-framework:utils:process   killed: false,
  ionic:cli-framework:utils:process   code: 128,
  ionic:cli-framework:utils:process   signal: null,
  ionic:cli-framework:utils:process   cmd: 'taskkill /pid 9476 /T /F' } +3ms
  ionic:cli-framework:utils:process onBeforeExit handler: exiting (exit code 1) +2ms

Please can any one tell me what is the problem it is really frustration. 
I an uninstall and install  Cordova , andriod and all other packages 10 times . 
But noting is working.

**Comment by mwq27** [comment]
This happens on `ionic cordova build` and `ionic cordova run` commands for me as well.  It started when I moved to ionic 4.2.1

**Comment by francovp** [comment]
I don't get why this doesn't get ANY ATTENTION AT ALL from the devs.
I receive this error since I updated to Ionic CLI 4.2.1, I can't use the livereload feature because of this :/

I'm getting this error on all "ionic cordova ..." commands:
ionic cordova run android
ionic cordova build ios
ionic cordova platform add
etc

My ionic info:

```
Ionic:

   ionic (Ionic CLI)  : 4.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 7.1.1, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 2.2.0, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/francovalerio/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.2 (/usr/local/bin/node)
   npm               : 6.4.0
   OS                : macOS
   Xcode             : Xcode 9.4.1 Build version 9F2000
```

**Comment by mwq27** [comment]
So for me, the problem was occurring during plugin installation.  It was so hard to find because the log that said "Failed to fetch plugin ...." was buried with a ton of other logs, and doesn't look like an error at all.  Once I fixed the plugin install issue, everything was working fine.
