### ISSUE TITLE
BarcoderScanner: Metadata version mismatch for module , found version 4, expected 3

### ISSUE THREAD

**Issue by dtgfranca** [ionic-team/ionic#16314]
# Bug Report

**Ionic Info**
Run `ionic info` from a terminal/cmd prompt and paste the output below.

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.3
    ionic (Ionic CLI) : 3.20.1

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.2.3 browser 5.0.3
    Ionic Framework    : ionic-angular 3.3.0

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.4
    npm               : 5.6.0
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /opt/android-sdk-linux

Misc:

    backend : pro

```

**Describe the Bug**
When I run 
`ionic cordova build android --prod --release`
I get the following error:

> Running app-scripts build: --prod --platform android --target cordova
> [17:12:45]  build prod started ...
> [17:12:45]  clean started ...
> [17:12:45]  clean finished in 3 ms
> [17:12:45]  copy started ...
> [17:12:46]  deeplinks started ...
> [17:12:47]  deeplinks finished in 1.17 s
> [17:12:47]  ngc started ...
> Error: Metadata version mismatch for module /var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@ionic-native/barcode-scanner/index.d.ts, found version 4, expected 3
>     at StaticSymbolResolver.getModuleMetadata (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:25616:34)
>     at StaticSymbolResolver._createSymbolsOf (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:25404:46)
>     at StaticSymbolResolver.getSymbolsOf (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:25385:14)
>     at /var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
>     at Array.forEach (<anonymous>)
>     at extractProgramSymbols (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:24240:79)
>     at AotCompiler.analyzeModulesAsync (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler/bundles/compiler.umd.js:23796:47)
>     at CodeGenerator.codegen (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
>     at Function.NgTools_InternalApi_NG_2.codeGen (/var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
>     at /var/www/html/autoatendimento_mobile/atm_develop/autoatendimento_frontend/node_modules/@ionic/app-scripts/dist/aot/aot-compiler.js:182:73
> [17:12:54]  copy finished in 8.84 s
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ionic-hello-world@1.0.0 build:release: ` gulp release`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ionic-hello-world@1.0.0 build:release script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-11-13T19_12_55_544Z-debug.log
> 

**Steps to Reproduce**
1. Execute `ionic cordova build android --prod --release`

**Related Code**
I'm trying to build on Android

**Expected Behavior**
Generate apk

**Comment by dtgfranca** [comment]
I did downgrade plugin BarcoderScanner from 4.17.0 to 4.3.3.
For me is resolved
