### ISSUE TITLE
Error: StaticInjectorError[n -> l]: StaticInjectorError(Platform: core)[n -> l]: NullInjectorError: No provider for l!

### ISSUE THREAD

**Issue by mingmLiang** [ionic-team/ionic#17672]
# Bug Report

**Ionic version:**

[x] **4.10.3**

**Current behavior:**

 I am getting the following error after run in  Android.
Error: Uncaught (in promise): Error: StaticInjectorError[n -> l]: 
  StaticInjectorError(Platform: core)[n -> l]: 
    NullInjectorError: No provider for l!
Error: StaticInjectorError[n -> l]: 
  StaticInjectorError(Platform: core)[n -> l]: 
    NullInjectorError: No provider for l!
    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:29350)
    at http://localhost/main.5fd6ac662e1feac5f89e.js:1:31619
    at t (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32024)
    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32175)
    at http://localhost/main.5fd6ac662e1feac5f89e.js:1:31619
    at t (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32024)
    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32175)
    at Hu (http://localhost/main.5fd6ac662e1feac5f89e.js:1:99687)
    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:110604)
    at Hu (http://localhost/main.5fd6ac662e1feac5f89e.js:1:99687)message: "Uncaught (in promise): Error: StaticInjectorError[n -> l]: ↵  StaticInjectorError(Platform: core)[n -> l]: ↵    NullInjectorError: No provider for l!↵Error: StaticInjectorError[n -> l]: ↵  StaticInjectorError(Platform: core)[n -> l]: ↵    NullInjectorError: No provider for l!↵    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:29350)↵    at http://localhost/main.5fd6ac662e1feac5f89e.js:1:31619↵    at t (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32024)↵    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32175)↵    at http://localhost/main.5fd6ac662e1feac5f89e.js:1:31619↵    at t (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32024)↵    at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:32175)↵    at Hu (http://localhost/main.5fd6ac662e1feac5f89e.js:1:99687)  at t.get (http://localhost/main.5fd6ac662e1feac5f89e.js:1:110604)   at Hu (http://localhost/main.5fd6ac662e1feac5f89e.js:1:99687)"promise: erejection: Error: StaticInjectorError[n -> l]: 
  StaticInjectorError(Platform: core)[n -> l]: 
    NullInjectorError: No provider for l!stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }task: ezone: e__proto__: d

I use qr-scanner following 'https://ionicframework.com/docs/native/qr-scanner'.
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
Ionic:

   ionic (Ionic CLI)             : 4.10.3 (C:\Users\mingming\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 6 other plugins)

System:

   NodeJS : v8.11.3 (D:\Program Files\nodejs\node.exe)
   npm    : 6.8.0
   OS     : Windows 10

```

**Other information:**

My code is in 'https://github.com/mingmLiang/ionic4-base-app'.
**Ionic info:**

```
insert the output from ionic info here
```

**Comment by liamdebeasi** [comment]
Hi @mingmLiang,

Thanks for the issue. You need to add the QR scanner plugin to your `app.module.ts` file: 

```
import { QRScanner } from '@ionic-native/qr-scanner/ngx';
```

After that, you should declare it in your providers:

```
  providers: [
    ...
    QRScanner
    ...
  ]
```

Can you confirm whether or not this fixes your issue? Thanks!

**Comment by mingmLiang** [comment]
I had fixed it. Thank you very much.
