### ISSUE TITLE
bug: Ionic build fails on project creation in node v12

### ISSUE THREAD

**Issue by velansalis** [ionic-team/ionic#18166]
I have `node v12` installed in my system. When i try creating a project from `ionic-cli` using `ionic start greenlink tabs` the prompt eventually falls down to something like this
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node":

HTTP error 404 Not Found
.
.
.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/velansalis/code/greenlink/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/home/velansalis/.nvm/versions/node/v12.0.0/bin/node" "/home/velansalis/code/greenlink/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/velansalis/code/greenlink/node_modules/node-sass
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
This seems to be an issue with `node v12` trying to get unsupported version of `node-sass`. Please fix this issue.

**Comment by liamdebeasi** [comment]
Hi there,

Thanks for the issue! We are aware of this and are working on migrating off `node-sass` and on to `sass` to prevent future instances like this.

Thanks!

**Comment by liamdebeasi** [comment]
Hi there,

After some investigation, we've determined that the package causing the installation to fail on Node 12 is not one of our packages. Additionally, the developer has not provided an updated package so we are unable to resolve this automatically.

For now, you can manually install the updated version of node-sass using `npm i node-sass@latest`.

Thanks for using Ionic!
