### ISSUE TITLE
bug: ionic depending on non-direct dependencies

### ISSUE THREAD

**Issue by beenotung** [ionic-team/ionic#18302]
# Bug Report

**Ionic version:**

[x] **4.12.0**

**Current behavior:**

The packages depends on non-direct dependencies.

**Expected behavior:**

The packages should only depends on explicitly depended packages.

**Steps to reproduce:**

```bash
npm i -g pnpm
pnpm i -g ionic
ionic start demo-ionic --no-deps
# select blank template
cd demo-ionic
pnpm i
npm run build
```
**Errors in console:**
```

> demo-ionic@0.0.1 build /home/beenotung/workspace/local/demo-ionic
> ng build

                                                                                                 
Date: 2019-05-18T10:10:59.544Z
Hash: c167e566f09c31ab0622
Time: 4911ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 368 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 633 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 119 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 22.4 kB [initial] [rendered]

ERROR in ./src/global.scss (./node_modules/.registry.npmjs.org/@angular-devkit/build-angular/0.13.9/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/.registry.npmjs.org/postcss-loader/3.0.0/node_modules/postcss-loader/src??embedded!./node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
Module build failed (from ./node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (/home/beenotung/workspace/local/demo-ionic/node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./src/theme/variables.scss (./node_modules/.registry.npmjs.org/@angular-devkit/build-angular/0.13.9/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/.registry.npmjs.org/postcss-loader/3.0.0/node_modules/postcss-loader/src??embedded!./node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
Module build failed (from ./node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.sassLoader (/home/beenotung/workspace/local/demo-ionic/node_modules/.registry.npmjs.org/sass-loader/7.1.0_webpack@4.29.0/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in node_modules/@ionic-native/core/decorators/common.d.ts(1,23): error TS2688: Cannot find type definition file for 'cordova'.
node_modules/@ionic/angular/dist/directives/navigation/router-link-delegate.d.ts(4,33): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/directives/navigation/stack-utils.d.ts(3,47): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/directives/proxies.d.ts(2,48): error TS2304: Cannot find name 'StencilElementInterfaces'.
node_modules/@ionic/angular/dist/directives/proxies.d.ts(2,76): error TS2304: Cannot find name 'StencilElementInterfaces'.
node_modules/@ionic/angular/dist/directives/virtual-scroll/virtual-scroll.d.ts(2,40): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/ionic-module.d.ts(2,29): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/action-sheet-controller.d.ts(1,36): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/action-sheet-controller.d.ts(3,94): error TS2304: Cannot find name 'HTMLIonActionSheetElement'.
node_modules/@ionic/angular/dist/providers/alert-controller.d.ts(1,30): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/alert-controller.d.ts(3,82): error TS2304: Cannot find name 'HTMLIonAlertElement'.
node_modules/@ionic/angular/dist/providers/angular-delegate.d.ts(2,35): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/config.d.ts(2,29): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/loading-controller.d.ts(1,32): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/loading-controller.d.ts(3,86): error TS2304: Cannot find name 'HTMLIonLoadingElement'.
node_modules/@ionic/angular/dist/providers/menu-controller.d.ts(33,61): error TS2304: Cannot find name 'HTMLIonMenuElement'.
node_modules/@ionic/angular/dist/providers/menu-controller.d.ts(40,66): error TS2304: Cannot find name 'HTMLIonMenuElement'.
node_modules/@ionic/angular/dist/providers/menu-controller.d.ts(61,35): error TS2304: Cannot find name 'HTMLIonMenuElement'.
node_modules/@ionic/angular/dist/providers/menu-controller.d.ts(65,24): error TS2304: Cannot find name 'HTMLIonMenuElement'.
node_modules/@ionic/angular/dist/providers/menu-controller.d.ts(69,25): error TS2304: Cannot find name 'HTMLIonMenuElement'.
node_modules/@ionic/angular/dist/providers/modal-controller.d.ts(2,30): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/modal-controller.d.ts(5,82): error TS2304: Cannot find name 'HTMLIonModalElement'.
node_modules/@ionic/angular/dist/providers/modal-controller.d.ts(10,41): error TS2304: Cannot find name 'HTMLIonModalElement'.
node_modules/@ionic/angular/dist/providers/nav-controller.d.ts(3,33): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/picker-controller.d.ts(1,31): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/picker-controller.d.ts(3,84): error TS2304: Cannot find name 'HTMLIonPickerElement'.
node_modules/@ionic/angular/dist/providers/platform.d.ts(1,50): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/popover-controller.d.ts(2,32): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/popover-controller.d.ts(5,86): error TS2304: Cannot find name 'HTMLIonPopoverElement'.
node_modules/@ionic/angular/dist/providers/popover-controller.d.ts(10,43): error TS2304: Cannot find name 'HTMLIonPopoverElement'.
node_modules/@ionic/angular/dist/providers/toast-controller.d.ts(1,30): error TS2307: Cannot find module '@ionic/core'.
node_modules/@ionic/angular/dist/providers/toast-controller.d.ts(3,82): error TS2304: Cannot find name 'HTMLIonToastElement'.
2m
 ERROR  Command failed with exit code 1.

```

**Other information:**

Related discussions:
- https://github.com/pnpm/pnpm/issues/827

Workaround:
After `pnpm i`, run `npm i` and `pnpm i` will fix the dependency issue (hence no error when run npm run build).

I think package.json of ionic package(s) can be improved to make it compatible with pnpm's philosophy:
> A package is accessible only when it is a dependency. So B will only be accessible from C, if it will be some kind of a dependency of B. -by @zkochan

**Ionic info:**

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/home/beenotung/.nvm/versions/node/v8.12.0/pnpm-global/2/node_modules/.registry.npmjs.org/ionic/4.12.0/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

System:

   NodeJS : v8.12.0 (/home/beenotung/.nvm/versions/node/v8.12.0/bin/node)
   npm    : 6.9.0
   OS     : Linux 5.0

```

**Comment by beenotung** [comment]
It works if running `npm i` after `pnpm i` is because pnpm will not de-flatten the node_modules if the pnpm lock file is already there.

**Comment by paulstelzer** [comment]
Thanks for your issue! Can you explain what is wrong with the dependencies?
