### ISSUE TITLE
bug: Android build always issues - Execution failed for task ':app:fabricGenerateResourcesDebug'. > Crashlytics Developer Tools error.

### ISSUE THREAD

**Issue by REPTILEHAUS** [ionic-team/ionic#18596]
Constant problems trying to build for android first issue in encountered was this one related to aapt2 

https://github.com/ionic-team/ionic/issues/18591

I believe the solution to this that most suggest is to update to the latest version of gradle which I have done [see below for gradle version] this then led me onto the main issue below which is related to crashlytics API credentials - my app does not and never has used crashlytics so Im not sure why I need an API key for it, is this a new thing in ionic 4 ?

```
 gradle -v

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.14.5 x86_64
```

```
* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.
```

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0
   Ionic Framework               : @ionic/angular 4.5.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 11 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/username/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v8.15.1 (/usr/local/Cellar/node@8/8.15.1/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

```
ionic cordova build android --verbose
  ionic:bootstrap local CLI 4.12.0 found at /Applications/MAMP/htdocs/Apps/projectName/app/node_modules/ionic/package.json +0ms
  ionic:lib Terminal info: { tty: true, ci: false, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'cordova', 'build', 'android' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +1ms
  ionic:lib:project Project type from config: @ionic/angular (angular) +0ms
  ionic:lib:project Project details: { configPath: '/Applications/MAMP/htdocs/Apps/projectName/app/ionic.config.json', errors: [], context: 'app', type: 'angular' } +0ms
  ionic Context: { binPath: '/Applications/MAMP/htdocs/Apps/projectName/app/node_modules/ionic/bin/ionic', libPath: '/Applications/MAMP/htdocs/Apps/projectName/app/node_modules/ionic', execPath: '/Applications/MAMP/htdocs/Apps/projectName/app', version: '4.12.0' } +0ms
  ionic:lib:integrations:cordova:config Using config.xml: /Applications/MAMP/htdocs/Apps/projectName/app/config.xml +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic cordova build' [ 'android', '--verbose', '--interactive', '--color' ] +0ms
  ionic:lib:hooks Looking for ionic:build:before npm script. +0ms
  ionic:lib:build Looking for ionic:build npm script. +0ms
> ng run app:ionic-cordova-build --platform=android
                                                                                                                        
Date: 2019-06-22T15:00:55.953Z
Hash: d33f256c43e45bc8b3a7
Time: 33773ms
chunk {0} 0.js, 0.js.map () 16.4 kB  [rendered]
chunk {1} 1.js, 1.js.map () 12.9 kB  [rendered]
chunk {2} 2.js, 2.js.map () 17.3 kB  [rendered]
chunk {3} 3.js, 3.js.map () 5.48 kB  [rendered]
chunk {4} 4.js, 4.js.map () 1.4 kB  [rendered]
chunk {5} 5.js, 5.js.map () 1.45 kB  [rendered]
chunk {6} 6.js, 6.js.map () 3.22 kB  [rendered]
chunk {7} 7.js, 7.js.map () 1000 bytes  [rendered]
chunk {8} 8.js, 8.js.map () 1.73 kB  [rendered]
chunk {9} 9.js, 9.js.map () 93.8 kB  [rendered]
chunk {10} 10.js, 10.js.map () 31.4 kB  [rendered]
chunk {11} 11.js, 11.js.map () 33 kB  [rendered]
chunk {12} 12.js, 12.js.map () 25.7 kB  [rendered]
chunk {13} 13.js, 13.js.map () 26.6 kB  [rendered]
chunk {14} 14.js, 14.js.map () 24.7 kB  [rendered]
chunk {15} 15.js, 15.js.map () 26.1 kB  [rendered]
chunk {16} 16.js, 16.js.map () 23.9 kB  [rendered]
chunk {17} 17.js, 17.js.map () 23.9 kB  [rendered]
chunk {18} 18.js, 18.js.map () 32.5 kB  [rendered]
chunk {19} 19.js, 19.js.map () 33.6 kB  [rendered]
chunk {20} 20.js, 20.js.map () 33.7 kB  [rendered]

... [Shortened for brevity]

chunk {168} 168.js, 168.js.map () 14.6 kB  [rendered]
chunk {169} 169.js, 169.js.map () 7.92 kB  [rendered]
chunk {170} 170.js, 170.js.map () 1.63 kB  [rendered]
chunk {171} 171.js, 171.js.map () 1.36 kB  [rendered]
chunk {172} 172.js, 172.js.map () 5.03 kB  [rendered]
chunk {authentication-authentication-module} authentication-authentication-module.js, authentication-authentication-module.js.map (authentication-authentication-module) 9.93 kB  [rendered]
chunk {common} common.js, common.js.map (common) 26.1 kB  [rendered]
chunk {conversation-conversation-module} conversation-conversation-module.js, conversation-conversation-module.js.map (conversation-conversation-module) 95 kB  [rendered]
chunk {cordova} cordova.js, cordova.js.map (cordova) 62.4 kB [entry] [rendered]
chunk {create-create-module} create-create-module.js, create-create-module.js.map (create-create-module) 8.12 kB  [rendered]
chunk {dashboard-dashboard-module} dashboard-dashboard-module.js, dashboard-dashboard-module.js.map (dashboard-dashboard-module) 26.8 kB  [rendered]
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 285 kB [initial] [rendered]
chunk {event-event-module} event-event-module.js, event-event-module.js.map (event-event-module) 43.4 kB  [rendered]
chunk {events-events-module} events-events-module.js, events-events-module.js.map (events-events-module) 8.8 kB  [rendered]
chunk {home-home-module} home-home-module.js, home-home-module.js.map (home-home-module) 44 kB  [rendered]
chunk {interests-interests-module} interests-interests-module.js, interests-interests-module.js.map (interests-interests-module) 18.4 kB  [rendered]
chunk {login-login-module} login-login-module.js, login-login-module.js.map (login-login-module) 17.8 kB  [rendered]
chunk {main} main.js, main.js.map (main) 457 kB [initial] [rendered]
chunk {messages-messages-module} messages-messages-module.js, messages-messages-module.js.map (messages-messages-module) 14.7 kB  [rendered]
chunk {pages-secondary-account-settings-account-settings-module} pages-secondary-account-settings-account-settings-module.js, pages-secondary-account-settings-account-settings-module.js.map (pages-secondary-account-settings-account-settings-module) 28.3 kB  [rendered]
chunk {password-reset-password-reset-module} password-reset-password-reset-module.js, password-reset-password-reset-module.js.map (password-reset-password-reset-module) 12.6 kB  [rendered]
chunk {personal-info-personal-info-module} personal-info-personal-info-module.js, personal-info-personal-info-module.js.map (personal-info-personal-info-module) 7.89 kB  [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 242 kB [initial] [rendered]
chunk {reg-step1-reg-step1-module} reg-step1-reg-step1-module.js, reg-step1-reg-step1-module.js.map (reg-step1-reg-step1-module) 11.8 kB  [rendered]
chunk {reg-step2-reg-step2-module} reg-step2-reg-step2-module.js, reg-step2-reg-step2-module.js.map (reg-step2-reg-step2-module) 11.5 kB  [rendered]
chunk {reg-step3-reg-step3-module} reg-step3-reg-step3-module.js, reg-step3-reg-step3-module.js.map (reg-step3-reg-step3-module) 17.9 kB  [rendered]
chunk {reg-step4-reg-step4-module} reg-step4-reg-step4-module.js, reg-step4-reg-step4-module.js.map (reg-step4-reg-step4-module) 12.1 kB  [rendered]
chunk {reg-step5-reg-step5-module} reg-step5-reg-step5-module.js, reg-step5-reg-step5-module.js.map (reg-step5-reg-step5-module) 8.28 kB  [rendered]
chunk {registration-registration-module} registration-registration-module.js, registration-registration-module.js.map (registration-registration-module) 6.14 kB  [rendered]
chunk {request-fullname-request-fullname-module} request-fullname-request-fullname-module.js, request-fullname-request-fullname-module.js.map (request-fullname-request-fullname-module) 15.8 kB  [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 10.3 kB [entry] [rendered]
chunk {step1-step1-module} step1-step1-module.js, step1-step1-module.js.map (step1-step1-module) 10.5 kB  [rendered]
chunk {step2-step2-module} step2-step2-module.js, step2-step2-module.js.map (step2-step2-module) 11.2 kB  [rendered]
chunk {step3-step3-module} step3-step3-module.js, step3-step3-module.js.map (step3-step3-module) 12.9 kB  [rendered]
chunk {step4-step4-module} step4-step4-module.js, step4-step4-module.js.map (step4-step4-module) 10.9 kB  [rendered]
chunk {step5-step5-module} step5-step5-module.js, step5-step5-module.js.map (step5-step5-module) 10.7 kB  [rendered]
chunk {step6-step6-module} step6-step6-module.js, step6-step6-module.js.map (step6-step6-module) 16.5 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 111 kB [initial] [rendered]
chunk {tabs-tabs-module} tabs-tabs-module.js, tabs-tabs-module.js.map (tabs-tabs-module) 8.94 kB  [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 8.32 MB [initial] [rendered]
  ionic:lib:hooks Looking for ionic:build:after npm script. +38s
> cordova build android --verbose
Executing script found in plugin cordova-android-support-gradle-release for hook "before_build": plugins/cordova-android-support-gradle-release/scripts/apply-changes.js
cordova-android-support-gradle-release: Android platform: V7+
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
PlatformApi successfully found for platform android
Checking config.xml for saved plugins that haven't been added to the project
Checking for any plugins added to the project that have not been installed in android platform
No differences found between plugins added to project and installed in android platform. Continuing...
Generating platform-specific config.xml from defaults for android at /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/app/src/main/res/xml/config.xml
Merging project's config.xml into platform-specific android config.xml
[Gradle Properties] Preparing Configuration
[Gradle Properties] Appending default configuration properties
[Gradle Properties] Appending custom configuration properties
[Gradle Properties] Updating and Saving File
Merging and updating files from [www, platforms/android/platform_www] to platforms/android/app/src/main/assets/www
  
... [Shortened for brevity]  
  
Prepared android project successfully
Executing script found in plugin cordova-android-support-gradle-release for hook "after_prepare": plugins/cordova-android-support-gradle-release/scripts/apply-changes.js
cordova-android-support-gradle-release: Android platform: V7+
Executing script found in plugin cordova-plugin-firebase for hook "after_prepare": plugins/cordova-plugin-firebase/scripts/after_prepare.js
Preparing Firebase on Android
Executing script found in plugin parse-push-plugin for hook "after_prepare": plugins/parse-push-plugin/scripts/afterAndroidPrepare.js
No scripts found for hook "before_compile".
Running command: /usr/libexec/java_home 
Command finished with error code 0: /usr/libexec/java_home 
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=/Users/username/Library/Android/sdk (recommended setting)
ANDROID_HOME=/Users/username/Library/Android/sdk (DEPRECATED)
Running command: /usr/local/Cellar/gradle/5.4.1/bin/gradle -p /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android wrapper -b /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/wrapper.gradle
> Task :wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Command finished with error code 0: /usr/local/Cellar/gradle/5.4.1/bin/gradle -p,/Applications/MAMP/htdocs/Apps/projectName/app/platforms/android,wrapper,-b,/Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/wrapper.gradle
Subproject Path: CordovaLib
Subproject Path: app
Running command: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/gradlew cdvBuildDebug -b /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/build.gradle

> Configure project :app
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 27.+
+-----------------------------------------------------------------
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: API 'variant.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getAssemble(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessManifest()' is obsolete and has been replaced with 'variantOutput.getProcessManifestProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessManifest(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageApplication(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
... [Shortened for brevity]

> Task :CordovaLib:compileDebugJavaWithJavac
Note: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :CordovaLib:processDebugJavaRes NO-SOURCE
... [Shortened for brevity]

> Task :app:processDebugManifest
/Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/app/src/main/AndroidManifest.xml:24:9-31:50 Warning:
	activity#com.google.firebase.auth.internal.FederatedSignInActivity@android:launchMode was tagged at AndroidManifest.xml:24 to replace other declarations but no other declaration present

> Task :app:fabricGenerateResourcesDebug FAILED
ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.
	at com.crashlytics.tools.android.DeveloperTools.processApiKey(DeveloperTools.java:375)
... [Shortened for brevity]
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
27 actionable tasks: 27 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Command finished with error code 1: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/gradlew cdvBuildDebug,-b,/Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/build.gradle
/Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Error: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /Applications/MAMP/htdocs/Apps/projectName/app/platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:fabricGenerateResourcesDebug'.
> Crashlytics Developer Tools error.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
    at ChildProcess.whenDone (/Applications/MAMP/htdocs/Apps/projectName/app/node_modules/cordova-common/src/superspawn.js:135:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build android --verbose exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: process.exit received +0ms
  ionic:utils-process onBeforeExit handler: running 2 functions +0ms
  ionic:utils-process onBeforeExit handler: exiting (exit code 1) +23ms
```

Plugins in use by the app are 

```
cordova-plugin-device/
cordova-plugin-ionic-webview/
com.telerik.plugins.nativepagetransitions/ 
cordova-plugin-file/
cordova-plugin-splashscreen/
parse-push-plugin/
cordova-android-support-gradle-release/
cordova-plugin-firebase/
cordova-plugin-statusbar/
cordova-plugin-advanced-http/
cordova-plugin-inappbrowser/
cordova-plugin-whitelist/
cordova-plugin-app-version/
cordova-plugin-ionic-keyboard/
```

**Comment by liamdebeasi** [comment]
Thanks for the issue! This Fabric/Crashlytics error is not related to anything that Ionic manages, so I am going to close this as this is more of a support question.

For further help with this issue, I recommend you post on our [forum](https://forum.ionicframework.com) or our [slack](https://ionicworldwide.herokuapp.com/).

Thanks for using Ionic!
