### ISSUE TITLE
bug: Crash on ionic native HTTP request with fresh install

### ISSUE THREAD

**Issue by Xstoudi** [ionic-team/ionic#18669]
# Bug Report

**Ionic version:**

[x] **4.6**

**Current behavior:**

The app crash on http request.

**Expected behavior:**

The app should not crash.

**Steps to reproduce:**

Simply start a new app, follow the native http installation from the doc and try to do an http request while using `ionic serve --devapp`.

**Related code:**
```
this.http.post('http://192.168.1.156:3333/register', registerData, {})
      .then(response => console.log(response))
      .catch(err => console.error(err))
```

**Other information:**
My main problem is that every single post on the internet about this issue is related to an other plugin, but I'm on a fresh install without any specific dependency. 
That what comes into the logs from `adb logcat *:E` :
```
06-30 00:02:11.857  1262  2400 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-15
06-30 00:02:11.857  1262  2400 E AndroidRuntime: Process: io.ionic.devapp, PID: 1262
06-30 00:02:11.857  1262  2400 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in base.apk)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at okhttp3.internal.huc.OkHttpURLConnection.buildCall(OkHttpURLConnection.java:373)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at okhttp3.internal.huc.OkHttpURLConnection.getOutputStream(OkHttpURLConnection.java:260)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.openOutput(HttpRequest.java:2902)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3325)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3285)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3350)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3255)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.synconset.cordovahttp.CordovaHttp.prepareRequestBody(CordovaHttp.java:239)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at com.synconset.cordovahttp.CordovaHttpPost.run(CordovaHttpPost.java:30)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-30 00:02:11.857  1262  2400 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-4
06-30 00:07:58.958  2755  2937 E AndroidRuntime: Process: io.ionic.devapp, PID: 2755
06-30 00:07:58.958  2755  2937 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getHttpUrlChecked(Ljava/lang/String;)Lokhttp3/HttpUrl; in class Lokhttp3/internal/Internal; or its super classes (declaration of 'okhttp3.internal.Internal' appears in base.apk)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at okhttp3.internal.huc.OkHttpURLConnection.buildCall(OkHttpURLConnection.java:373)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at okhttp3.internal.huc.OkHttpURLConnection.getOutputStream(OkHttpURLConnection.java:260)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.openOutput(HttpRequest.java:2902)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3325)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3285)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3350)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.github.kevinsawicki.http.HttpRequest.form(HttpRequest.java:3255)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.synconset.cordovahttp.CordovaHttp.prepareRequestBody(CordovaHttp.java:239)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at com.synconset.cordovahttp.CordovaHttpPost.run(CordovaHttpPost.java:30)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-30 00:07:58.958  2755  2937 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-30 00:07:58.960   492   492 E SELinux : avc:  denied  { find } for service=opdiagnose pid=2755 uid=10165 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
06-30 00:07:58.961   492   492 E SELinux : avc:  denied  { find } for service=opdiagnose pid=2755 uid=10165 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
06-30 00:07:59.094  2528  3506 E SensorManager: unregisterListenerImpl callingApp: android.uid.system:1000,callingPid:2528,callingUid:1000
06-30 00:07:59.239  2528  2638 E libprocessgroup: Error encountered killing process cgroup uid 99317 pid 2795: No such file or directory
```

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 5.2.1 (/home/xavier/.nvm/versions/node/v11.10.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 6 other plugins)

Utility:

   cordova-res : 0.5.1 
   native-run  : 0.2.7 

System:

   Android SDK Tools : 26.1.1 (/home/xavier/Android/Sdk)
   NodeJS            : v11.10.0 (/home/xavier/.nvm/versions/node/v11.10.0/bin/node)
   npm               : 6.7.0
   OS                : Linux 4.18
```

**Comment by Xstoudi** [comment]
Oh, I forgot to show the plugins I have installed:
```
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by Xstoudi** [comment]
Moreover, here is `grep -rnw '.' -e 'okhttp'`:
```
./platforms/android/app/build.gradle:270:    implementation "com.squareup.okhttp3:okhttp-urlconnection:3.10.0"
./platforms/android/project.properties:15:cordova.system.library.2=com.squareup.okhttp3:okhttp-urlconnection:3.10.0
./plugins/cordova-plugin-advanced-http/plugin.xml:81:    <framework src="com.squareup.okhttp3:okhttp-urlconnection:$OKHTTP_VERSION"/>
./node_modules/cordova-android/RELEASENOTES.md:463:* [CB-6630](https://issues.apache.org/jira/browse/CB-6630) Removed OkHttp from core library. It's now available as a plugin: [cordova-plugin-okhttp](https://www.npmjs.com/package/cordova-plugin-okhttp)
./node_modules/useragent/lib/regexps.js:208:parser[0] = new RegExp("(Google-HTTP-Java-Client|Apache-HttpClient|http%20client|Python-urllib|HttpMonitor|TLSProber|WinHTTP|JNLP|okhttp)(?:[ /](\\d+)(?:\\.(\\d+)(?:\\.(\\d+))?)?)?");
./node_modules/useragent/lib/regexps.js:1034:parser[0] = new RegExp("^(AntennaPod|WMPlayer|Zune|Podkicker|Radio|ExoPlayerDemo|Overcast|PocketTunes|NSPlayer|okhttp|DoggCatcher|QuickNews|QuickTime|Peapod|Podcasts|GoldenPod|VLC|Spotify|Miro|MediaGo|Juice|iPodder|gPodder|Banshee)/(\\d+)\\.(\\d+)\\.?(\\d+)?\\.?(\\d+)?");
./node_modules/cordova-plugin-advanced-http/plugin.xml:81:    <framework src="com.squareup.okhttp3:okhttp-urlconnection:$OKHTTP_VERSION"/>
```

**Comment by zyhzx123e** [comment]
i encounter this error as well, but in my case, is when i call the post , get second time, it crashes

**Comment by zyhzx123e** [comment]
Finally solved the issue, the issue bcz the okhttp of other depencies, plugin use different version of okhttp, make sure u chk your declaration in config file like gradle, all okhttp prefix should have same version, in case like 3+ and 3.10.0, make sure change the 3+ to 3.10.0(explicit)
