### ISSUE TITLE
TypeError: Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by Lweaver5051** [ionic-team/ionic#19758]
Please help, I recently updated my project to the latest Iconic, NodeJs and Cordova versions and when I would try to run my application I get a blank form with the error below. I have searched for a solution but nothing has helped. Thank you in advance 

ionic-app-script task: "build" 
TypeError: Cannot read property 'compilation' of undefined 
TypeError: Cannot read property 'compilation' of undefined
    at DefinePlugin.apply (\node_modules\webpack\lib\DefinePlugin.js:97:18)
    at Compiler.apply (\node_modules\@ionic\app-scripts\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (\node_modules\@ionic\app-scripts\node_modules\webpack\lib\webpack.js:33:19)
    at \node_modules\@ionic\app-scripts\dist\webpack.js:132:24
    at new Promise (<anonymous>)
    at runWebpackFullBuild (\node_modules\@ionic\app-scripts\dist\webpack.js:113:12)
    at webpackWorker (\node_modules\@ionic\app-scripts\dist\webpack.js:70:19)
    at Object.webpack (\node_modules\@ionic\app-scripts\dist\webpack.js:29:12)
    at bundleWorker (\node_modules\@ionic\app-scripts\dist\bundle.js:13:22)
    at Object.bundle (\node_modules\@ionic\app-scripts\dist\bundle.js:6:12)
[ERROR] An error occurred while running subprocess ionic-app-scripts.

Package.json

{
  "name": "my project",
  "version": "0.0.1",
  "author": "",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0",
    "@angular/animations": "^8.2.12",
    "@angular/common": "^8.2.12",
    "@angular/core": "^8.2.12",
    "@angular/forms": "^8.2.12",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "^8.2.12",
    "@angular/platform-browser-dynamic": "^8.2.12",
    "@angular/platform-server": "^8.2.12",
    "@angular/router": "^8.2.12",
    "@ionic-native/core": "5.0.0-beta.21",
    "@ionic-native/email-composer": "^5.15.1",
    "@ionic-native/file": "^5.15.1",
    "@ionic-native/file-opener": "^5.15.1",
    "@ionic-native/file-transfer": "^5.15.1",
    "@ionic-native/geolocation": "^5.15.1",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/native-geocoder": "^5.15.1",
    "@ionic-native/social-sharing": "^5.15.1",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "^4.0.0-beta.16",
    "@ionic/pro": "2.0.3",
    "@ionic/storage": "^2.2.0",
    "@storybook/vue": "^4.0.0-alpha.25",
    "agm-core": "^1.0.0-beta.5",
    "chart.js": "^2.8.0",
    "cordova-android": "7.1.4",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "4.5.5",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic": "^5.2.7",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.1",
    "cordova-plugin-smtp-client": "^2.0.11",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.3",
    "core-js": "^2.5.4",
    "dotenv-webpack": "^1.7.0",
    "eslint": "^6.5.1",
    "file-saver": "^2.0.2",
    "geolocation": "^0.2.0",
    "grunt": "^1.0.3",
    "inherits": "^2.0.4",
    "inject-html-webpack-plugin": "0.0.39",
    "ionic-angular": "^3.9.9",
    "ionic-native": "^2.9.0",
    "ngx-papaparse": "^4.0.4",
    "npm": "^6.12.0",
    "promise-polyfill": "8.1.3",
    "rx-subject": "^3.1.0",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "xlsx": "^0.15.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.10.0",
    "@angular-devkit/build-angular": "^0.803.12",
    "@angular-devkit/core": "~7.0.0",
    "@angular-devkit/schematics": "~7.0.0",
    "@angular/cdk": "^8.2.3",
    "@angular/cli": "~7.0.0",
    "@angular/compiler": "^8.2.12",
    "@angular/compiler-cli": "^8.2.12",
    "@angular/language-service": "~7.0.0",
    "@babel/core": "^7.6.4",
    "@babel/register": "^7.6.2",
    "@ionic/angular-toolkit": "~1.2.0",
    "@ionic/app-scripts": "^3.2.4",
    "@ionic/cli-plugin-cordova": "^1.6.2",
    "@ionic/lab": "1.0.15",
    "@types/googlemaps": "^3.38.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "grunt-contrib-jshint": "^2.0.0",
    "html-webpack-plugin": "^3.2.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "^3.6.4",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.9"
  },
  "peerDependencies": {
    "html-webpack-plugin": "^3.0.4 || ^4.0.0-0",
    "webpack": "^4.0.0"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-nativegeocoder": {},
      "cordova-plugin-geolocation": {},
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-email-composer": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-file": {},
      "cordova-plugin-file-opener2": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      }
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}

Ionic info:

   Ionic CLI          : 5.4.4 (C:\Users\<>\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 16 other plugins)

Utility:
   cordova-res : not installed
   native-run  : 0.2.8

System:
   NodeJS : v12.13.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.12.0
   OS     : Windows 10

**Comment by Lweaver5051** [comment]
I had to uninstall several packages and get the latest versions that corrected the issue
