### ISSUE TITLE
Is building Windows UWP apps supported using Ionic 4?

### ISSUE THREAD

**Issue by srinidhirao** [ionic-team/ionic#20325]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**
Building Windows UWP apps seems to be broken in Ionic 4

**Expected behavior:**

Is Building Windows UWP apps supported in Ionic 4?

**Steps to reproduce:**

1. Create a new Ionic 4 app targeting Windows.
2. Add a Camera Plugin.
3. Try to use the Camera Plugin.
4. You get an error saying JavaScript runtime error: Function expected

**Related code:**
The error exception
```
Exception was thrown at line 81605, column 56 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 15744, column 9 in ms-appx-web://io.ionic.starter/www/build/vendor.js
0x800a138a - JavaScript runtime error: Function expected
Exception was thrown at line 3, column 19746 in ms-appx-web://io.ionic.starter/www/build/polyfills.js
0x800a139e - JavaScript runtime error: Uncaught (in promise): TypeError: Function expected
TypeError: Function expected
   at Camera.prototype.getPicture (ms-appx-web://io.ionic.starter/www/build/vendor.js:81605:56)
   at ContactPage (ms-appx-web://io.ionic.starter/www/build/main.js:146:9)
   at createClass (ms-appx-web://io.ionic.starter/www/build/vendor.js:13119:13)
   at createDirectiveInstance (ms-appx-web://io.ionic.starter/www/build/vendor.js:12962:5)
   at createViewNodes (ms-appx-web://io.ionic.starter/www/build/vendor.js:14420:21)
   at createRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:14309:5)
   at callWithDebugContext (ms-appx-web://io.ionic.starter/www/build/vendor.js:15734:9)
   at debugCreateRootView (ms-appx-web://io.ionic.starter/www/build/vendor.js:15017:5)
   at ComponentFactory_.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:11914:9)
   at ComponentFactoryBoundToModule.prototype.create (ms-appx-web://io.ionic.starter/www/build/vendor.js:4666:9)
```

```
insert short code snippets here
```

**Other information:**

Is any-one building apps targeting Windows UWP using Ionic 4? If yes, do you have any issues using the plugins in Ionic 4?

**Ionic info:**

```
C:\Users\VPNUser\Documents\MyIonicProject>ionic info

Ionic:

   ionic (Ionic CLI)  : 4.5.0 (C:\Users\VPNUser\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : windows 6.0.1
   Cordova Plugins       : not available

System:

   NodeJS : v12.14.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.13.4
   OS     : Windows 10
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. Yes, building Windows UWP apps are supported using Ionic 4. Can you provide a repo with the code required to reproduce this issue?
