### ISSUE TITLE
bug: TypeError: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic#20924]
# Bug Report

**Ionic version:**

[x] **5.x**

**Current behavior:**

when running the command `$ ionic cordova build android/ios --prod` I get the error:
```
ERROR in ./node_modules/@ionic/angular/fesm5/ionic-angular.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/Desktop/dicus/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/application/app/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/application/app/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/application/app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/application/app/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/application/app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/application/app/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/application/app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/application/app/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/application/app/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/application/app/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/application/app/node_modules/typescript/lib/typescript.js:16599:21)
[ERROR] An error occurred while running subprocess ng.
```
**Expected behavior:**

build without a problem

**Steps to reproduce:**

run command above
**Related code:**

```
insert short code snippets here
```

**Other information:**

I have been reading a lot of different post but can't seem to find one that solves my issue:
[1](https://stackoverflow.com/questions/58694820/cannot-read-property-kind-of-undefined)
[2](https://stackoverflow.com/questions/57891605/angular-cli-build-prod-typeerror-cannot-read-property-kind-of-undefined)
[3](https://github.com/microsoft/TypeScript/issues/28810)
[4](https://forum.ionicframework.com/t/ionic-3-x-unable-to-build-using-the-prod-typeerror-cannot-read-property-kind-of-undefined/133689)

I can't seem to get it to work.

**Ionic info:**

```
Ionic:

   Ionic CLI                     : 6.3.0 (/Users/me/.config/yarn/global/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.801.2
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res (update available: 0.11.0) : 0.9.0
   native-run                             : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.11.0 (/usr/local/Cellar/node/13.11.0/bin/node)
   npm               : 6.13.7
   OS                : macOS Mojave
   Xcode             : Xcode 11.3.1 Build version 11C504
```
Angular
```
angular-cli: 1.0.0-beta.28.3
node: 13.11.0
os: darwin x64
@angular/cdk: 8.2.3
@angular/common: 8.2.14
@angular/core: 8.2.14
@angular/forms: 8.2.14
@angular/platform-browser: 8.2.14
@angular/platform-browser-dynamic: 8.2.14
@angular/router: 8.2.14
@angular/cli: 8.3.26
@angular/compiler: 8.2.14
@angular/compiler-cli: 8.2.14
@angular/language-service: 8.2.14
```

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as this does not appear to be a bug in Ionic Framework. The error appears to be coming from `@angular-devkit/build-optimizer`.

`Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):`

You might want to try updating that dependency to `0.803.26` which seems to more closely align with the Angular version of `8.3.26`.
