### ISSUE TITLE
ion-refresher  TypeError: Cannot read property 'querySelector' of null 

### ISSUE THREAD

**Issue by shuto-fandd** [ionic-team/ionic#21229]
**Ionic version:**

[] **4.x**
[ x] **5.1.0**

**I'm submitting a ...** 

[ x] bug report
[ ] feature request

**Current behavior:**

When I use Android 7.0 to open a page has ion-refresher, the console throws an error
```bash
TypeError: Cannot read property 'querySelector' of null
    at Refresher._callee6$ (https://-app/49-es5.js:1006:68)
    at tryCatch (https://xxx-app/polyfills-es5.js:14014:21)
    at GeneratorFunctionPrototype.invoke [as _invoke] (https://cne-app/polyfills-es5.js:14234:26)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (https://xxx-app/polyfills-es5.js:14067:25)
    at asyncGeneratorStep (https://xxx-app/49-es5.js:3:103)
    at _next (https://xxx-app/49-es5.js:5:194)
    at ZoneDelegate.invoke (https://xxx-app/polyfills-es5.js:15149:166)
    at Zone.run (https://xxx-app/polyfills-es5.js:14810:43)
    at https://xxx-app/polyfills-es5.js:15801:32
    at ZoneDelegate.invokeTask (https://xxx-app/polyfills-es5.js:15185:179)
```
Then I checked 49-es5.js:1006:68, and the error code is:
```javascript
 997                   console.error('<ion-refresher> must be used inside an <ion-content>');
998                    return _context6.abrupt("return");
999
1000                  case 7:
1001                    _context6.next = 9;
1002                    return contentEl.getScrollElement();
1003
1004                  case 9:
1005                    this.scrollEl = _context6.sent;
1006                    this.backgroundContentEl = contentEl.shadowRoot.querySelector('#background-content');

```
**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```html
<ion-content class="xxx">
    <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
      <ion-refresher-content pullingText="下拉刷新"
                             refreshingSpinner=""
                             refreshingText="">
      </ion-refresher-content>
    </ion-refresher>
</ion-content>
```

**Other information:**

**Ionic info:** 

```
% ionic info                 

Ionic:

   Ionic CLI                     : 6.7.0 (/Users/xxx/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.901.3
   @angular-devkit/schematics    : 9.1.3
   @angular/cli                  : 9.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.14.0
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 (/Volumes/data/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v13.10.0 (/Users/xxx/node/v13.10.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.4.1 Build version 11E503a
```

**Comment by shuto-fandd** [comment]
Step 1. Clone demo app from https://github.com/shuto-fandd/ionic-refresher-error-demo.git
Step 2. Initialize the project.
Step 3. exec Ionic cordova platform add android@8.1.
Step 4. Launch an Android simulator based on sdk24.
Step 5. Run demo app on the simulator.
Step 6. Open the chrome console to view errors

**Comment by liamdebeasi** [comment]
Thanks for the issue. Can you try the following dev build and let me know if it resolves the issue?

`npm i @ionic/angular@5.2.0-dev.202005071702.2c7ae64`

**Comment by shuto-fandd** [comment]
It worked. Perfect.

**Comment by liamdebeasi** [comment]
Glad to hear it is working! I am going to keep this issue open until the fix has been merged in.

**Comment by liamdebeasi** [comment]
Thanks for the issue. This has been resolved via https://github.com/ionic-team/ionic/pull/21237 and a fix will be available in an upcoming release of Ionic Framework.
