### ISSUE TITLE
support: Default test is failing

### ISSUE THREAD

**Issue by chemisax** [ionic-team/ionic#21696]
Hello,

I'm running the test that comes by default with Ionic 5 React, but it fails with the following error:

```
ReferenceError: customElements is not defined

      4 | 
      5 | test('renders without crashing', () => {
    > 6 |   const { baseElement } = render(<App />);
        |                           ^
      7 |   expect(baseElement).toBeDefined();
      8 | });
      9 | 

      at createOverlay (node_modules/@ionic/core/dist/cjs/overlays-7b6de5e6.js:38:5)
      at Object.create (node_modules/@ionic/core/dist/cjs/overlays-7b6de5e6.js:11:20)
      at Overlay.present (node_modules/@ionic/react/src/components/createOverlayComponent.tsx:91:39)
      at Overlay.componentDidMount (node_modules/@ionic/react/src/components/createOverlayComponent.tsx:50:14)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19814:22)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
```

I understand that the testing tooling used here is the one that comes with create-react-app, so we don't have much control over it, It appears that the library that is using is a little bit old, so customElements are not supported. I think customElements is used by the IonicOverlay component that I am using (I wonder why Ionic ships components that have not been tested with the default tooling).

**Does anyone know how to configure the tests so it can support testing of customElements?** 

Thank you

**Comment by elylucas** [comment]
Hi @chemisax,

We have a blog that goes over testing here: https://ionicframework.com/blog/testing-ionic-react-apps-with-jest-and-react-testing-library/

I wasn't able to reproduce having the test fail from a fresh app, though. Did you modify the code at all? And which starter did you use?

Thanks
