### ISSUE TITLE
VirtualScroll renders empty elements (and can crash)

### ISSUE THREAD

**Issue by wli** [ionic-team/ionic#6912]
#### Short description of the problem:

VirtualScroll sometimes renders a `*virtualItem` by passing it an empty dict. This causes template crashes if accessing nested attributes. It also renders extra blank elements.
#### What behavior are you expecting?

VirtualScroll should never pass empty dicts to `*virtualItem`, and there should not be any crashes.

**Steps to reproduce:**
1. Create an array of 2 nested elements.
2. Create a virtualScroll and render a nested child
3. Observe three elements instead of 2

``` js
this.items = [{parent: {child: "hello"}}, {parent: {child: "world"}}];
```

``` html
    <ion-list [virtualScroll]="items">
      <ion-item *virtualItem="let item">
        {{ item.parent.child }}
      </ion-item>
    </ion-list>
```

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
![1465946468433screensave](https://cloud.githubusercontent.com/assets/649892/16063034/05246bbe-324c-11e6-9c16-0ec4777a489d.png)

**Which Ionic Version?** 1.x or 2.x
2.0.0-beta.8
#### Plunker that shows an example of your issue

http://plnkr.co/edit/NS25MBPrTOvqwMNHhLhp?p=preview

Punker doesn't crash for whatever reason, but I can try a similar thing locally and this is the sample output:

```
TypeError: Cannot read property 'text' of undefined
    at DebugAppView._View_InactiveConversationsPage2.detectChangesInternal (InactiveConversationsPage.template.js:451:73)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:29234:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:29323:44)
    at DebugAppView.AppView.detectContentChildrenChanges (http://localhost:8100/build/js/app.bundle.js:29249:37)
    at DebugAppView._View_InactiveConversationsPage0.detectChangesInternal (InactiveConversationsPage.template.js:170:8)
    at DebugAppView.AppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:29234:14)
    at DebugAppView.detectChanges (http://localhost:8100/build/js/app.bundle.js:29323:44)
    at ViewRef_.detectChanges (http://localhost:8100/build/js/app.bundle.js:29655:65)
    at VirtualScroll.renderVirtual (http://localhost:8100/build/js/app.bundle.js:64761:18)
    at http://localhost:8100/build/js/app.bundle.js:64744:18
```

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Cordova CLI: 6.0.0
Ionic Framework Version: 2.0.0-beta.8
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Distributor ID: Ubuntu Description: Ubuntu 16.04 LTS 
Node Version: v5.8.0
```

**Comment by lohanidamodar** [comment]
I am having same problem! Any solution?

**Comment by jgw96** [comment]
Hello all! Is this still an issue with the latest version of ionic? Thanks!

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!
